Budget::Ninja::Data::AppropriationSelector
System.ComponentModel.IContainer Budget.Ninja.Data.AppropriationSelector.components
Required designer variable.
Referenced by Budget.Ninja.Data.AppropriationSelector.Dispose.
Syncfusion.Windows.Forms.Tools.Carousel Budget.Ninja.Data.AppropriationSelector.AppropriationCarousel
Budget.Ninja.Data.AppropriationSelector.AppropriationSelector()
References Budget.Ninja.Data.AppropriationSelector.AppropriationCarousel_OnImageSelected, Budget.Ninja.Data.AppropriationSelector.GetAppropriationCarouselImageList, Budget.Ninja.Data.AppropriationSelector.InitializeComponent.
void Budget.Ninja.Data.AppropriationSelector.AppropriationCarousel_OnImageSelected(object sender, EventArgs e)
Referenced by Budget.Ninja.Data.AppropriationSelector.AppropriationSelector.
void Budget.Ninja.Data.AppropriationSelector.GetAppropriationCarouselImageList()
Referenced by Budget.Ninja.Data.AppropriationSelector.AppropriationSelector.
void Budget.Ninja.Data.AppropriationSelector.InitializeComponent()
Required method for Designer support - do not modify the contents of this method with the code editor.
Referenced by Budget.Ninja.Data.AppropriationSelector.AppropriationSelector.
override void Budget.Ninja.Data.AppropriationSelector.Dispose(bool disposing)
Clean up any resources being used.
disposing true if managed resources should be disposed; otherwise, false.
References Budget.Ninja.Data.AppropriationSelector.components.