BudgetExecution::FormData
BindingSource BudgetExecution.FormData.BindingSource
Referenced by BudgetExecution.FormData.FormData.
DataSet BudgetExecution.FormData.BudgetData
Referenced by BudgetExecution.FormData.FormData.
PrcMetric BudgetExecution.FormData.BudgetMetric
Referenced by BudgetExecution.FormData.FormData.
ChartControl BudgetExecution.FormData.Chart
ChartDataBindModel BudgetExecution.FormData.ChartModel
int BudgetExecution.FormData.Count
DataBuilder BudgetExecution.FormData.Data
Referenced by BudgetExecution.FormData.FormData.
DataGridView BudgetExecution.FormData.DataGrid
Referenced by BudgetExecution.FormData.FormData.
decimal [] BudgetExecution.FormData.Metrics
BindingNavigator BudgetExecution.FormData.Navigator
Referenced by BudgetExecution.FormData.FormData.
FlowLayoutPanel BudgetExecution.FormData.Panel
Referenced by BudgetExecution.FormData.AppropriationButton_OnSelect, BudgetExecution.FormData.BocButton_OnSelect, BudgetExecution.FormData.BocListBoxItem_OnSelect.
DataTable BudgetExecution.FormData.Table
Referenced by BudgetExecution.FormData.AppropriationButton_OnSelect, BudgetExecution.FormData.AppropriationListBoxItem_OnSelect, BudgetExecution.FormData.BocButton_OnSelect, BudgetExecution.FormData.BocListBoxItem_OnSelect, BudgetExecution.FormData.FormData, BudgetExecution.FormData.ReturnButton_OnClick.
bool BudgetExecution.FormData.Percent
BudgetExecution.FormData.FormData()
BudgetExecution.FormData.FormData(DataBuilder data, BindingSource bs, DataGridView dgv, BindingNavigator bn)
References BudgetExecution.FormData.BindDataGridAndNavigator, BudgetExecution.FormData.BindingSource, BudgetExecution.FormData.BudgetData, BudgetExecution.FormData.BudgetMetric, BudgetExecution.FormData.Data, BudgetExecution.FormData.DataGrid, BudgetExecution.FormData.Navigator, BudgetExecution.FormData.Table.
DataTable BudgetExecution.FormData.FilterTable(DataTable table, string column, string filter)
decimal BudgetExecution.FormData.GetAverage(DataTable table)
References BudgetExecution.Average, BudgetExecution.M, BudgetExecution.Select.
string [] BudgetExecution.FormData.GetCodes(DataTable table, string column)
References BudgetExecution.Select.
Referenced by BudgetExecution.FormData.GetDataTotals, BudgetExecution.FormData.GetProgramElements, BudgetExecution.FormData.PopulateBocFilterBox, BudgetExecution.FormData.PopulateFundFilterButtonBox, BudgetExecution.FormData.PopulateFundFilterListBox.
Dictionary<string, decimal> BudgetExecution.FormData.GetDataTotals(DataTable table, string column, string filter)
References BudgetExecution.FormData.GetCodes.
PRC [] BudgetExecution.FormData.GetPrcArray(DataTable table)
References BudgetExecution.PRC, BudgetExecution.Select.
Dictionary<string, string[]> BudgetExecution.FormData.GetProgramElements(DataTable table)
References BudgetExecution.FormData.GetCodes.
DataTable BudgetExecution.FormData.GetTable(DataTable table, string column, string filter)
Referenced by BudgetExecution.FormData.AppropriationButton_OnSelect, BudgetExecution.FormData.AppropriationListBoxItem_OnSelect, BudgetExecution.FormData.BocButton_OnSelect, BudgetExecution.FormData.BocListBoxItem_OnSelect.
decimal BudgetExecution.FormData.GetTotal(DataTable table)
References BudgetExecution.M.
Dictionary<string, decimal> BudgetExecution.FormData.GetTotals(DataTable table, string[] filters, string column)
void BudgetExecution.FormData.AppropriationButton_OnSelect(object sender, EventArgs e)
References BudgetExecution.FormData.GetTable, BudgetExecution.FormData.Panel, BudgetExecution.FormData.PopulateBocFilterBox, BudgetExecution.FormData.Table.
Referenced by BudgetExecution.FormData.PopulateFundFilterButtonBox.
void BudgetExecution.FormData.AppropriationListBoxItem_OnSelect(object sender, EventArgs e)
References BudgetExecution.FormData.GetTable, BudgetExecution.FormData.Table.
Referenced by BudgetExecution.FormData.PopulateFundFilterListBox.
void BudgetExecution.FormData.BindDataGridAndNavigator(DataTable table, DataGridView dg, BindingSource bs, BindingNavigator bn)
References BudgetExecution.FormData.ConfigureGridColumns.
Referenced by BudgetExecution.FormData.FormData.
void BudgetExecution.FormData.BindTextBox(BindingSource bs, TextBox tb, string field)
void BudgetExecution.FormData.BocButton_OnSelect(object sender, EventArgs e)
References BudgetExecution.FormData.GetTable, BudgetExecution.FormData.Panel, BudgetExecution.FormData.PopulateBocFilterBox, BudgetExecution.FormData.Table.
Referenced by BudgetExecution.FormData.PopulateBocFilterBox.
void BudgetExecution.FormData.BocListBoxItem_OnSelect(object sender, EventArgs e)
References BudgetExecution.FormData.GetTable, BudgetExecution.FormData.Panel, BudgetExecution.FormData.PopulateBocFilterBox, BudgetExecution.FormData.Table.
void BudgetExecution.FormData.ConfigureTabControl(MetroForm form, TabControlAdv tab, DataBuilder Ninja)
References BudgetExecution.DataBuilder.DataQuery, BudgetExecution.Query.Source.
void BudgetExecution.FormData.PopulateFundFilterButtonBox(DataTable table, Control filterPanel)
References BudgetExecution.FormData.AppropriationButton_OnSelect, BudgetExecution.FormData.GetCodes, BudgetExecution.FormData.PopulateFilterButtons.
void BudgetExecution.FormData.PopulateFundFilterListBox(DataTable table, Control filterPanel)
References BudgetExecution.FormData.AppropriationListBoxItem_OnSelect, BudgetExecution.FormData.GetCodes, BudgetExecution.FormData.PopulateFilterListItems.
void BudgetExecution.FormData.PopulateBocFilterBox(DataTable table, FlowLayoutPanel filterPanel)
References BudgetExecution.FormData.BocButton_OnSelect, BudgetExecution.FormData.GetCodes, BudgetExecution.FormData.PopulateFilterButtons.
Referenced by BudgetExecution.FormData.AppropriationButton_OnSelect, BudgetExecution.FormData.BocButton_OnSelect, BudgetExecution.FormData.BocListBoxItem_OnSelect.
void BudgetExecution.FormData.PopulateFilterButtons(Control panel, string[] list)
Referenced by BudgetExecution.FormData.PopulateBocFilterBox, BudgetExecution.FormData.PopulateFundFilterButtonBox.
void BudgetExecution.FormData.PopulateFilterListItems(Control panel, string[] list)
Referenced by BudgetExecution.FormData.PopulateFundFilterListBox.
void BudgetExecution.FormData.ConfigureFormSettings(MetroForm form)
void BudgetExecution.FormData.ConfigureGridColumns(DataGridView dgv)
Referenced by BudgetExecution.FormData.BindDataGridAndNavigator.
void BudgetExecution.FormData.ReturnButton_OnClick(object sender, EventArgs e)
References BudgetExecution.FormData.Table.