BudgetExecution::MainForm
GetChart BudgetExecution.MainForm.Chart
Referenced by BudgetExecution.MainForm.ChartTimer, BudgetExecution.MainForm.MainForm.
int BudgetExecution.MainForm.Counter
Referenced by BudgetExecution.MainForm.ChartTimer, BudgetExecution.MainForm.MainForm_Load.
DataBuilder BudgetExecution.MainForm.D6
Referenced by BudgetExecution.MainForm.MainForm.
PrcMetric BudgetExecution.MainForm.Metric
Referenced by BudgetExecution.MainForm.MainForm.
FormData BudgetExecution.MainForm.NinjaData
Referenced by BudgetExecution.MainForm.MainForm.
DataBuilder BudgetExecution.MainForm.R6
Referenced by BudgetExecution.MainForm.MainForm.
string [] BudgetExecution.MainForm.Title
Referenced by BudgetExecution.MainForm.ChartTimer, BudgetExecution.MainForm.MainForm.
Dictionary<string, double> [] BudgetExecution.MainForm.Values
Referenced by BudgetExecution.MainForm.ChartTimer, BudgetExecution.MainForm.MainForm.
Timer BudgetExecution.MainForm.Timer
Referenced by BudgetExecution.MainForm.MainForm.
System.ComponentModel.IContainer BudgetExecution.MainForm.components
Required designer variable.
Referenced by BudgetExecution.MainForm.Dispose.
Syncfusion.Windows.Forms.Tools.HubTile BudgetExecution.MainForm.SummaryTile
Syncfusion.Windows.Forms.Tools.HubTile BudgetExecution.MainForm.DataTile
System.Windows.Forms.Button BudgetExecution.MainForm.RegionSummaryButton
System.Windows.Forms.Button BudgetExecution.MainForm.DataButton
System.Windows.Forms.Button BudgetExecution.MainForm.TransferButton
System.Windows.Forms.Button BudgetExecution.MainForm.DocumentButton
System.Windows.Forms.Button BudgetExecution.MainForm.DivisionSummaryButton
System.Windows.Forms.Button BudgetExecution.MainForm.DivisionBtn
Syncfusion.Windows.Forms.Chart.ChartControl BudgetExecution.MainForm.MainChart
Referenced by BudgetExecution.MainForm.ChartTimer, BudgetExecution.MainForm.GetMainChart, BudgetExecution.MainForm.MainForm.
BudgetExecution.MainForm.MainForm()
References BudgetExecution.MainForm.Chart, BudgetExecution.MainForm.D6, BudgetExecution.MainForm.DivisionSummaryButton_OnClick, BudgetExecution.GetChart, BudgetExecution.MainForm.GetChartTitles, BudgetExecution.PrcMetric.GetChartTotals, BudgetExecution.MainForm.GetMainChart, BudgetExecution.MainForm.InitializeComponent, BudgetExecution.MainForm.MainChart, BudgetExecution.MainForm.Metric, BudgetExecution.MainForm.NinjaData, BudgetExecution.DataBuilder.QueryTable, BudgetExecution.MainForm.R6, BudgetExecution.MainForm.RegionSummaryButton_OnClick, BudgetExecution.MainForm.Timer, BudgetExecution.MainForm.Title, BudgetExecution.MainForm.TransferButton_OnClick, BudgetExecution.MainForm.Values.
void BudgetExecution.MainForm.MainForm_Load(object sender, EventArgs e)
References BudgetExecution.MainForm.ChartTimer, BudgetExecution.MainForm.Counter.
void BudgetExecution.MainForm.ChartTimer(object sender, EventArgs e)
References BudgetExecution.MainForm.Chart, BudgetExecution.MainForm.Counter, BudgetExecution.MainForm.MainChart, BudgetExecution.MainForm.Title, BudgetExecution.MainForm.Values.
Referenced by BudgetExecution.MainForm.MainForm_Load.
void BudgetExecution.MainForm.DataButton_OnClick(object sender, EventArgs e)
void BudgetExecution.MainForm.DivisionSummaryButton_OnClick(object sender, EventArgs e)
Referenced by BudgetExecution.MainForm.MainForm.
string [] BudgetExecution.MainForm.GetChartTitles(Dictionary< string, double >[] info)
Referenced by BudgetExecution.MainForm.MainForm.
ChartControl BudgetExecution.MainForm.GetMainChart(ChartControl chart, string[] title, Dictionary< string, double > data)
References BudgetExecution.MainForm.MainChart.
Referenced by BudgetExecution.MainForm.MainForm.
ChartControl BudgetExecution.MainForm.GetMainChart(ChartControl chart, string title, Dictionary< string, double > data)
References BudgetExecution.MainForm.MainChart.
void BudgetExecution.MainForm.RegionSummaryButton_OnClick(object sender, EventArgs e)
Referenced by BudgetExecution.MainForm.MainForm.
void BudgetExecution.MainForm.TransferButton_OnClick(object sender, EventArgs e)
Referenced by BudgetExecution.MainForm.MainForm.
void BudgetExecution.MainForm.DataTile_OnClick(object sender, EventArgs e)
References BudgetExecution.Info.DivisionImages.
void BudgetExecution.MainForm.SummaryTile_OnClick(object sender, EventArgs e)
References BudgetExecution.Info.SummaryImages.
void BudgetExecution.MainForm.DocumentButton_OnClick(object sender, EventArgs e)
References BudgetExecution.Info.FunctionImages.
void BudgetExecution.MainForm.TransferButton_Click(object sender, EventArgs e)
void BudgetExecution.MainForm.InitializeComponent()
Required method for Designer support - do not modify the contents of this method with the code editor.
References BudgetExecution.D, BudgetExecution.F.
Referenced by BudgetExecution.MainForm.MainForm.
override void BudgetExecution.MainForm.Dispose(bool disposing)
Clean up any resources being used.
disposing true if managed resources should be disposed; otherwise, false.
References BudgetExecution.MainForm.components.