BudgetExecution::DocInfo
List<string> BudgetExecution.DocInfo.AccountingInfo
Referenced by BudgetExecution.DocInfo.DocInfo.
decimal BudgetExecution.DocInfo.Awards
List<string> BudgetExecution.DocInfo.ControlInfo
string BudgetExecution.DocInfo.ControlNumber
Referenced by BudgetExecution.DocInfo.DocInfo, BudgetExecution.DocInfo.GetDocmumentDictionary.
List<string> BudgetExecution.DocInfo.ControlNumbers
string BudgetExecution.DocInfo.DateIssued
string BudgetExecution.DocInfo.DcnPrefix
DivisionAuthority BudgetExecution.DocInfo.DivisionBudget
Referenced by BudgetExecution.DocInfo.DocInfo.
List<string> BudgetExecution.DocInfo.DocumentHeader
Referenced by BudgetExecution.DocInfo.DocInfo.
Org BudgetExecution.DocInfo.Organization
decimal BudgetExecution.DocInfo.OverTime
string BudgetExecution.DocInfo.Purpose
Referenced by BudgetExecution.DocInfo.GetDocmumentDictionary.
List<Transfer> BudgetExecution.DocInfo.Reprogrammings
List<string> BudgetExecution.DocInfo.SignatureBlock
Referenced by BudgetExecution.DocInfo.DocInfo.
Dictionary<string, object> BudgetExecution.DocInfo.Suppplemental
int BudgetExecution.DocInfo.TimeOffAwards
PRC BudgetExecution.DocInfo.Training
BudgetExecution.DocInfo.DocInfo()
BudgetExecution.DocInfo.DocInfo(DivisionAuthority budget)
References BudgetExecution.DocInfo.AccountingInfo, BudgetExecution.DocInfo.ControlNumber, BudgetExecution.DocInfo.DivisionBudget, BudgetExecution.DocInfo.DocumentHeader, BudgetExecution.DocInfo.GetAccountingInfo, BudgetExecution.DocInfo.GetControlNumber, BudgetExecution.DocInfo.GetDocumentHeader, BudgetExecution.DocInfo.GetSignatureInfo, BudgetExecution.DocInfo.SignatureBlock.
List<string> BudgetExecution.DocInfo.GetAccountingInfo()
Referenced by BudgetExecution.DocInfo.DocInfo.
string BudgetExecution.DocInfo.GetControlNumber()
References BudgetExecution.DivisionAuthority.FiscalYear.
Referenced by BudgetExecution.DocInfo.DocInfo.
Dictionary<string, string> BudgetExecution.DocInfo.GetDocmumentDictionary()
References BudgetExecution.DocInfo.ControlNumber, BudgetExecution.DivisionAuthority.FiscalYear, BudgetExecution.DocInfo.Purpose.
List<string> BudgetExecution.DocInfo.GetDocumentHeader()
Referenced by BudgetExecution.DocInfo.DocInfo.
List<string> BudgetExecution.DocInfo.GetManagementHeader()
int BudgetExecution.DocInfo.GetNewDocNumber()
References BudgetExecution.DataBuilder.QueryTable.
List<string> BudgetExecution.DocInfo.GetSignatureInfo()
Referenced by BudgetExecution.DocInfo.DocInfo.