BudgetExecution::ExcelOp
string BudgetExecution.ExcelOp.P7path
Referenced by BudgetExecution.ExcelOp.ExcelOp, BudgetExecution.ExcelOp.ExportData.
DataTable BudgetExecution.ExcelOp.Data
Referenced by BudgetExecution.ExcelOp.ExcelOp.
string BudgetExecution.ExcelOp.FilePath
Referenced by BudgetExecution.ExcelOp.ExcelOp.
string BudgetExecution.ExcelOp.ConnectionString
Referenced by BudgetExecution.ExcelOp.ExcelOp.
DocInfo BudgetExecution.ExcelOp.AccountingInfo
Excel BudgetExecution.ExcelOp.Excel
Referenced by BudgetExecution.ExcelOp.Create.
BudgetExecution.ExcelOp.ExcelOp()
BudgetExecution.ExcelOp.ExcelOp(string filepath)
References BudgetExecution.ExcelOp.ConnectionString, BudgetExecution.ExcelOp.FilePath, BudgetExecution.ExcelOp.GetConnectionString.
BudgetExecution.ExcelOp.ExcelOp(DataTable data)
References BudgetExecution.ExcelOp.ConnectionString, BudgetExecution.ExcelOp.Data, BudgetExecution.ExcelOp.FilePath, BudgetExecution.ExcelOp.GetConnectionString, BudgetExecution.ExcelOp.P7path.
string BudgetExecution.ExcelOp.GetConnectionString(string filepath)
Referenced by BudgetExecution.ExcelOp.ExcelOp.
Workbook BudgetExecution.ExcelOp.ExportData(DataTable table)
References BudgetExecution.ExcelOp.Create, BudgetExecution.ExcelOp.P7path.
Workbook BudgetExecution.ExcelOp.ExportData(string filepath, DataTable table)
References BudgetExecution.ExcelOp.Create.
string BudgetExecution.ExcelOp.GetExternalFile()
Workbook BudgetExecution.ExcelOp.OpenFile(string filepath)
References BudgetExecution.ExcelOp.Create.
Workbook BudgetExecution.ExcelOp.OpenNew()
References BudgetExecution.ExcelOp.Create.
void BudgetExecution.ExcelOp.SaveAs(Workbook wb, string filepath)
Excel BudgetExecution.ExcelOp.Create()
References BudgetExecution.ExcelOp.Excel.
Referenced by BudgetExecution.ExcelOp.ExportData, BudgetExecution.ExcelOp.OpenFile, BudgetExecution.ExcelOp.OpenNew.
void BudgetExecution.ExcelOp.ReleaseObject(object obj)