BudgetExecution::DataManager
DataBuilder BudgetExecution.DataManager.Data
Referenced by BudgetExecution.DataManager.DataManager.
PrcMetric BudgetExecution.DataManager.Metric
Referenced by BudgetExecution.DataManager.DataManager.
FormData BudgetExecution.DataManager.Ninja
Referenced by BudgetExecution.DataManager.DataManager.
Dictionary<string, string[]> BudgetExecution.DataManager.ProgramElements
Referenced by BudgetExecution.DataManager.DataManager, BudgetExecution.DataManager.FundFilter_ItemSelected.
DataTable BudgetExecution.DataManager.Table
Referenced by BudgetExecution.DataManager.DataManager.
decimal BudgetExecution.DataManager.Total
System.ComponentModel.IContainer BudgetExecution.DataManager.components
Required designer variable.
Referenced by BudgetExecution.DataManager.Dispose.
System.Windows.Forms.BindingSource BudgetExecution.DataManager.BindingSource
Referenced by BudgetExecution.DataManager.DataManager, BudgetExecution.DataManager.InitializeComponent.
Syncfusion.Windows.Forms.Tools.TabControlAdv BudgetExecution.DataManager.MiniTabControl1
Referenced by BudgetExecution.DataManager.InitializeComponent.
Syncfusion.Windows.Forms.Tools.TabPageAdv BudgetExecution.DataManager.tabPageAdv2
System.Windows.Forms.GroupBox BudgetExecution.DataManager.groupBox1
MetroFramework.Controls.MetroLink BudgetExecution.DataManager.ReturnButton
System.Windows.Forms.BindingNavigator BudgetExecution.DataManager.Navigator
Referenced by BudgetExecution.DataManager.DataManager, BudgetExecution.DataManager.InitializeComponent.
System.Windows.Forms.ToolStripButton BudgetExecution.DataManager.toolStripButton1
System.Windows.Forms.ToolStripLabel BudgetExecution.DataManager.toolStripLabel1
System.Windows.Forms.ToolStripButton BudgetExecution.DataManager.toolStripButton3
System.Windows.Forms.ToolStripSeparator BudgetExecution.DataManager.toolStripSeparator4
System.Windows.Forms.ToolStripButton BudgetExecution.DataManager.toolStripButton4
System.Windows.Forms.ToolStripSeparator BudgetExecution.DataManager.toolStripSeparator5
System.Windows.Forms.ToolStripTextBox BudgetExecution.DataManager.toolStripTextBox1
System.Windows.Forms.ToolStripSeparator BudgetExecution.DataManager.toolStripSeparator6
System.Windows.Forms.ToolStripButton BudgetExecution.DataManager.toolStripButton5
System.Windows.Forms.ToolStripSeparator BudgetExecution.DataManager.toolStripSeparator7
System.Windows.Forms.ToolStripButton BudgetExecution.DataManager.toolStripButton6
System.Windows.Forms.ToolStripSeparator BudgetExecution.DataManager.toolStripSeparator8
System.Windows.Forms.ToolStripSeparator BudgetExecution.DataManager.toolStripSeparator9
MetroSet_UI.Controls.MetroSetLabel BudgetExecution.DataManager.metroSetLabel9
MetroSet_UI.Controls.MetroSetLabel BudgetExecution.DataManager.metroSetLabel8
System.Windows.Forms.ToolStripSeparator BudgetExecution.DataManager.toolStripSeparator1
Syncfusion.Windows.Forms.Tools.TabPageAdv BudgetExecution.DataManager.tabPageAdv3
Syncfusion.Windows.Forms.Tools.CalculatorControl BudgetExecution.DataManager.calculatorControl1
System.Windows.Forms.ToolStripButton BudgetExecution.DataManager.toolStripButton8
System.Windows.Forms.ToolStripSeparator BudgetExecution.DataManager.toolStripSeparator2
MetroSet_UI.Controls.MetroSetTextBox BudgetExecution.DataManager.bfy
MetroSet_UI.Controls.MetroSetTextBox BudgetExecution.DataManager.org
MetroSet_UI.Controls.MetroSetLabel BudgetExecution.DataManager.metroSetLabel15
MetroSet_UI.Controls.MetroSetLabel BudgetExecution.DataManager.metroSetLabel10
MetroSet_UI.Controls.MetroSetButton BudgetExecution.DataManager.metroSetButton2
MetroSet_UI.Controls.MetroSetButton BudgetExecution.DataManager.metroSetButton1
Syncfusion.Windows.Forms.Tools.TabPageAdv BudgetExecution.DataManager.tabPageAdv1
System.Windows.Forms.GroupBox BudgetExecution.DataManager.FilterGroupBox
System.Windows.Forms.GroupBox BudgetExecution.DataManager.groupBox5
MetroSet_UI.Controls.MetroSetLabel BudgetExecution.DataManager.metroSetLabel2
MetroSet_UI.Controls.MetroSetLabel BudgetExecution.DataManager.metroSetLabel1
MetroSet_UI.Controls.MetroSetLabel BudgetExecution.DataManager.metroSetLabel11
MetroSet_UI.Controls.MetroSetLabel BudgetExecution.DataManager.metroSetLabel7
MetroSet_UI.Controls.MetroSetTextBox BudgetExecution.DataManager.amount2
MetroSet_UI.Controls.MetroSetTextBox BudgetExecution.DataManager.code
MetroSet_UI.Controls.MetroSetTextBox BudgetExecution.DataManager.boc
Referenced by BudgetExecution.DataManager.BocFilter_ItemSelected, BudgetExecution.DataManager.FundFilter_ItemSelected.
MetroSet_UI.Controls.MetroSetLabel BudgetExecution.DataManager.metroSetLabel6
MetroSet_UI.Controls.MetroSetLabel BudgetExecution.DataManager.metroSetLabel4
MetroSet_UI.Controls.MetroSetLabel BudgetExecution.DataManager.metroSetLabel3
MetroSet_UI.Controls.MetroSetTextBox BudgetExecution.DataManager.rc
MetroSet_UI.Controls.MetroSetTextBox BudgetExecution.DataManager.fund
Referenced by BudgetExecution.DataManager.FundFilter_ItemSelected.
MetroSet_UI.Controls.MetroSetComboBox BudgetExecution.DataManager.CodeFilter
MetroSet_UI.Controls.MetroSetComboBox BudgetExecution.DataManager.BocFilter
MetroSet_UI.Controls.MetroSetComboBox BudgetExecution.DataManager.FundFilter
System.Windows.Forms.DataGridView BudgetExecution.DataManager.Grid
Referenced by BudgetExecution.DataManager.DataManager, BudgetExecution.DataManager.GetGridSelectedRowValues, BudgetExecution.DataManager.InitializeComponent, BudgetExecution.DataManager.UpdateGridSelectedRowValues.
MetroSet_UI.Controls.MetroSetTextBox BudgetExecution.DataManager.amount1
MetroSet_UI.Controls.MetroSetLabel BudgetExecution.DataManager.metroSetLabel5
Syncfusion.Windows.Forms.Chart.ChartControl BudgetExecution.DataManager.PrcChart
Referenced by BudgetExecution.DataManager.DataManager.
BudgetExecution.DataManager.DataManager(Source source)
References BudgetExecution.DataManager.BindingSource, BudgetExecution.DataManager.Data, BudgetExecution.DataManager.GetGridSelectedRowValues, BudgetExecution.DataManager.Grid, BudgetExecution.DataManager.InitializeComponent, BudgetExecution.DataManager.Metric, BudgetExecution.DataManager.Navigator, BudgetExecution.DataManager.Ninja, BudgetExecution.DataManager.PrcChart, BudgetExecution.DataManager.ProgramElements, BudgetExecution.DataManager.Table.
string [] BudgetExecution.DataManager.GetCodes(DataTable table, string column)
References BudgetExecution.Select.
Tuple<DataTable, PRC[], decimal, int> BudgetExecution.DataManager.GetData(DataTable table, string column, string filter)
References BudgetExecution.DataManager.GetTable, BudgetExecution.DataManager.GetTotal, BudgetExecution.PRC, BudgetExecution.Select.
Referenced by BudgetExecution.DataManager.GetData.
Dictionary<string, decimal> BudgetExecution.DataManager.GetData(DataTable table, string[] filters, string column)
References BudgetExecution.DataManager.GetData.
Dictionary<string, decimal[]> BudgetExecution.DataManager.GetMetrics(DataTable table, string[] list, string column)
References BudgetExecution.DataManager.GetTotal.
DataTable BudgetExecution.DataManager.GetTable(DataTable table, string column, string filter)
Referenced by BudgetExecution.DataManager.GetData.
decimal BudgetExecution.DataManager.GetTotal(DataTable table)
References BudgetExecution.M, BudgetExecution.Select.
Referenced by BudgetExecution.DataManager.GetData, BudgetExecution.DataManager.GetMetrics.
void BudgetExecution.DataManager.BocFilter_ItemSelected(object sender, EventArgs e)
References BudgetExecution.DataManager.boc.
Referenced by BudgetExecution.DataManager.FundFilter_ItemSelected.
void BudgetExecution.DataManager.Form_Load(object sender, EventArgs e)
References BudgetExecution.DataManager.UpdateDataChart.
void BudgetExecution.DataManager.FundFilter_ItemSelected(object sender, EventArgs e)
References BudgetExecution.DataManager.boc, BudgetExecution.DataManager.BocFilter_ItemSelected, BudgetExecution.DataManager.fund, BudgetExecution.DataManager.ProgramElements.
void BudgetExecution.DataManager.GetCalculatorValue(DataGridView gridrow)
void BudgetExecution.DataManager.GetFundFilterItems()
void BudgetExecution.DataManager.GetGridColumns(DataGridView dgv)
void BudgetExecution.DataManager.GetGridSelectedRowValues()
References BudgetExecution.DataManager.Grid.
Referenced by BudgetExecution.DataManager.DataManager.
void BudgetExecution.DataManager.GridRow_DoubleClick(object sender, EventArgs e)
void BudgetExecution.DataManager.UpdateDataChart(object sender, EventArgs e)
Referenced by BudgetExecution.DataManager.Form_Load.
void BudgetExecution.DataManager.UpdateGridSelectedRowValues(object sender, EventArgs e)
References BudgetExecution.DataManager.Grid.
void BudgetExecution.DataManager.InitializeComponent()
Required method for Designer support - do not modify the contents of this method with the code editor.
References BudgetExecution.DataManager.BindingSource, BudgetExecution.D, BudgetExecution.F, BudgetExecution.DataManager.Grid, BudgetExecution.DataManager.MiniTabControl1, BudgetExecution.DataManager.Navigator.
Referenced by BudgetExecution.DataManager.DataManager.
override void BudgetExecution.DataManager.Dispose(bool disposing)
Clean up any resources being used.
disposing true if managed resources should be disposed; otherwise, false.
References BudgetExecution.DataManager.components.