BudgetExecution::PrcMetric
DataBuilder BudgetExecution.PrcMetric.Data
Referenced by BudgetExecution.PrcMetric.GetMetrics, BudgetExecution.PrcMetric.PrcMetric.
decimal BudgetExecution.PrcMetric.Average
Referenced by BudgetExecution.PrcMetric.GetBaseAverage, BudgetExecution.PrcMetric.PrcMetric.
int BudgetExecution.PrcMetric.Count
Referenced by BudgetExecution.PrcMetric.GetBaseAverage, BudgetExecution.PrcMetric.PrcMetric.
double [] BudgetExecution.PrcMetric.Metrics
Referenced by BudgetExecution.PrcMetric.PrcMetric.
DataSet BudgetExecution.PrcMetric.DataSet
Referenced by BudgetExecution.PrcMetric.PrcMetric.
DataTable BudgetExecution.PrcMetric.Table
Referenced by BudgetExecution.PrcMetric.PrcMetric.
decimal BudgetExecution.PrcMetric.Total
Referenced by BudgetExecution.PrcMetric.PrcMetric.
Dictionary<string, double[]> BudgetExecution.PrcMetric.BocMetrics
Referenced by BudgetExecution.PrcMetric.PrcMetric.
Dictionary<string, decimal> BudgetExecution.PrcMetric.BocTotals
Referenced by BudgetExecution.PrcMetric.PrcMetric.
Dictionary<string, double[]> BudgetExecution.PrcMetric.DivisionMetrics
Referenced by BudgetExecution.PrcMetric.PrcMetric.
Dictionary<string, decimal> BudgetExecution.PrcMetric.DivisionTotals
Referenced by BudgetExecution.PrcMetric.PrcMetric.
Dictionary<string, double[]> BudgetExecution.PrcMetric.FundMetrics
Referenced by BudgetExecution.PrcMetric.PrcMetric.
Dictionary<string, decimal> BudgetExecution.PrcMetric.FundTotals
Referenced by BudgetExecution.PrcMetric.PrcMetric.
Dictionary<string, double[]> BudgetExecution.PrcMetric.GoalMetrics
Referenced by BudgetExecution.PrcMetric.PrcMetric.
Dictionary<string, decimal> BudgetExecution.PrcMetric.GoalTotals
Referenced by BudgetExecution.PrcMetric.PrcMetric.
Dictionary<string, double[]> BudgetExecution.PrcMetric.NpmMetrics
Referenced by BudgetExecution.PrcMetric.PrcMetric.
Dictionary<string, decimal> BudgetExecution.PrcMetric.NpmTotals
Referenced by BudgetExecution.PrcMetric.PrcMetric.
Dictionary<string, double[]> BudgetExecution.PrcMetric.ObjectiveMetrics
Referenced by BudgetExecution.PrcMetric.PrcMetric.
Dictionary<string, decimal> BudgetExecution.PrcMetric.ObjectiveTotals
Referenced by BudgetExecution.PrcMetric.PrcMetric.
Dictionary<string, double[]> BudgetExecution.PrcMetric.ProgramAreaMetrics
Referenced by BudgetExecution.PrcMetric.PrcMetric.
Dictionary<string, decimal> BudgetExecution.PrcMetric.ProgramAreaTotals
Referenced by BudgetExecution.PrcMetric.PrcMetric.
Dictionary<string, string[]> BudgetExecution.PrcMetric.ProgramElements
Referenced by BudgetExecution.PrcMetric.PrcMetric.
Dictionary<string, double[]> BudgetExecution.PrcMetric.ProgramProjectMetrics
Referenced by BudgetExecution.PrcMetric.PrcMetric.
Dictionary<string, decimal> BudgetExecution.PrcMetric.ProgramProjectTotals
Referenced by BudgetExecution.PrcMetric.PrcMetric.
BudgetExecution.PrcMetric.PrcMetric()
BudgetExecution.PrcMetric.PrcMetric(DataBuilder data)
References BudgetExecution.PrcMetric.Average, BudgetExecution.PrcMetric.BocMetrics, BudgetExecution.PrcMetric.BocTotals, BudgetExecution.PrcMetric.Count, BudgetExecution.PrcMetric.Data, BudgetExecution.PrcMetric.DataSet, BudgetExecution.PrcMetric.DivisionMetrics, BudgetExecution.PrcMetric.DivisionTotals, BudgetExecution.PrcMetric.FundMetrics, BudgetExecution.PrcMetric.FundTotals, BudgetExecution.PrcMetric.GetBaseAverage, BudgetExecution.PrcMetric.GetDataTotals, BudgetExecution.PrcMetric.GetMetrics, BudgetExecution.PrcMetric.GetTotals, BudgetExecution.PrcMetric.GoalMetrics, BudgetExecution.PrcMetric.GoalTotals, BudgetExecution.PrcMetric.Metrics, BudgetExecution.PrcMetric.NpmMetrics, BudgetExecution.PrcMetric.NpmTotals, BudgetExecution.PrcMetric.ObjectiveMetrics, BudgetExecution.PrcMetric.ObjectiveTotals, BudgetExecution.DataBuilder.Parameter, BudgetExecution.PrcMetric.ProgramAreaMetrics, BudgetExecution.PrcMetric.ProgramAreaTotals, BudgetExecution.PrcMetric.ProgramElements, BudgetExecution.PrcMetric.ProgramProjectMetrics, BudgetExecution.PrcMetric.ProgramProjectTotals, BudgetExecution.DataBuilder.Source, BudgetExecution.PrcMetric.Table, BudgetExecution.PrcMetric.Total.
BudgetExecution.PrcMetric.PrcMetric(DataBuilder data, PrcField prcfilter, string filter)
References BudgetExecution.PrcMetric.Average, BudgetExecution.PrcMetric.BocMetrics, BudgetExecution.PrcMetric.BocTotals, BudgetExecution.PrcMetric.Count, BudgetExecution.PrcMetric.Data, BudgetExecution.PrcMetric.DataSet, BudgetExecution.PrcMetric.DivisionMetrics, BudgetExecution.PrcMetric.DivisionTotals, BudgetExecution.PrcMetric.FilterTable, BudgetExecution.PrcMetric.FundMetrics, BudgetExecution.PrcMetric.FundTotals, BudgetExecution.PrcMetric.GetBaseAverage, BudgetExecution.PrcMetric.GetDataTotals, BudgetExecution.PrcMetric.GetMetrics, BudgetExecution.PrcMetric.GetProgramElements, BudgetExecution.PrcMetric.GetTotals, BudgetExecution.PrcMetric.GoalMetrics, BudgetExecution.PrcMetric.GoalTotals, BudgetExecution.PrcMetric.Metrics, BudgetExecution.PrcMetric.NpmMetrics, BudgetExecution.PrcMetric.NpmTotals, BudgetExecution.PrcMetric.ObjectiveMetrics, BudgetExecution.PrcMetric.ObjectiveTotals, BudgetExecution.PrcMetric.ProgramAreaMetrics, BudgetExecution.PrcMetric.ProgramAreaTotals, BudgetExecution.PrcMetric.ProgramElements, BudgetExecution.PrcMetric.ProgramProjectMetrics, BudgetExecution.PrcMetric.ProgramProjectTotals, BudgetExecution.DataBuilder.QueryTable, BudgetExecution.DataBuilder.Source, BudgetExecution.PrcMetric.Table, BudgetExecution.PrcMetric.Total.
BudgetExecution.PrcMetric.PrcMetric(DataTable table, PrcField prcfilter, string filter)
References BudgetExecution.PrcMetric.Average, BudgetExecution.PrcMetric.BocMetrics, BudgetExecution.PrcMetric.BocTotals, BudgetExecution.PrcMetric.Count, BudgetExecution.PrcMetric.FilterTable, BudgetExecution.PrcMetric.FundMetrics, BudgetExecution.PrcMetric.FundTotals, BudgetExecution.PrcMetric.GetBaseAverage, BudgetExecution.PrcMetric.GetDataTotals, BudgetExecution.PrcMetric.GetMetrics, BudgetExecution.PrcMetric.GetProgramElements, BudgetExecution.PrcMetric.GetTotals, BudgetExecution.PrcMetric.GoalMetrics, BudgetExecution.PrcMetric.GoalTotals, BudgetExecution.PrcMetric.Metrics, BudgetExecution.PrcMetric.NpmMetrics, BudgetExecution.PrcMetric.NpmTotals, BudgetExecution.PrcMetric.ObjectiveMetrics, BudgetExecution.PrcMetric.ObjectiveTotals, BudgetExecution.PrcMetric.ProgramAreaMetrics, BudgetExecution.PrcMetric.ProgramAreaTotals, BudgetExecution.PrcMetric.ProgramElements, BudgetExecution.PrcMetric.ProgramProjectMetrics, BudgetExecution.PrcMetric.ProgramProjectTotals, BudgetExecution.PrcMetric.Table, BudgetExecution.PrcMetric.Total.
DataTable BudgetExecution.PrcMetric.FilterTable(DataTable table, PrcField prcfilter, string filter)
References BudgetExecution.Select.
Referenced by BudgetExecution.PrcMetric.PrcMetric.
decimal BudgetExecution.PrcMetric.GetBaseAverage(DataTable table)
References BudgetExecution.PrcMetric.Average, BudgetExecution.PrcMetric.Count, BudgetExecution.M, BudgetExecution.Select.
Referenced by BudgetExecution.PrcMetric.GetMetrics, BudgetExecution.PrcMetric.PrcMetric.
decimal BudgetExecution.PrcMetric.GetTotals(DataTable table)
References BudgetExecution.M.
Referenced by BudgetExecution.PrcMetric.GetChartMetrics, BudgetExecution.PrcMetric.GetChartTotals, BudgetExecution.PrcMetric.GetDataTotals, BudgetExecution.PrcMetric.GetMetrics, BudgetExecution.PrcMetric.PrcMetric.
string [] BudgetExecution.PrcMetric.GetCodes(DataTable table, string column)
References BudgetExecution.Select.
Referenced by BudgetExecution.PrcMetric.GetChartMetrics, BudgetExecution.PrcMetric.GetChartTotals, BudgetExecution.PrcMetric.GetDataTotals, BudgetExecution.PrcMetric.GetMetrics, BudgetExecution.PrcMetric.GetProgramElements.
double [] BudgetExecution.PrcMetric.GetMetrics(DataTable table)
References BudgetExecution.PrcMetric.Data, BudgetExecution.PrcMetric.GetBaseAverage, BudgetExecution.PrcMetric.GetCount, BudgetExecution.PrcMetric.GetTotals, BudgetExecution.DataBuilder.QueryTotal.
Referenced by BudgetExecution.PrcMetric.GetChartMetrics, BudgetExecution.PrcMetric.PrcMetric.
PRC [] BudgetExecution.PrcMetric.GetPrcArray(DataTable table)
References BudgetExecution.PRC, BudgetExecution.Select.
Dictionary<string, string[]> BudgetExecution.PrcMetric.GetProgramElements(DataTable table)
References BudgetExecution.PrcMetric.GetCodes.
Referenced by BudgetExecution.PrcMetric.PrcMetric.
int BudgetExecution.PrcMetric.GetCount(DataTable table)
References BudgetExecution.Select.
Referenced by BudgetExecution.PrcMetric.GetMetrics.
Dictionary<string, decimal> BudgetExecution.PrcMetric.GetDataTotals(DataTable table, PrcField prcfilter)
References BudgetExecution.PrcMetric.GetCodes, BudgetExecution.PrcMetric.GetTotals, BudgetExecution.Select.
Referenced by BudgetExecution.PrcMetric.PrcMetric.
Dictionary<string, double[]> BudgetExecution.PrcMetric.GetChartMetrics(DataTable table, PrcField prcfilter)
References BudgetExecution.PrcMetric.GetCodes, BudgetExecution.PrcMetric.GetMetrics, BudgetExecution.PrcMetric.GetTotals, BudgetExecution.Select.
Dictionary<string, double> BudgetExecution.PrcMetric.GetChartTotals(DataTable table, PrcField prcfilter)
References BudgetExecution.PrcMetric.GetCodes, BudgetExecution.PrcMetric.GetTotals, BudgetExecution.Select.
Referenced by BudgetExecution.MainForm.MainForm.
Dictionary<string, double[]> BudgetExecution.PrcMetric.GetMetrics(DataTable table, PrcField prcfilter)
References BudgetExecution.PrcMetric.GetCodes, BudgetExecution.PrcMetric.GetTotals, BudgetExecution.Select.