BudgetExecution::Selector
string BudgetExecution.Selector.DivisionImages
string BudgetExecution.Selector.SummaryImages
FormData BudgetExecution.Selector.NinjaData
Referenced by BudgetExecution.Selector.Selector.
string [] BudgetExecution.Selector.Images
System.ComponentModel.IContainer BudgetExecution.Selector.components
Required designer variable.
Referenced by BudgetExecution.Selector.Dispose.
Syncfusion.Windows.Forms.Tools.Carousel BudgetExecution.Selector.ViewerCarousel
System.Windows.Forms.Panel BudgetExecution.Selector.panel1
BudgetExecution.Selector.Selector()
BudgetExecution.Selector.Selector(string path)
References BudgetExecution.Selector.GetViewerCarouselImageList, BudgetExecution.Selector.InitializeComponent, BudgetExecution.Selector.NinjaData, BudgetExecution.Selector.ViewerCarousel_OnImageSelected.
void BudgetExecution.Selector.GetViewerCarouselImageList(string path)
Referenced by BudgetExecution.Selector.Selector.
void BudgetExecution.Selector.Selector_Load(object sender, EventArgs e)
void BudgetExecution.Selector.ViewerCarousel_OnImageSelected(object sender, EventArgs e)
Referenced by BudgetExecution.Selector.Selector.
void BudgetExecution.Selector.InitializeComponent()
Required method for Designer support - do not modify the contents of this method with the code editor.
References BudgetExecution.F.
Referenced by BudgetExecution.Selector.Selector.
override void BudgetExecution.Selector.Dispose(bool disposing)
Clean up any resources being used.
disposing true if managed resources should be disposed; otherwise, false.
References BudgetExecution.Selector.components.