CREATE TABLE "Sites" (
    "ID" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE, 
    "Fund" TEXT, 
    "FundName" TEXT, 
    "BOC" TEXT, 
    "DCN" TEXT, 
    "DocType" TEXT, 
    "FOC" TEXT, 
    "FocName" TEXT, 
    "NPM" TEXT,
    "RC" TEXT, 
    "DivisionName" TEXT,
    "AgreementNumber" TEXT,
    "Code" TEXT,
    "ProgramProjectCode" TEXT,
    "ActivityCode" TEXT,
    "System" TEXT,
    "PurchaseRequest" TEXT,
    "SiteID" TEXT,
    "City" TEXT, 
    "District" TEXT, 
    "SiteName" TEXT, 
    "SiteProjectName" TEXT, 
    "SiteProjectCode" TEXT, 
    "State" TEXT, 
    "Commitments" NUMERIC DEFAULT 0, 
    "Obligations" NUMERIC DEFAULT 0 );