BudgetExecution::ControlNumber
string BudgetExecution.ControlNumber.Region
Referenced by BudgetExecution.ControlNumber.ControlNumber.
int BudgetExecution.ControlNumber.ID
Referenced by BudgetExecution.ControlNumber.ControlNumber, BudgetExecution.ControlNumber.Delete, BudgetExecution.ControlNumber.Update.
DataRow BudgetExecution.ControlNumber.DbRow
Referenced by BudgetExecution.ControlNumber.ControlNumber.
DataBuilder BudgetExecution.ControlNumber.DbData
Referenced by BudgetExecution.ControlNumber.ControlNumber.
string BudgetExecution.ControlNumber.FiscalYear
Referenced by BudgetExecution.ControlNumber.ControlNumber.
int BudgetExecution.ControlNumber.RegionControlNumber
Referenced by BudgetExecution.ControlNumber.ControlNumber.
string BudgetExecution.ControlNumber.Fund
Referenced by BudgetExecution.ControlNumber.Select.
int BudgetExecution.ControlNumber.FundControlNumber
Referenced by BudgetExecution.ControlNumber.ControlNumber.
string BudgetExecution.ControlNumber.DivisionID
Referenced by BudgetExecution.ControlNumber.ControlNumber.
string BudgetExecution.ControlNumber.DivisionControlNumber
int BudgetExecution.ControlNumber.BudgetControlNumber
Referenced by BudgetExecution.ControlNumber.ControlNumber.
Dictionary<string, object> BudgetExecution.ControlNumber.Parameter
Source BudgetExecution.ControlNumber.Source
Provider BudgetExecution.ControlNumber.Provider
DataTable BudgetExecution.ControlNumber.Table
Referenced by BudgetExecution.ControlNumber.ControlNumber.
BudgetExecution.ControlNumber.ControlNumber()
Referenced by BudgetExecution.ControlNumber.GetInsertionColumns.
BudgetExecution.ControlNumber.ControlNumber(Source source, Provider provider)
Initializes a new instance of the ControlNumber class.
source The source. provider The provider.
References BudgetExecution.ControlNumber.BudgetControlNumber, BudgetExecution.ControlNumber.DbData, BudgetExecution.ControlNumber.DbRow, BudgetExecution.ControlNumber.FiscalYear, BudgetExecution.ControlNumber.FundControlNumber, BudgetExecution.ControlNumber.GetRegionCount, BudgetExecution.ControlNumber.ID, BudgetExecution.ControlNumber.Region, BudgetExecution.ControlNumber.RegionControlNumber, BudgetExecution.ControlNumber.Select, BudgetExecution.ControlNumber.Table.
BudgetExecution.ControlNumber.ControlNumber(string fund, string division)
Initializes a new instance of the ControlNumber class.
fund The fund. division The division.
References BudgetExecution.ControlNumber.BudgetControlNumber, BudgetExecution.ControlNumber.DbData, BudgetExecution.ControlNumber.DbRow, BudgetExecution.ControlNumber.DivisionID, BudgetExecution.ControlNumber.FiscalYear, BudgetExecution.ControlNumber.FundControlNumber, BudgetExecution.ControlNumber.GetDivisionCount, BudgetExecution.ControlNumber.GetFundCount, BudgetExecution.ControlNumber.GetParamData, BudgetExecution.ControlNumber.GetRegionCount, BudgetExecution.ControlNumber.ID, BudgetExecution.ControlNumber.Region, BudgetExecution.ControlNumber.RegionControlNumber, BudgetExecution.ControlNumber.Table.
Dictionary<string, object> BudgetExecution.ControlNumber.GetParamData(string fund, string divisionid)
Gets the parameter data.
fund The fund. divisionid The divisionid.
Referenced by BudgetExecution.ControlNumber.ControlNumber.
override string BudgetExecution.ControlNumber.ToString()
Returns a System.String that represents this instance.
A System.String that represents this instance.
Referenced by BudgetExecution.ControlNumber.GetInsertionColumns.
static Dictionary<string, object> BudgetExecution.ControlNumber.GetInsertionColumns(Dictionary< string, object > param)
Gets the insertion columns.
param The parameter.
References BudgetExecution.ControlNumber.ControlNumber, BudgetExecution.ControlNumber.ToString.
Referenced by BudgetExecution.ControlNumber.Insert.
static Fund BudgetExecution.ControlNumber.Select(Source source, Dictionary< string, object > p)
Selects the specified source.
source The source. p The p. returns a Fund object
References BudgetExecution.ControlNumber.Fund.
Referenced by BudgetExecution.ControlNumber.ControlNumber, BudgetExecution.ControlNumber.Select.
static Fund BudgetExecution.ControlNumber.Select(Source source, Provider provider, Dictionary< string, object > p)
Selects the specified source.
source The source. provider The provider. p The p. returns a Fund object
References BudgetExecution.ControlNumber.Fund, BudgetExecution.ControlNumber.Select.
static void BudgetExecution.ControlNumber.Insert(Dictionary< string, object > p)
Inserts the specified p.
p The p.
References BudgetExecution.ControlNumber.GetInsertionColumns.
static void BudgetExecution.ControlNumber.Insert(Source source, Provider provider, Dictionary< string, object > p)
Inserts the specified source.
source The source. provider The provider. p The p.
References BudgetExecution.ControlNumber.GetInsertionColumns.
static void BudgetExecution.ControlNumber.Update(Source source, Dictionary< string, object > p)
Updates the specified source.
source The source. p The p.
References BudgetExecution.Amount, BudgetExecution.ControlNumber.ID.
static void BudgetExecution.ControlNumber.Update(Source source, Provider provider, Dictionary< string, object > p)
Updates the specified source.
source The source. provider The provider. p The p.
References BudgetExecution.Amount, BudgetExecution.ControlNumber.ID.
static void BudgetExecution.ControlNumber.Delete(Source source, Dictionary< string, object > p)
Deletes the specified source.
source The source. p The p.
References BudgetExecution.ControlNumber.ID.
static void BudgetExecution.ControlNumber.Delete(Source source, Provider provider, Dictionary< string, object > p)
Deletes the specified source.
source The source. provider The provider. p The p.
References BudgetExecution.ControlNumber.ID.
string [] BudgetExecution.ControlNumber.GetColumnNames()
Gets the column names.
int BudgetExecution.ControlNumber.GetFundCount(string fund)
Gets the fund count.
fund The fund.
References BudgetExecution.Count.
Referenced by BudgetExecution.ControlNumber.Calculate, BudgetExecution.ControlNumber.ControlNumber.
int BudgetExecution.ControlNumber.GetDivisionCount(string divisionId)
Gets the division count.
divisionid The divisionid.
References BudgetExecution.Count.
Referenced by BudgetExecution.ControlNumber.Calculate, BudgetExecution.ControlNumber.ControlNumber.
int BudgetExecution.ControlNumber.GetRegionCount()
Gets the region count.
return integer representing the number of records
References BudgetExecution.Count.
Referenced by BudgetExecution.ControlNumber.Calculate, BudgetExecution.ControlNumber.ControlNumber.
void BudgetExecution.ControlNumber.Calculate(string fund, string divisionid)
References BudgetExecution.ControlNumber.GetDivisionCount, BudgetExecution.ControlNumber.GetFundCount, BudgetExecution.ControlNumber.GetRegionCount.