BudgetExecution::DataBuilder
Source BudgetExecution.DataBuilder.Source
Referenced by BudgetExecution.AccountManager.AccountManager, BudgetExecution.SummaryForm.Form_Load, BudgetExecution.PrcMetric.PrcMetric, BudgetExecution.SummaryForm.SummaryTabPage_TabSelected.
Query BudgetExecution.DataBuilder.DbQuery
Referenced by BudgetExecution.DataBuilder.DataBuilder.
DataTable BudgetExecution.DataBuilder.DbTable
Referenced by BudgetExecution.DataBuilder.DataBuilder, BudgetExecution.DivisionAuthority.DivisionAuthority, BudgetExecution.DataBuilder.GetCount, BudgetExecution.DataBuilder.GetFteTotal, BudgetExecution.DataBuilder.GetTotal, BudgetExecution.MainForm.MainForm, BudgetExecution.PrcMetric.PrcMetric.
Dictionary<string, string[]> BudgetExecution.DataBuilder.ProgramElements
Referenced by BudgetExecution.DataBuilder.DataBuilder, BudgetExecution.SQLiteData.SQLiteData_Load.
string [] BudgetExecution.DataBuilder.Columns
Referenced by BudgetExecution.DataBuilder.DataBuilder.
DataRow [] BudgetExecution.DataBuilder.DbRow
Referenced by BudgetExecution.DataBuilder.DataBuilder.
BindingSource BudgetExecution.DataBuilder.BindingSource
Referenced by BudgetExecution.DataBuilder.DataBuilder.
decimal BudgetExecution.DataBuilder.Total
Referenced by BudgetExecution.DataBuilder.DataBuilder, BudgetExecution.PrcMetric.GetMetrics, BudgetExecution.SummaryForm.SummaryTabPage_TabSelected.
Dictionary<string, object> BudgetExecution.DataBuilder.DataFields
Referenced by BudgetExecution.DataBuilder.DataBuilder, BudgetExecution.PrcMetric.PrcMetric.
BudgetExecution.DataBuilder.DataBuilder()
BudgetExecution.DataBuilder.DataBuilder(Query q)
References BudgetExecution.DataBuilder.BindingSource, BudgetExecution.DataBuilder.Columns, BudgetExecution.DataBuilder.DataFields, BudgetExecution.DataBuilder.DbQuery, BudgetExecution.DataBuilder.DbRow, BudgetExecution.DataBuilder.DbTable, BudgetExecution.DataBuilder.GetColumnNames, BudgetExecution.DataBuilder.GetDataRecords, BudgetExecution.DataBuilder.GetDataTable, BudgetExecution.DataBuilder.GetFteTotal, BudgetExecution.DataBuilder.GetProgramElements, BudgetExecution.DataBuilder.GetTotal, BudgetExecution.DataBuilder.ProgramElements, BudgetExecution.Query.Provider, BudgetExecution.Select, BudgetExecution.Query.Source, BudgetExecution.DataBuilder.Total.
BudgetExecution.DataBuilder.DataBuilder(Source source, Provider provider)
References BudgetExecution.DataBuilder.BindingSource, BudgetExecution.DataBuilder.Columns, BudgetExecution.DataBuilder.DataFields, BudgetExecution.DataBuilder.DbQuery, BudgetExecution.DataBuilder.DbRow, BudgetExecution.DataBuilder.DbTable, BudgetExecution.DataBuilder.GetColumnNames, BudgetExecution.DataBuilder.GetDataRecords, BudgetExecution.DataBuilder.GetDataTable, BudgetExecution.DataBuilder.GetFteTotal, BudgetExecution.DataBuilder.GetProgramElements, BudgetExecution.DataBuilder.GetTotal, BudgetExecution.DataBuilder.ProgramElements, BudgetExecution.Select, BudgetExecution.DataBuilder.Total.
BudgetExecution.DataBuilder.DataBuilder(Source source, Provider provider, Dictionary< string, object > param)
References BudgetExecution.DataBuilder.BindingSource, BudgetExecution.DataBuilder.Columns, BudgetExecution.DataBuilder.DataFields, BudgetExecution.DataBuilder.DbQuery, BudgetExecution.DataBuilder.DbRow, BudgetExecution.DataBuilder.DbTable, BudgetExecution.DataBuilder.GetColumnNames, BudgetExecution.DataBuilder.GetDataRecords, BudgetExecution.DataBuilder.GetDataTable, BudgetExecution.DataBuilder.GetFteTotal, BudgetExecution.DataBuilder.GetProgramElements, BudgetExecution.DataBuilder.GetTotal, BudgetExecution.DataBuilder.ProgramElements, BudgetExecution.DataBuilder.Total.
string [] BudgetExecution.DataBuilder.GetCodes(DataTable table, string column)
References BudgetExecution.Select.
Referenced by BudgetExecution.DataBuilder.GetProgramElements.
Dictionary<string, string[]> BudgetExecution.DataBuilder.GetProgramElements(DataTable table)
References BudgetExecution.DataBuilder.GetCodes.
Referenced by BudgetExecution.DataBuilder.DataBuilder.
Dictionary<string, object> BudgetExecution.DataBuilder.GetParamVals(DataTable table)
int BudgetExecution.DataBuilder.GetCount(DataTable table)
References BudgetExecution.DataBuilder.DbTable, BudgetExecution.Select.
DataSet BudgetExecution.DataBuilder.GetDataSet()
DataSet BudgetExecution.DataBuilder.GetDataSet(string dataset, Source source)
DataTable BudgetExecution.DataBuilder.GetDataTable()
Referenced by BudgetExecution.DataBuilder.DataBuilder.
DataTable BudgetExecution.DataBuilder.GetDataTable(Source source)
decimal BudgetExecution.DataBuilder.GetTotal(DataTable table)
References BudgetExecution.DataBuilder.DbTable, BudgetExecution.M, BudgetExecution.Select.
Referenced by BudgetExecution.DataBuilder.DataBuilder.
decimal BudgetExecution.DataBuilder.GetFteTotal(DataTable table)
References BudgetExecution.DataBuilder.DbTable, BudgetExecution.M, BudgetExecution.Select.
Referenced by BudgetExecution.DataBuilder.DataBuilder.
DataRow [] BudgetExecution.DataBuilder.GetDataRecords(DataTable table)
References BudgetExecution.Select.
Referenced by BudgetExecution.DataBuilder.DataBuilder.
string [] BudgetExecution.DataBuilder.GetColumnNames(DataTable table)
Referenced by BudgetExecution.DataBuilder.DataBuilder.
SQLiteQuery BudgetExecution.DataBuilder.GetSQLiteQuery(Source source, Provider provider)
SQLiteQuery BudgetExecution.DataBuilder.GetSQLiteQuery(Source source, Provider provider, SQLiteParameter[] pmr)
SQLiteQuery BudgetExecution.DataBuilder.GetSQLiteQuery(Source source, Provider provider, Dictionary< string, object > dpr)
ExcelQuery BudgetExecution.DataBuilder.GetExcelQuery(Source source, Provider provider, OleDbParameter[] pmr)
ExcelQuery BudgetExecution.DataBuilder.GetExcelQuery(Source source, Provider provider, Dictionary< string, object > dpr)
static DataTable BudgetExecution.DataBuilder.FilterTable(DataTable table, Field prcfilter, string filter)
References BudgetExecution.Select.
Referenced by BudgetExecution.DivisionAuthority.DivisionAuthority.