BudgetExecution::BudgetChart
string [] BudgetExecution.BudgetChart.AxisTitle
ChartControl BudgetExecution.BudgetChart.Chart
Referenced by BudgetExecution.BudgetChart.Activate, BudgetExecution.BudgetChart.BudgetChart, BudgetExecution.BudgetChart.Configure3DMode, BudgetExecution.BudgetChart.ConfigureMainTitle, BudgetExecution.BudgetChart.ConfigurePrimaryAxisLabels, BudgetExecution.BudgetChart.GetLegend.
DataBuilder BudgetExecution.BudgetChart.DbData
Referenced by BudgetExecution.BudgetChart.BudgetChart.
PrcMetric BudgetExecution.BudgetChart.Metric
Referenced by BudgetExecution.BudgetChart.BudgetChart.
BindingSource BudgetExecution.BudgetChart.BindingSource
Dictionary<string, double[]> BudgetExecution.BudgetChart.DataMetrics
Referenced by BudgetExecution.BudgetChart.BudgetChart.
ChartSeries BudgetExecution.BudgetChart.DataSeries
Referenced by BudgetExecution.BudgetChart.BudgetChart, BudgetExecution.BudgetChart.ConfigureLargeNumberSeries, BudgetExecution.BudgetChart.ConfigurePieChart, BudgetExecution.BudgetChart.ConfigureSeries, BudgetExecution.BudgetChart.ConfigureToolTip, BudgetExecution.BudgetChart.GetSeriesTotals.
Dictionary<string, double> BudgetExecution.BudgetChart.DataTotals
Referenced by BudgetExecution.BudgetChart.BudgetChart.
int [] BudgetExecution.BudgetChart.Dimension
Source BudgetExecution.BudgetChart.Source
Field BudgetExecution.BudgetChart.Filter
ChartSeriesType BudgetExecution.BudgetChart.SeriesType
Referenced by BudgetExecution.BudgetChart.BudgetChart, BudgetExecution.BudgetChart.Configure3DMode, BudgetExecution.BudgetChart.ConfigureLargeNumberSeries, BudgetExecution.BudgetChart.ConfigureSeries, BudgetExecution.BudgetChart.GetSeriesTotals.
Stat BudgetExecution.BudgetChart.Value
Referenced by BudgetExecution.BudgetChart.BudgetChart.
Dictionary<string, double[]> BudgetExecution.BudgetChart.InputMetrics
Dictionary<string, double> BudgetExecution.BudgetChart.InputTotals
ChartLegend BudgetExecution.BudgetChart.Legend
string [] BudgetExecution.BudgetChart.MainTitle
ChartDataBindModel BudgetExecution.BudgetChart.Model
DataTable BudgetExecution.BudgetChart.Table
Referenced by BudgetExecution.BudgetChart.BudgetChart.
double BudgetExecution.BudgetChart.Total
BudgetExecution.BudgetChart.BudgetChart()
BudgetExecution.BudgetChart.BudgetChart(ChartControl chart, string title, Dictionary< string, double > data)
References BudgetExecution.BudgetChart.Chart, BudgetExecution.BudgetChart.Configure3DMode, BudgetExecution.BudgetChart.ConfigureLargeNumberSeries, BudgetExecution.BudgetChart.ConfigurePrimaryAxisLabels, BudgetExecution.BudgetChart.ConfigurePrimaryAxisTitle, BudgetExecution.BudgetChart.ConfigureToolTip, BudgetExecution.BudgetChart.DataSeries, BudgetExecution.BudgetChart.GetSeriesTotals, BudgetExecution.BudgetChart.SeriesType, BudgetExecution.BudgetChart.Value.
BudgetExecution.BudgetChart.BudgetChart(ChartControl chart, DataBuilder data, Field filter)
References BudgetExecution.BudgetChart.Chart, BudgetExecution.BudgetChart.Configure3DMode, BudgetExecution.BudgetChart.ConfigureLargeNumberSeries, BudgetExecution.BudgetChart.ConfigurePrimaryAxisLabels, BudgetExecution.BudgetChart.ConfigureToolTip, BudgetExecution.BudgetChart.DataSeries, BudgetExecution.BudgetChart.DataTotals, BudgetExecution.BudgetChart.DbData, BudgetExecution.BudgetChart.GetSeriesTotals, BudgetExecution.BudgetChart.Metric, BudgetExecution.BudgetChart.SeriesType, BudgetExecution.BudgetChart.Table, BudgetExecution.BudgetChart.Value.
BudgetExecution.BudgetChart.BudgetChart(ChartControl chart, DataBuilder data, Field filter, Stat value, ChartSeriesType type)
References BudgetExecution.BudgetChart.Chart, BudgetExecution.BudgetChart.Configure3DMode, BudgetExecution.BudgetChart.ConfigurePrimaryAxisLabels, BudgetExecution.BudgetChart.ConfigureSeries, BudgetExecution.BudgetChart.ConfigureToolTip, BudgetExecution.BudgetChart.DataMetrics, BudgetExecution.BudgetChart.DataSeries, BudgetExecution.BudgetChart.DbData, BudgetExecution.BudgetChart.GetMeasure, BudgetExecution.BudgetChart.GetSeriesTotals, BudgetExecution.BudgetChart.Metric, BudgetExecution.BudgetChart.SeriesType, BudgetExecution.BudgetChart.Table, BudgetExecution.BudgetChart.Value.
BudgetExecution.BudgetChart.BudgetChart(ChartControl chart, string[] title, DataBuilder data, Field filter, Stat value, ChartSeriesType type)
References BudgetExecution.BudgetChart.Chart, BudgetExecution.BudgetChart.Configure3DMode, BudgetExecution.BudgetChart.ConfigureMainTitle, BudgetExecution.BudgetChart.ConfigurePrimaryAxisLabels, BudgetExecution.BudgetChart.ConfigureSeries, BudgetExecution.BudgetChart.ConfigureToolTip, BudgetExecution.BudgetChart.DataMetrics, BudgetExecution.BudgetChart.DataSeries, BudgetExecution.BudgetChart.DbData, BudgetExecution.BudgetChart.GetMeasure, BudgetExecution.BudgetChart.GetSeriesTotals, BudgetExecution.BudgetChart.Metric, BudgetExecution.BudgetChart.SeriesType, BudgetExecution.BudgetChart.Table, BudgetExecution.BudgetChart.Value.
BudgetExecution.BudgetChart.BudgetChart(ChartControl chart, string[] title, DataTable table, Field filter, Stat value, ChartSeriesType type)
References BudgetExecution.BudgetChart.Chart, BudgetExecution.BudgetChart.Configure3DMode, BudgetExecution.BudgetChart.ConfigureMainTitle, BudgetExecution.BudgetChart.ConfigurePrimaryAxisLabels, BudgetExecution.BudgetChart.ConfigureSeries, BudgetExecution.BudgetChart.ConfigureToolTip, BudgetExecution.BudgetChart.DataMetrics, BudgetExecution.BudgetChart.DataSeries, BudgetExecution.BudgetChart.GetMeasure, BudgetExecution.BudgetChart.GetSeriesTotals, BudgetExecution.BudgetChart.SeriesType, BudgetExecution.BudgetChart.Table, BudgetExecution.BudgetChart.Value.
BudgetExecution.BudgetChart.BudgetChart(ChartControl chart, string[] title, Dictionary< string, double > data, Field filter, Stat value, ChartSeriesType type)
References BudgetExecution.BudgetChart.Chart, BudgetExecution.BudgetChart.Configure3DMode, BudgetExecution.BudgetChart.ConfigureMainTitle, BudgetExecution.BudgetChart.ConfigurePrimaryAxisLabels, BudgetExecution.BudgetChart.ConfigureToolTip, BudgetExecution.BudgetChart.DataSeries, BudgetExecution.BudgetChart.SeriesType, BudgetExecution.BudgetChart.Value.
BudgetExecution.BudgetChart.BudgetChart(ChartControl chart, string[] title, Source source, Field filter, Stat value, ChartSeriesType type)
References BudgetExecution.BudgetChart.Chart, BudgetExecution.BudgetChart.Configure3DMode, BudgetExecution.BudgetChart.ConfigureMainTitle, BudgetExecution.BudgetChart.ConfigurePrimaryAxisLabels, BudgetExecution.BudgetChart.ConfigureSeries, BudgetExecution.BudgetChart.ConfigureToolTip, BudgetExecution.BudgetChart.DataMetrics, BudgetExecution.BudgetChart.DataSeries, BudgetExecution.BudgetChart.DbData, BudgetExecution.BudgetChart.GetMeasure, BudgetExecution.BudgetChart.GetSeriesTotals, BudgetExecution.BudgetChart.Metric, BudgetExecution.BudgetChart.SeriesType, BudgetExecution.BudgetChart.Table, BudgetExecution.BudgetChart.Value.
BudgetExecution.BudgetChart.BudgetChart(ChartControl chart, string[] title, Source source, Dictionary< string, object > param, Field filter, Stat value, ChartSeriesType type)
References BudgetExecution.BudgetChart.Chart, BudgetExecution.BudgetChart.Configure3DMode, BudgetExecution.BudgetChart.ConfigureMainTitle, BudgetExecution.BudgetChart.ConfigurePrimaryAxisLabels, BudgetExecution.BudgetChart.ConfigureSeries, BudgetExecution.BudgetChart.ConfigureToolTip, BudgetExecution.BudgetChart.DataMetrics, BudgetExecution.BudgetChart.DataSeries, BudgetExecution.BudgetChart.DbData, BudgetExecution.BudgetChart.GetMeasure, BudgetExecution.BudgetChart.GetSeriesTotals, BudgetExecution.BudgetChart.Metric, BudgetExecution.BudgetChart.SeriesType, BudgetExecution.BudgetChart.Table, BudgetExecution.BudgetChart.Value.
ChartControl BudgetExecution.BudgetChart.Activate()
References BudgetExecution.BudgetChart.Chart.
ChartSeries BudgetExecution.BudgetChart.GetSeriesTotals(Dictionary< string, double > data)
References BudgetExecution.BudgetChart.DataSeries, BudgetExecution.BudgetChart.SeriesType.
Referenced by BudgetExecution.BudgetChart.BudgetChart.
ChartSeries BudgetExecution.BudgetChart.GetSeriesTotals(Dictionary< string, double > data, ChartSeriesType type)
References BudgetExecution.BudgetChart.DataSeries.
void BudgetExecution.BudgetChart.ConfigurePieChart(ChartSeries ds)
References BudgetExecution.BudgetChart.DataSeries.
void BudgetExecution.BudgetChart.ConfigureLargeNumberSeries(ChartSeries series)
References BudgetExecution.BudgetChart.DataSeries, BudgetExecution.BudgetChart.SeriesType.
Referenced by BudgetExecution.BudgetChart.BudgetChart.
void BudgetExecution.BudgetChart.ConfigureSeries(ChartSeries series)
References BudgetExecution.BudgetChart.ConfigureToolTip, BudgetExecution.BudgetChart.DataSeries, BudgetExecution.BudgetChart.SeriesType.
Referenced by BudgetExecution.BudgetChart.BudgetChart.
void BudgetExecution.BudgetChart.ConfigureSeries(ChartSeries series, Stat value)
References BudgetExecution.BudgetChart.DataSeries.
void BudgetExecution.BudgetChart.Configure3DMode(int[] dim)
References BudgetExecution.BudgetChart.SeriesType.
void BudgetExecution.BudgetChart.ConfigurePrimaryAxisTitle(string[] title)
Referenced by BudgetExecution.BudgetChart.BudgetChart.
ChartDataBindModel BudgetExecution.BudgetChart.GetDataBindingSource(Dictionary< string, double > data, Field filter)
ChartLegend BudgetExecution.BudgetChart.GetLegend(ChartControl chart)
References BudgetExecution.BudgetChart.Chart.
void BudgetExecution.BudgetChart.ConfigureMainTitle(string[] t)
References BudgetExecution.BudgetChart.Chart.
Referenced by BudgetExecution.BudgetChart.BudgetChart.
Dictionary<string, double> BudgetExecution.BudgetChart.GetMeasure(Dictionary< string, double[]> data, Stat value)
Referenced by BudgetExecution.BudgetChart.BudgetChart.
void BudgetExecution.BudgetChart.ConfigureToolTip(ChartSeries series)
References BudgetExecution.BudgetChart.DataSeries.
Referenced by BudgetExecution.BudgetChart.BudgetChart, BudgetExecution.BudgetChart.ConfigureSeries.
void BudgetExecution.BudgetChart.ConfigurePrimaryAxisLabels(ChartControl chart)
References BudgetExecution.BudgetChart.Chart, BudgetExecution.F.
Referenced by BudgetExecution.BudgetChart.BudgetChart.
void BudgetExecution.BudgetChart.Configure3DMode(ChartControl chart)
References BudgetExecution.BudgetChart.Chart, BudgetExecution.BudgetChart.SeriesType.
Referenced by BudgetExecution.BudgetChart.BudgetChart.