BudgetExecution::ExcelReport
string BudgetExecution.ExcelReport.path
Referenced by BudgetExecution.ExcelReport.ExportData.
DataBuilder BudgetExecution.ExcelReport.DbData
Referenced by BudgetExecution.ExcelReport.ExcelReport.
DataTable BudgetExecution.ExcelReport.Table
Referenced by BudgetExecution.ExcelReport.ExcelReport.
string BudgetExecution.ExcelReport.FilePath
Referenced by BudgetExecution.ExcelReport.ExcelReport.
string BudgetExecution.ExcelReport.ConnectionString
Referenced by BudgetExecution.ExcelReport.ExcelReport.
DocInfo BudgetExecution.ExcelReport.AccountingInfo
Excel BudgetExecution.ExcelReport.Excel
Referenced by BudgetExecution.ExcelReport.Create.
BudgetExecution.ExcelReport.ExcelReport()
BudgetExecution.ExcelReport.ExcelReport(string filepath)
References BudgetExecution.ExcelReport.ConnectionString, BudgetExecution.ExcelReport.Create, BudgetExecution.ExcelReport.FilePath, BudgetExecution.ExcelReport.GetConnectionString.
BudgetExecution.ExcelReport.ExcelReport(DataTable data)
References BudgetExecution.ExcelReport.Create, BudgetExecution.ExcelReport.Table.
BudgetExecution.ExcelReport.ExcelReport(DataBuilder data)
References BudgetExecution.ExcelReport.Create, BudgetExecution.ExcelReport.DbData, BudgetExecution.ExcelReport.Table.
string BudgetExecution.ExcelReport.GetConnectionString(string filepath)
Referenced by BudgetExecution.ExcelReport.ExcelReport.
string BudgetExecution.ExcelReport.GetExternalFile()
Workbook BudgetExecution.ExcelReport.ExportData(DataTable table)
References BudgetExecution.ExcelReport.Create, BudgetExecution.ExcelReport.path.
Workbook BudgetExecution.ExcelReport.ExportData(string filepath, DataTable table)
References BudgetExecution.ExcelReport.Create.
Workbook BudgetExecution.ExcelReport.OpenFile(string filepath)
Workbook BudgetExecution.ExcelReport.OpenWorkbook()
void BudgetExecution.ExcelReport.SaveWorkbook(Workbook wb, string filepath)
void BudgetExecution.ExcelReport.Close(Workbook wb)
Excel BudgetExecution.ExcelReport.Create()
References BudgetExecution.ExcelReport.Excel.
Referenced by BudgetExecution.ExcelReport.ExcelReport, BudgetExecution.ExcelReport.ExportData.
void BudgetExecution.ExcelReport.ReleaseObject(object obj)