BudgetExecution::Transfer
DataBuilder BudgetExecution.Transfer.DbData
DataRow BudgetExecution.Transfer.DbTable
DataRow BudgetExecution.Transfer.DbRow
Source BudgetExecution.Transfer.Source
Provider BudgetExecution.Transfer.Provider
Account BudgetExecution.Transfer.Account
Referenced by BudgetExecution.Transfer.Transfer.
decimal BudgetExecution.Transfer.Amount
Referenced by BudgetExecution.Transfer.Transfer, BudgetExecution.Transfer.Update.
string BudgetExecution.Transfer.BFY
Referenced by BudgetExecution.Transfer.Transfer.
BOC BudgetExecution.Transfer.BOC
Referenced by BudgetExecution.Transfer.Transfer.
string BudgetExecution.Transfer.BudgetLevel
Referenced by BudgetExecution.Transfer.Transfer.
string BudgetExecution.Transfer.Code
Referenced by BudgetExecution.Transfer.Transfer.
string BudgetExecution.Transfer.Date
Referenced by BudgetExecution.Transfer.Transfer.
string BudgetExecution.Transfer.DocType
Referenced by BudgetExecution.Transfer.Transfer.
string BudgetExecution.Transfer.FromTo
Referenced by BudgetExecution.Transfer.Transfer.
Fund BudgetExecution.Transfer.Fund
Referenced by BudgetExecution.Transfer.GetInsertionColumns, BudgetExecution.Transfer.Transfer.
string BudgetExecution.Transfer.NpmCode
Referenced by BudgetExecution.Transfer.Transfer.
Org BudgetExecution.Transfer.Org
Referenced by BudgetExecution.Transfer.Transfer.
string BudgetExecution.Transfer.Qtr
Referenced by BudgetExecution.Transfer.Transfer.
RC BudgetExecution.Transfer.RC
Referenced by BudgetExecution.Transfer.Transfer.
string BudgetExecution.Transfer.RPIO
Referenced by BudgetExecution.Transfer.Transfer.
string BudgetExecution.Transfer.TCN
Referenced by BudgetExecution.Transfer.Transfer.
BudgetExecution.Transfer.Transfer()
Referenced by BudgetExecution.Transfer.Select.
BudgetExecution.Transfer.Transfer(string bl, string docType, string rpio, string org, string rc, string bfy, string fund, string tcn, string qtr, string date, string code, string progproj, string ppn, string npmcode, string fromto, string boc, decimal amount)
References BudgetExecution.Transfer.Account, BudgetExecution.Transfer.Amount, BudgetExecution.Transfer.BFY, BudgetExecution.Transfer.BOC, BudgetExecution.Transfer.BudgetLevel, BudgetExecution.Transfer.Code, BudgetExecution.Transfer.Date, BudgetExecution.Transfer.DocType, BudgetExecution.Transfer.FromTo, BudgetExecution.Transfer.Fund, BudgetExecution.Account.NPM, BudgetExecution.Transfer.NpmCode, BudgetExecution.Transfer.Org, BudgetExecution.Transfer.Qtr, BudgetExecution.Transfer.RC, BudgetExecution.Transfer.RPIO, BudgetExecution.Transfer.TCN.
BudgetExecution.Transfer.Transfer(DataRow dr)
References BudgetExecution.Transfer.Account, BudgetExecution.Transfer.Amount, BudgetExecution.Transfer.BFY, BudgetExecution.Transfer.BOC, BudgetExecution.Transfer.BudgetLevel, BudgetExecution.Transfer.Code, BudgetExecution.Transfer.Date, BudgetExecution.Transfer.DocType, BudgetExecution.Transfer.FromTo, BudgetExecution.Transfer.Fund, BudgetExecution.Account.NPM, BudgetExecution.Transfer.NpmCode, BudgetExecution.Transfer.Org, BudgetExecution.Transfer.Qtr, BudgetExecution.Transfer.RC, BudgetExecution.Transfer.RPIO, BudgetExecution.Transfer.TCN.
static Dictionary<string, object> BudgetExecution.Transfer.GetInsertionColumns(Source source, Provider provider, Dictionary< string, object > param)
References BudgetExecution.Transfer.Fund.
Referenced by BudgetExecution.Transfer.Insert.
static Transfer BudgetExecution.Transfer.Select(Source source, Dictionary< string, object > p)
References BudgetExecution.Transfer.Transfer.
Referenced by BudgetExecution.Transfer.Select.
static Transfer BudgetExecution.Transfer.Select(Source source, Provider provider, Dictionary< string, object > p)
References BudgetExecution.Transfer.Select, BudgetExecution.Transfer.Transfer.
static void BudgetExecution.Transfer.Insert(Source source, Dictionary< string, object > p)
References BudgetExecution.Transfer.GetInsertionColumns.
static void BudgetExecution.Transfer.Insert(Source source, Provider provider, Dictionary< string, object > p)
References BudgetExecution.Transfer.GetInsertionColumns.
static void BudgetExecution.Transfer.Update(Source source, Dictionary< string, object > p)
References BudgetExecution.Transfer.Amount, BudgetExecution.ID.
static void BudgetExecution.Transfer.Update(Source source, Provider provider, Dictionary< string, object > p)
References BudgetExecution.Transfer.Amount, BudgetExecution.ID.
static void BudgetExecution.Transfer.Delete(Source source, Dictionary< string, object > p)
References BudgetExecution.ID.
static void BudgetExecution.Transfer.Delete(Source source, Provider provider, Dictionary< string, object > p)
References BudgetExecution.ID.