BudgetExecution::SQLiteData
Source BudgetExecution.SQLiteData.Source
Referenced by BudgetExecution.SQLiteData.FilterControlButton_OnClick.
Provider BudgetExecution.SQLiteData.Provider
DataFilter BudgetExecution.SQLiteData.TableFilter
Referenced by BudgetExecution.SQLiteData.Filter1_SelectedIndexChanged, BudgetExecution.SQLiteData.Filter2_SelectedIndexChanged, BudgetExecution.SQLiteData.Filter3_SelectedIndexChanged, BudgetExecution.SQLiteData.Filter4_SelectedIndexChanged, BudgetExecution.SQLiteData.SQLiteData.
ColumnFilter BudgetExecution.SQLiteData.FieldFilter
Referenced by BudgetExecution.SQLiteData.PopulateFilterItems, BudgetExecution.SQLiteData.SQLiteData.
DataBuilder BudgetExecution.SQLiteData.DbData
Referenced by BudgetExecution.SQLiteData.GetDataBase, BudgetExecution.SQLiteData.SQLiteData, BudgetExecution.SQLiteData.SQLiteData_Load.
Dictionary<string, object> BudgetExecution.SQLiteData.Parameter
Dictionary<string, string[]> BudgetExecution.SQLiteData.ProgramElements
Referenced by BudgetExecution.SQLiteData.SQLiteData.
DataTable BudgetExecution.SQLiteData.Table
Referenced by BudgetExecution.SQLiteData.Filter1_SelectedIndexChanged, BudgetExecution.SQLiteData.Filter2_SelectedIndexChanged, BudgetExecution.SQLiteData.Filter3_SelectedIndexChanged, BudgetExecution.SQLiteData.Filter4_SelectedIndexChanged, BudgetExecution.SQLiteData.SQLiteData.
string BudgetExecution.SQLiteData.F1
Referenced by BudgetExecution.SQLiteData.Filter1_SelectedIndexChanged, BudgetExecution.SQLiteData.Filter2_SelectedIndexChanged, BudgetExecution.SQLiteData.Filter3_SelectedIndexChanged, BudgetExecution.SQLiteData.Filter4_SelectedIndexChanged.
string BudgetExecution.SQLiteData.F2
Referenced by BudgetExecution.SQLiteData.Filter2_SelectedIndexChanged, BudgetExecution.SQLiteData.Filter3_SelectedIndexChanged, BudgetExecution.SQLiteData.Filter4_SelectedIndexChanged.
string BudgetExecution.SQLiteData.F3
Referenced by BudgetExecution.SQLiteData.Filter3_SelectedIndexChanged, BudgetExecution.SQLiteData.Filter4_SelectedIndexChanged.
string BudgetExecution.SQLiteData.F4
Referenced by BudgetExecution.SQLiteData.Filter4_SelectedIndexChanged.
Field BudgetExecution.SQLiteData.C1
Referenced by BudgetExecution.SQLiteData.Filter1_SelectedIndexChanged, BudgetExecution.SQLiteData.Filter2_SelectedIndexChanged, BudgetExecution.SQLiteData.Filter3_SelectedIndexChanged, BudgetExecution.SQLiteData.Filter4_SelectedIndexChanged.
Field BudgetExecution.SQLiteData.C2
Referenced by BudgetExecution.SQLiteData.Filter2_SelectedIndexChanged, BudgetExecution.SQLiteData.Filter3_SelectedIndexChanged, BudgetExecution.SQLiteData.Filter4_SelectedIndexChanged.
Field BudgetExecution.SQLiteData.C3
Referenced by BudgetExecution.SQLiteData.Filter3_SelectedIndexChanged, BudgetExecution.SQLiteData.Filter4_SelectedIndexChanged.
Field BudgetExecution.SQLiteData.C4
Referenced by BudgetExecution.SQLiteData.Filter4_SelectedIndexChanged.
System.ComponentModel.IContainer BudgetExecution.SQLiteData.components
Required designer variable.
Referenced by BudgetExecution.SQLiteData.Dispose.
Syncfusion.Windows.Forms.Grid.GridDataBoundGrid BudgetExecution.SQLiteData.E6DataGrid
Referenced by BudgetExecution.SQLiteData.InitializeComponent.
Syncfusion.Windows.Forms.Tools.toolstripitem BudgetExecution.SQLiteData.toolstripitem1
System.Windows.Forms.ToolStripButton BudgetExecution.SQLiteData.bindingNavigatorAddNewItem
System.Windows.Forms.ToolStripLabel BudgetExecution.SQLiteData.bindingNavigatorCountItem
System.Windows.Forms.ToolStripButton BudgetExecution.SQLiteData.bindingNavigatorDeleteItem
System.Windows.Forms.ToolStripButton BudgetExecution.SQLiteData.bindingNavigatorMoveFirstItem
System.Windows.Forms.ToolStripButton BudgetExecution.SQLiteData.bindingNavigatorMovePreviousItem
System.Windows.Forms.ToolStripSeparator BudgetExecution.SQLiteData.bindingNavigatorSeparator
System.Windows.Forms.ToolStripTextBox BudgetExecution.SQLiteData.bindingNavigatorPositionItem
System.Windows.Forms.ToolStripSeparator BudgetExecution.SQLiteData.bindingNavigatorSeparator1
System.Windows.Forms.ToolStripButton BudgetExecution.SQLiteData.bindingNavigatorMoveNextItem
System.Windows.Forms.ToolStripButton BudgetExecution.SQLiteData.bindingNavigatorMoveLastItem
System.Windows.Forms.ToolStripSeparator BudgetExecution.SQLiteData.bindingNavigatorSeparator2
System.Windows.Forms.ToolStripButton BudgetExecution.SQLiteData.toolStripButton1
System.Windows.Forms.ToolStripButton BudgetExecution.SQLiteData.toolStripButton2
System.Windows.Forms.BindingSource BudgetExecution.SQLiteData.BindingSource
Referenced by BudgetExecution.SQLiteData.InitializeComponent, BudgetExecution.SQLiteData.SQLiteData.
MetroSet_UI.Controls.MetroSetComboBox BudgetExecution.SQLiteData.Filter2
Referenced by BudgetExecution.SQLiteData.Filter1_SelectedIndexChanged.
MetroFramework.Controls.MetroPanel BudgetExecution.SQLiteData.metroPanel1
System.Windows.Forms.DataGridView BudgetExecution.SQLiteData.Grid
Referenced by BudgetExecution.SQLiteData.InitializeComponent.
System.Windows.Forms.FlowLayoutPanel BudgetExecution.SQLiteData.flowLayoutPanel1
System.Windows.Forms.Button BudgetExecution.SQLiteData.button1
System.Windows.Forms.Button BudgetExecution.SQLiteData.button6
System.Windows.Forms.Button BudgetExecution.SQLiteData.button7
System.Windows.Forms.Button BudgetExecution.SQLiteData.button10
System.Windows.Forms.Button BudgetExecution.SQLiteData.button13
MetroFramework.Controls.MetroPanel BudgetExecution.SQLiteData.metroPanel3
MetroSet_UI.Controls.MetroSetComboBox BudgetExecution.SQLiteData.Filter3
Referenced by BudgetExecution.SQLiteData.Filter2_SelectedIndexChanged.
MetroFramework.Controls.MetroPanel BudgetExecution.SQLiteData.metroPanel4
MetroFramework.Controls.MetroPanel BudgetExecution.SQLiteData.metroPanel5
Syncfusion.Windows.Forms.Tools.TabControlAdv BudgetExecution.SQLiteData.DataTabControl
Referenced by BudgetExecution.SQLiteData.InitializeComponent.
Syncfusion.Windows.Forms.Tools.TabPageAdv BudgetExecution.SQLiteData.FilterTab
Syncfusion.Windows.Forms.Tools.TabPageAdv BudgetExecution.SQLiteData.FunctionTab
MetroSet_UI.Controls.MetroSetComboBox BudgetExecution.SQLiteData.Filter1
Referenced by BudgetExecution.SQLiteData.GetDataBase, BudgetExecution.SQLiteData.SQLiteData.
System.Windows.Forms.TableLayoutPanel BudgetExecution.SQLiteData.tableLayoutPanel1
System.Windows.Forms.Label BudgetExecution.SQLiteData.label5
System.Windows.Forms.Label BudgetExecution.SQLiteData.label10
System.Windows.Forms.Label BudgetExecution.SQLiteData.label6
System.Windows.Forms.Label BudgetExecution.SQLiteData.label9
System.Windows.Forms.Label BudgetExecution.SQLiteData.label7
System.Windows.Forms.Label BudgetExecution.SQLiteData.label8
System.Windows.Forms.Label BudgetExecution.SQLiteData.label11
System.Windows.Forms.Label BudgetExecution.SQLiteData.label12
MetroSet_UI.Controls.MetroSetComboBox BudgetExecution.SQLiteData.Filter4
Referenced by BudgetExecution.SQLiteData.Filter3_SelectedIndexChanged.
System.Windows.Forms.Label BudgetExecution.SQLiteData.label4
Referenced by BudgetExecution.SQLiteData.Filter3_SelectedIndexChanged.
System.Windows.Forms.Label BudgetExecution.SQLiteData.label3
Referenced by BudgetExecution.SQLiteData.Filter2_SelectedIndexChanged.
System.Windows.Forms.Label BudgetExecution.SQLiteData.label2
Referenced by BudgetExecution.SQLiteData.Filter1_SelectedIndexChanged.
System.Windows.Forms.Label BudgetExecution.SQLiteData.label1
Referenced by BudgetExecution.SQLiteData.GetDataBase.
System.Windows.Forms.BindingNavigator BudgetExecution.SQLiteData.Navigator
Referenced by BudgetExecution.SQLiteData.InitializeComponent.
System.Windows.Forms.ToolStripLabel BudgetExecution.SQLiteData.toolStripLabel2
System.Windows.Forms.ToolStripSeparator BudgetExecution.SQLiteData.toolStripSeparator3
System.Windows.Forms.ToolStripButton BudgetExecution.SQLiteData.toolStripButton10
System.Windows.Forms.ToolStripSeparator BudgetExecution.SQLiteData.toolStripSeparator10
System.Windows.Forms.ToolStripTextBox BudgetExecution.SQLiteData.toolStripTextBox2
System.Windows.Forms.ToolStripSeparator BudgetExecution.SQLiteData.toolStripSeparator11
System.Windows.Forms.ToolStripButton BudgetExecution.SQLiteData.toolStripButton11
System.Windows.Forms.ToolStripSeparator BudgetExecution.SQLiteData.toolStripSeparator13
System.Windows.Forms.ToolStripButton BudgetExecution.SQLiteData.CopyButton
System.Windows.Forms.ToolStripSeparator BudgetExecution.SQLiteData.toolStripSeparator15
System.Windows.Forms.ToolStripButton BudgetExecution.SQLiteData.toolStripButton13
System.Windows.Forms.ToolStripSeparator BudgetExecution.SQLiteData.toolStripSeparator18
System.Windows.Forms.ToolStripButton BudgetExecution.SQLiteData.toolStripButton12
System.Windows.Forms.ToolStripSeparator BudgetExecution.SQLiteData.toolStripSeparator16
System.Windows.Forms.ToolStripButton BudgetExecution.SQLiteData.ResetButton
System.Windows.Forms.ToolStripSeparator BudgetExecution.SQLiteData.toolStripSeparator14
System.Windows.Forms.ToolStripButton BudgetExecution.SQLiteData.AddButton
System.Windows.Forms.ToolStripSeparator BudgetExecution.SQLiteData.toolStripSeparator19
System.Windows.Forms.ToolStripButton BudgetExecution.SQLiteData.toolStripButton7
System.Windows.Forms.ToolStripSeparator BudgetExecution.SQLiteData.GridRefreshButton
System.Windows.Forms.ToolStripButton BudgetExecution.SQLiteData.toolStripButton9
System.Windows.Forms.ToolStripSeparator BudgetExecution.SQLiteData.toolStripSeparator12
System.Windows.Forms.ToolStripButton BudgetExecution.SQLiteData.toolStripButton14
System.Windows.Forms.ToolStripSeparator BudgetExecution.SQLiteData.toolStripSeparator17
System.Windows.Forms.ToolStripButton BudgetExecution.SQLiteData.toolStripButton15
System.Windows.Forms.ToolStripSeparator BudgetExecution.SQLiteData.toolStripSeparator20
System.Windows.Forms.ToolStripButton BudgetExecution.SQLiteData.toolStripButton16
BudgetExecution.SQLiteData.SQLiteData()
References BudgetExecution.SQLiteData.BindingSource, BudgetExecution.ColumnFilter, BudgetExecution.DataFilter, BudgetExecution.SQLiteData.DbData, BudgetExecution.SQLiteData.FieldFilter, BudgetExecution.SQLiteData.Filter1, BudgetExecution.Info.FilterRows, BudgetExecution.Info.GetColumnValues, BudgetExecution.SQLiteData.InitializeComponent, BudgetExecution.SQLiteData.PopulateFilterButtons, BudgetExecution.SQLiteData.ProgramElements, BudgetExecution.Info.Sources, BudgetExecution.SQLiteData.Table, BudgetExecution.SQLiteData.TableFilter.
BudgetExecution.SQLiteData.SQLiteData(Source source, Provider provider)
References BudgetExecution.SQLiteData.BindingSource, BudgetExecution.ColumnFilter, BudgetExecution.DataFilter, BudgetExecution.SQLiteData.DbData, BudgetExecution.SQLiteData.FieldFilter, BudgetExecution.Info.FilterRows, BudgetExecution.Info.GetColumnValues, BudgetExecution.SQLiteData.InitializeComponent, BudgetExecution.SQLiteData.ProgramElements, BudgetExecution.SQLiteData.Table, BudgetExecution.SQLiteData.TableFilter.
void BudgetExecution.SQLiteData.SQLiteData_Load(object sender, EventArgs e)
References BudgetExecution.SQLiteData.DbData, BudgetExecution.SQLiteData.GetDataBase, BudgetExecution.SQLiteData.HideTopGridLabels, BudgetExecution.DataBuilder.ProgramElements.
void BudgetExecution.SQLiteData.PreviousButton_OnClick(object sender, EventArgs e)
void BudgetExecution.SQLiteData.NextButton_OnClick(object sender, EventArgs e)
void BudgetExecution.SQLiteData.AddButton_OnClick(object sender, EventArgs e)
void BudgetExecution.SQLiteData.RefreshButton_Click(object sender, EventArgs e)
void BudgetExecution.SQLiteData.CopyButton_OnClick(object sender, EventArgs e)
void BudgetExecution.SQLiteData.GetPrcGridVisibleColumns(DataGridView dgv)
void BudgetExecution.SQLiteData.HideTopGridLabels()
Referenced by BudgetExecution.SQLiteData.SQLiteData_Load.
void BudgetExecution.SQLiteData.Filter1_SelectedIndexChanged(object sender, EventArgs e)
References BudgetExecution.SQLiteData.C1, BudgetExecution.SQLiteData.F1, BudgetExecution.SQLiteData.Filter2, BudgetExecution.SQLiteData.label2, BudgetExecution.SQLiteData.PopulateFilterItems, BudgetExecution.SQLiteData.Table, BudgetExecution.SQLiteData.TableFilter.
void BudgetExecution.SQLiteData.Filter2_SelectedIndexChanged(object sender, EventArgs e)
References BudgetExecution.SQLiteData.C1, BudgetExecution.SQLiteData.C2, BudgetExecution.SQLiteData.F1, BudgetExecution.SQLiteData.F2, BudgetExecution.SQLiteData.Filter3, BudgetExecution.SQLiteData.label3, BudgetExecution.SQLiteData.PopulateFilterItems, BudgetExecution.SQLiteData.Table, BudgetExecution.SQLiteData.TableFilter.
void BudgetExecution.SQLiteData.Filter3_SelectedIndexChanged(object sender, EventArgs e)
References BudgetExecution.SQLiteData.C1, BudgetExecution.SQLiteData.C2, BudgetExecution.SQLiteData.C3, BudgetExecution.SQLiteData.F1, BudgetExecution.SQLiteData.F2, BudgetExecution.SQLiteData.F3, BudgetExecution.SQLiteData.Filter4, BudgetExecution.SQLiteData.label4, BudgetExecution.SQLiteData.PopulateFilterItems, BudgetExecution.SQLiteData.Table, BudgetExecution.SQLiteData.TableFilter.
void BudgetExecution.SQLiteData.Filter4_SelectedIndexChanged(object sender, EventArgs e)
References BudgetExecution.SQLiteData.C1, BudgetExecution.SQLiteData.C2, BudgetExecution.SQLiteData.C3, BudgetExecution.SQLiteData.C4, BudgetExecution.SQLiteData.F1, BudgetExecution.SQLiteData.F2, BudgetExecution.SQLiteData.F3, BudgetExecution.SQLiteData.F4, BudgetExecution.SQLiteData.Table, BudgetExecution.SQLiteData.TableFilter.
void BudgetExecution.SQLiteData.GetDataBase(Source source)
References BudgetExecution.SQLiteData.DbData, BudgetExecution.SQLiteData.Filter1, BudgetExecution.SQLiteData.label1, BudgetExecution.SQLiteData.PopulateFilterItems.
Referenced by BudgetExecution.SQLiteData.SQLiteData_Load.
void BudgetExecution.SQLiteData.InitializeComponent()
Required method for Designer support - do not modify the contents of this method with the code editor.
References BudgetExecution.SQLiteData.BindingSource, BudgetExecution.SQLiteData.DataTabControl, BudgetExecution.SQLiteData.E6DataGrid, BudgetExecution.F, BudgetExecution.SQLiteData.Grid, BudgetExecution.SQLiteData.Navigator.
Referenced by BudgetExecution.SQLiteData.SQLiteData.
void BudgetExecution.SQLiteData.PopulateFilterItems(string colname, DataBuilder data, MetroSetComboBox control, Label label)
Referenced by BudgetExecution.SQLiteData.Filter1_SelectedIndexChanged, BudgetExecution.SQLiteData.Filter2_SelectedIndexChanged, BudgetExecution.SQLiteData.Filter3_SelectedIndexChanged, BudgetExecution.SQLiteData.GetDataBase.
void BudgetExecution.SQLiteData.PopulateFilterItems(string colname, DataTable table, MetroSetComboBox control, Label label)
References BudgetExecution.SQLiteData.FieldFilter.
void BudgetExecution.SQLiteData.PopulateFilterItems(Field colname, DataBuilder data, MetroSetComboBox control, Label label)
void BudgetExecution.SQLiteData.PopulateFilterItems(Field colname, DataTable table, MetroSetComboBox control, Label label)
References BudgetExecution.SQLiteData.FieldFilter.
void BudgetExecution.SQLiteData.PopulateFilterButtons(MetroSetComboBox control, string[] list)
Referenced by BudgetExecution.SQLiteData.SQLiteData.
void BudgetExecution.SQLiteData.FilterControlButton_OnClick(object sender, EventArgs e)
References BudgetExecution.SQLiteData.Source.
override void BudgetExecution.SQLiteData.Dispose(bool disposing)
Clean up any resources being used.
disposing true if managed resources should be disposed; otherwise, false.
References BudgetExecution.SQLiteData.components.