BudgetExecution::AppropriationSelector
System.ComponentModel.IContainer BudgetExecution.AppropriationSelector.components
Required designer variable.
Referenced by BudgetExecution.AppropriationSelector.Dispose.
Syncfusion.Windows.Forms.Tools.Carousel BudgetExecution.AppropriationSelector.AppropriationCarousel
BudgetExecution.AppropriationSelector.AppropriationSelector()
References BudgetExecution.AppropriationSelector.AppropriationCarousel_OnImageSelected, BudgetExecution.AppropriationSelector.GetAppropriationCarouselImageList, BudgetExecution.AppropriationSelector.InitializeComponent.
void BudgetExecution.AppropriationSelector.AppropriationCarousel_OnImageSelected(object sender, EventArgs e)
References BudgetExecution.Info.AppropriationImages.
Referenced by BudgetExecution.AppropriationSelector.AppropriationSelector.
void BudgetExecution.AppropriationSelector.GetAppropriationCarouselImageList()
Referenced by BudgetExecution.AppropriationSelector.AppropriationSelector.
void BudgetExecution.AppropriationSelector.InitializeComponent()
Required method for Designer support - do not modify the contents of this method with the code editor.
References BudgetExecution.F.
Referenced by BudgetExecution.AppropriationSelector.AppropriationSelector.
override void BudgetExecution.AppropriationSelector.Dispose(bool disposing)
Clean up any resources being used.
disposing true if managed resources should be disposed; otherwise, false.
References BudgetExecution.AppropriationSelector.components.