BudgetExecution::Appropriation
Fund BudgetExecution.Appropriation.Fund
Referenced by BudgetExecution.Appropriation.Appropriation.
string BudgetExecution.Appropriation.Name
Referenced by BudgetExecution.Appropriation.Appropriation.
string BudgetExecution.Appropriation.Title
Referenced by BudgetExecution.Appropriation.Appropriation.
DataBuilder BudgetExecution.Appropriation.DbData
Referenced by BudgetExecution.Appropriation.Appropriation.
Dictionary<string, string[]> BudgetExecution.Appropriation.ProgramElements
Referenced by BudgetExecution.Appropriation.Appropriation, BudgetExecution.Appropriation.GetCodes.
PrcMetric BudgetExecution.Appropriation.Metric
Referenced by BudgetExecution.Appropriation.Appropriation.
DataTable BudgetExecution.Appropriation.DbTable
Referenced by BudgetExecution.Appropriation.Appropriation.
decimal BudgetExecution.Appropriation.Amount
decimal BudgetExecution.Appropriation.Average
Referenced by BudgetExecution.Appropriation.Appropriation, BudgetExecution.Appropriation.GetAverage.
string [] BudgetExecution.Appropriation.BocCodes
Referenced by BudgetExecution.Appropriation.Appropriation, BudgetExecution.Appropriation.GetFTE.
Dictionary<string, decimal> BudgetExecution.Appropriation.BocData
Referenced by BudgetExecution.Appropriation.Appropriation.
int BudgetExecution.Appropriation.Count
Referenced by BudgetExecution.Appropriation.Appropriation.
string BudgetExecution.Appropriation.FiscalYear
Referenced by BudgetExecution.Appropriation.Appropriation.
FTE [] BudgetExecution.Appropriation.FTE
Referenced by BudgetExecution.Appropriation.GetFTE.
Dictionary<string, decimal> BudgetExecution.Appropriation.GoalData
Referenced by BudgetExecution.Appropriation.Appropriation.
Dictionary<string, decimal> BudgetExecution.Appropriation.NpmData
Referenced by BudgetExecution.Appropriation.Appropriation.
Dictionary<string, decimal> BudgetExecution.Appropriation.ObjectiveData
Tuple<DataTable, PRC[], decimal, int> BudgetExecution.Appropriation.PrcData
Dictionary<string, decimal> BudgetExecution.Appropriation.ProgramData
Referenced by BudgetExecution.Appropriation.Appropriation.
string [] BudgetExecution.Appropriation.Project
Dictionary<string, decimal> BudgetExecution.Appropriation.ProjectData
decimal BudgetExecution.Appropriation.Total
Referenced by BudgetExecution.Appropriation.Appropriation, BudgetExecution.Appropriation.GetMetrics.
DataRow [] BudgetExecution.Appropriation.Data
BudgetExecution.Appropriation.Appropriation()
BudgetExecution.Appropriation.Appropriation(string fundcode, string bfy)
References BudgetExecution.Appropriation.FiscalYear, BudgetExecution.Fund.FiscalYear, BudgetExecution.Appropriation.Fund, BudgetExecution.Appropriation.Name, BudgetExecution.Fund.Name, BudgetExecution.Appropriation.Title, BudgetExecution.Fund.Title.
BudgetExecution.Appropriation.Appropriation(Source source, Provider provider, string fundcode, string bfy)
References BudgetExecution.Appropriation.Average, BudgetExecution.Appropriation.BocCodes, BudgetExecution.Appropriation.BocData, BudgetExecution.Appropriation.Count, BudgetExecution.Appropriation.DbData, BudgetExecution.Appropriation.DbTable, BudgetExecution.Appropriation.GetFTE, BudgetExecution.Appropriation.GetProgramElements, BudgetExecution.Appropriation.GoalData, BudgetExecution.Appropriation.Metric, BudgetExecution.Appropriation.NpmData, BudgetExecution.Appropriation.ProgramData, BudgetExecution.Appropriation.ProgramElements, BudgetExecution.Appropriation.Total.
DataTable BudgetExecution.Appropriation.FilterTable(DataTable table, string column, string filter)
decimal BudgetExecution.Appropriation.GetAverage(DataTable table)
References BudgetExecution.Appropriation.Average, BudgetExecution.M, BudgetExecution.Select.
Referenced by BudgetExecution.Appropriation.GetMetrics.
string [] BudgetExecution.Appropriation.GetCodes(DataTable table, string column)
References BudgetExecution.Select.
Tuple<string[], string[], string[], string[], string[]> BudgetExecution.Appropriation.GetCodes()
References BudgetExecution.Appropriation.ProgramElements.
Referenced by BudgetExecution.Appropriation.GetMetrics, BudgetExecution.Appropriation.GetProgramElements, BudgetExecution.Appropriation.GetTotals.
int BudgetExecution.Appropriation.GetCount(DataTable table)
References BudgetExecution.Select.
Referenced by BudgetExecution.Appropriation.GetDataValues, BudgetExecution.Appropriation.GetMetrics.
Tuple<DataTable, PRC[], decimal, int> BudgetExecution.Appropriation.GetDataValues(DataTable table, string column, string filter)
References BudgetExecution.Appropriation.GetCount, BudgetExecution.Appropriation.GetPrcArray, BudgetExecution.Appropriation.GetTotal.
Referenced by BudgetExecution.Appropriation.GetMetrics.
Tuple<DataTable, PRC[], decimal, int> BudgetExecution.Appropriation.GetDataValues(DataTable table, string[] list, string column)
References BudgetExecution.Appropriation.GetCount, BudgetExecution.Appropriation.GetPrcArray, BudgetExecution.Appropriation.GetTotal.
decimal BudgetExecution.Appropriation.GetFteTotal()
References BudgetExecution.Select.
decimal [] BudgetExecution.Appropriation.GetMetrics(DataTable table)
References BudgetExecution.Appropriation.GetAverage, BudgetExecution.Appropriation.GetCount, BudgetExecution.Appropriation.GetTotal.
Dictionary<string, decimal[]> BudgetExecution.Appropriation.GetMetrics(DataTable table, string[] list, string column)
References BudgetExecution.Appropriation.GetDataValues, BudgetExecution.Appropriation.Total.
Dictionary<string, decimal[]> BudgetExecution.Appropriation.GetMetrics(DataTable table, string column, string filter)
References BudgetExecution.Appropriation.GetCodes, BudgetExecution.Appropriation.GetDataValues, BudgetExecution.Appropriation.Total.
PRC [] BudgetExecution.Appropriation.GetPrcArray(DataTable table)
References BudgetExecution.PRC, BudgetExecution.Select.
Referenced by BudgetExecution.Appropriation.GetDataValues.
Dictionary<string, string[]> BudgetExecution.Appropriation.GetProgramElements(DataTable table)
References BudgetExecution.Appropriation.GetCodes.
Referenced by BudgetExecution.Appropriation.Appropriation.
decimal BudgetExecution.Appropriation.GetTotal(DataTable table)
References BudgetExecution.M.
Referenced by BudgetExecution.Appropriation.GetDataValues, BudgetExecution.Appropriation.GetMetrics, BudgetExecution.Appropriation.GetTotals.
Dictionary<string, decimal> BudgetExecution.Appropriation.GetTotals(DataTable table, string column, string filter)
References BudgetExecution.Appropriation.GetCodes.
Dictionary<string, decimal> BudgetExecution.Appropriation.GetTotals(DataTable table, string[] filters, string column)
References BudgetExecution.Appropriation.GetTotal.
FTE [] BudgetExecution.Appropriation.GetFTE(DataTable table)
References BudgetExecution.Appropriation.BocCodes, BudgetExecution.Appropriation.FTE.
Referenced by BudgetExecution.Appropriation.Appropriation.