BudgetExecution::SummaryForm
Source BudgetExecution.SummaryForm.Source
Provider BudgetExecution.SummaryForm.Provider
Dictionary<string, object> BudgetExecution.SummaryForm.Parameter
Referenced by BudgetExecution.SummaryForm.SummaryForm.
DataBuilder BudgetExecution.SummaryForm.DbData
Referenced by BudgetExecution.SummaryForm.Form_Load, BudgetExecution.SummaryForm.GridRefreshButton_OnClick, BudgetExecution.SummaryForm.SummaryForm, BudgetExecution.SummaryForm.SummaryTabPage_TabSelected.
DataTable BudgetExecution.SummaryForm.Table
Referenced by BudgetExecution.SummaryForm.Form_Load, BudgetExecution.SummaryForm.SummaryForm, BudgetExecution.SummaryForm.SummaryTabPage_TabSelected, BudgetExecution.SummaryForm.UpdateAccountChart.
DataRow BudgetExecution.SummaryForm.DbRow
Referenced by BudgetExecution.SummaryForm.SummaryTabPage_TabSelected, BudgetExecution.SummaryForm.UpdateAccountChart.
PrcMetric BudgetExecution.SummaryForm.Metric
Referenced by BudgetExecution.SummaryForm.SummaryForm.
ChartSeriesType BudgetExecution.SummaryForm.ChartType
Referenced by BudgetExecution.SummaryForm.ChartFilterControl1_ItemSelected, BudgetExecution.SummaryForm.ChartFilterControl4_ItemSelected.
Field BudgetExecution.SummaryForm.ChartField
Referenced by BudgetExecution.SummaryForm.ChartFilterControl3_ItemSelected.
string BudgetExecution.SummaryForm.ChartFilter
Referenced by BudgetExecution.SummaryForm.ChartFilterControl3_ItemSelected, BudgetExecution.SummaryForm.ChartFilterControl4_ItemSelected.
string BudgetExecution.SummaryForm.Division
Referenced by BudgetExecution.SummaryForm.SummaryForm.
Field BudgetExecution.SummaryForm.ChartGroup
Referenced by BudgetExecution.SummaryForm.ChartFilterControl4_ItemSelected.
Dictionary<string, string[]> BudgetExecution.SummaryForm.ProgramElements
Referenced by BudgetExecution.SummaryForm.SummaryForm.
string [] BudgetExecution.SummaryForm.ChartMainTitle
Referenced by BudgetExecution.SummaryForm.ChartFilterControl4_ItemSelected, BudgetExecution.SummaryForm.SummaryTabPage_TabSelected.
string [] BudgetExecution.SummaryForm.ChartAxisTitle
int BudgetExecution.SummaryForm.CurrentTabIndex
Referenced by BudgetExecution.SummaryForm.ChartFilterControl4_ItemSelected, BudgetExecution.SummaryForm.Expander_Click, BudgetExecution.SummaryForm.GetTitle, BudgetExecution.SummaryForm.SummaryForm, BudgetExecution.SummaryForm.SummaryTabPage_TabSelected.
MetroSetComboBox BudgetExecution.SummaryForm.GridFilterControl1
MetroSetComboBox BudgetExecution.SummaryForm.GridFilterControl2
MetroSetComboBox BudgetExecution.SummaryForm.GridFilterControl3
MetroSetComboBox BudgetExecution.SummaryForm.ChartFilterControl1
Referenced by BudgetExecution.SummaryForm.AssignChartFIlterControls, BudgetExecution.SummaryForm.ChartFilterControl1_ItemSelected.
MetroSetComboBox BudgetExecution.SummaryForm.ChartFilterControl2
Referenced by BudgetExecution.SummaryForm.AssignChartFIlterControls, BudgetExecution.SummaryForm.ChartFilterControl2_ItemSelected.
MetroSetComboBox BudgetExecution.SummaryForm.ChartFilterControl3
Referenced by BudgetExecution.SummaryForm.AssignChartFIlterControls, BudgetExecution.SummaryForm.ChartFilterControl3_ItemSelected, BudgetExecution.SummaryForm.SummaryTabPage_TabSelected.
MetroSetComboBox BudgetExecution.SummaryForm.ChartFilterControl4
Referenced by BudgetExecution.SummaryForm.AssignChartFIlterControls, BudgetExecution.SummaryForm.ChartFilterControl4_ItemSelected.
ExpandCollapsePanel BudgetExecution.SummaryForm.Expander1
Referenced by BudgetExecution.SummaryForm.AssignChartExpanders.
ExpandCollapsePanel BudgetExecution.SummaryForm.Expander2
Referenced by BudgetExecution.SummaryForm.AssignChartExpanders, BudgetExecution.SummaryForm.ChartFilterControl1_ItemSelected, BudgetExecution.SummaryForm.ChartFilterControl2_ItemSelected.
Stat BudgetExecution.SummaryForm.Measure
Referenced by BudgetExecution.SummaryForm.ChartFilterControl2_ItemSelected, BudgetExecution.SummaryForm.ChartFilterControl4_ItemSelected.
TabPageAdv [] BudgetExecution.SummaryForm.Tab
string [] BudgetExecution.SummaryForm.TabNames
Referenced by BudgetExecution.SummaryForm.PopulateFilterBoxItems, BudgetExecution.SummaryForm.SummaryForm.
System.ComponentModel.IContainer BudgetExecution.SummaryForm.components
Required designer variable.
Referenced by BudgetExecution.SummaryForm.Dispose.
toolstripitem BudgetExecution.SummaryForm.toolstripitem1
toolstripitem BudgetExecution.SummaryForm.toolstripitem2
ToolStripButton BudgetExecution.SummaryForm.toolStripButton1
ToolStripLabel BudgetExecution.SummaryForm.toolStripLabel1
ToolStripButton BudgetExecution.SummaryForm.toolStripButton3
ToolStripSeparator BudgetExecution.SummaryForm.toolStripSeparator4
ToolStripButton BudgetExecution.SummaryForm.toolStripButton4
ToolStripSeparator BudgetExecution.SummaryForm.toolStripSeparator5
ToolStripTextBox BudgetExecution.SummaryForm.toolStripTextBox1
ToolStripSeparator BudgetExecution.SummaryForm.toolStripSeparator6
ToolStripButton BudgetExecution.SummaryForm.toolStripButton5
ToolStripSeparator BudgetExecution.SummaryForm.toolStripSeparator7
ToolStripButton BudgetExecution.SummaryForm.toolStripButton6
ToolStripSeparator BudgetExecution.SummaryForm.toolStripSeparator8
ToolStripButton BudgetExecution.SummaryForm.toolStripButton8
ToolStripSeparator BudgetExecution.SummaryForm.toolStripSeparator2
ToolStripSeparator BudgetExecution.SummaryForm.toolStripSeparator9
ToolStripButton BudgetExecution.SummaryForm.toolStripButton2
ToolStripSeparator BudgetExecution.SummaryForm.toolStripSeparator1
TabPageAdv BudgetExecution.SummaryForm.tabPageAdv4
CalculatorControl BudgetExecution.SummaryForm.calculatorControl1
TabPageAdv BudgetExecution.SummaryForm.tabPageAdv3
ChartTitle BudgetExecution.SummaryForm.chartTitle1
TabPageAdv BudgetExecution.SummaryForm.tabPageAdv2
MetroSetLabel BudgetExecution.SummaryForm.dd
MetroSetTextBox BudgetExecution.SummaryForm.metroSetTextBox2
MetroSetTextBox BudgetExecution.SummaryForm.rcc
MetroSetLabel BudgetExecution.SummaryForm.metroSetLabel11
MetroSetLabel BudgetExecution.SummaryForm.metroSetLabel7
MetroSetTextBox BudgetExecution.SummaryForm.Amount2
MetroSetTextBox BudgetExecution.SummaryForm.Amount1
MetroSetTextBox BudgetExecution.SummaryForm.cd
MetroSetTextBox BudgetExecution.SummaryForm.bb
MetroSetLabel BudgetExecution.SummaryForm.metroSetLabel6
MetroSetLabel BudgetExecution.SummaryForm.metroSetLabel5
MetroSetLabel BudgetExecution.SummaryForm.metroSetLabel4
MetroSetLabel BudgetExecution.SummaryForm.metroSetLabel3
MetroSetTextBox BudgetExecution.SummaryForm.ff
MetroSetButton BudgetExecution.SummaryForm.metroSetButton2
MetroSetLabel BudgetExecution.SummaryForm.metroSetLabel10
MetroSetButton BudgetExecution.SummaryForm.metroSetButton1
MetroSetLabel BudgetExecution.SummaryForm.metroSetLabel15
MetroSetTextBox BudgetExecution.SummaryForm.yy
MetroSetTextBox BudgetExecution.SummaryForm.o
TabControlAdv BudgetExecution.SummaryForm.MiniTabControl1
Referenced by BudgetExecution.SummaryForm.InitializeComponent.
TabPageAdv BudgetExecution.SummaryForm.ProjectTab
MakarovDev.ExpandCollapsePanel.ExpandCollapsePanel BudgetExecution.SummaryForm.ProjectExpander1
Referenced by BudgetExecution.SummaryForm.SummaryTabPage_TabSelected.
ButtonEditChildButton BudgetExecution.SummaryForm.buttonEditChildButton1
TabPageAdv BudgetExecution.SummaryForm.AreaTab
MakarovDev.ExpandCollapsePanel.ExpandCollapsePanel BudgetExecution.SummaryForm.AreaExpander1
Referenced by BudgetExecution.SummaryForm.SummaryTabPage_TabSelected.
TabPageAdv BudgetExecution.SummaryForm.DivisionTab
MakarovDev.ExpandCollapsePanel.ExpandCollapsePanel BudgetExecution.SummaryForm.DivisionExpander1
Referenced by BudgetExecution.SummaryForm.SummaryTabPage_TabSelected.
MetroSetComboBox BudgetExecution.SummaryForm.DivisionFilter2
Referenced by BudgetExecution.SummaryForm.SummaryTabPage_TabSelected.
TabPageAdv BudgetExecution.SummaryForm.ObjectiveTab
MakarovDev.ExpandCollapsePanel.ExpandCollapsePanel BudgetExecution.SummaryForm.ObjectiveExpander1
Referenced by BudgetExecution.SummaryForm.SummaryTabPage_TabSelected.
TabPageAdv BudgetExecution.SummaryForm.GoalTab
MakarovDev.ExpandCollapsePanel.ExpandCollapsePanel BudgetExecution.SummaryForm.GoalExpander1
Referenced by BudgetExecution.SummaryForm.SummaryTabPage_TabSelected.
TabPageAdv BudgetExecution.SummaryForm.NpmTab
MakarovDev.ExpandCollapsePanel.ExpandCollapsePanel BudgetExecution.SummaryForm.NpmExpander1
Referenced by BudgetExecution.SummaryForm.SummaryTabPage_TabSelected.
TabPageAdv BudgetExecution.SummaryForm.BocTab
TabPageAdv BudgetExecution.SummaryForm.FundTab
MakarovDev.ExpandCollapsePanel.ExpandCollapsePanel BudgetExecution.SummaryForm.FundExpander1
Referenced by BudgetExecution.SummaryForm.SummaryTabPage_TabSelected.
TabControlAdv BudgetExecution.SummaryForm.SummaryTabControl
Referenced by BudgetExecution.SummaryForm.InitializeComponent, BudgetExecution.SummaryForm.SummaryTabPage_TabSelected.
MetroSetComboBox BudgetExecution.SummaryForm.ObjectiveFilter2
Referenced by BudgetExecution.SummaryForm.SummaryTabPage_TabSelected.
MetroSetComboBox BudgetExecution.SummaryForm.GoalFilter2
Referenced by BudgetExecution.SummaryForm.SummaryTabPage_TabSelected.
MetroSetComboBox BudgetExecution.SummaryForm.FundFilter2
Referenced by BudgetExecution.SummaryForm.SummaryTabPage_TabSelected.
MetroSetComboBox BudgetExecution.SummaryForm.ProjectFilter2
Referenced by BudgetExecution.SummaryForm.SummaryTabPage_TabSelected.
MetroSetComboBox BudgetExecution.SummaryForm.AreaFilter2
Referenced by BudgetExecution.SummaryForm.SummaryTabPage_TabSelected.
MakarovDev.ExpandCollapsePanel.ExpandCollapsePanel BudgetExecution.SummaryForm.BocExpander1
Referenced by BudgetExecution.SummaryForm.SummaryTabPage_TabSelected.
MetroSetComboBox BudgetExecution.SummaryForm.BocFilter2
Referenced by BudgetExecution.SummaryForm.SummaryTabPage_TabSelected.
MetroSetComboBox BudgetExecution.SummaryForm.BocFilter1
Referenced by BudgetExecution.SummaryForm.SummaryTabPage_TabSelected.
MetroSetComboBox BudgetExecution.SummaryForm.NpmFilter2
Referenced by BudgetExecution.SummaryForm.SummaryTabPage_TabSelected.
MetroSetComboBox BudgetExecution.SummaryForm.NpmFilter1
Referenced by BudgetExecution.SummaryForm.SummaryTabPage_TabSelected.
MetroSetComboBox BudgetExecution.SummaryForm.ProjectFilter1
Referenced by BudgetExecution.SummaryForm.SummaryTabPage_TabSelected.
MetroSetComboBox BudgetExecution.SummaryForm.AreaFilter1
Referenced by BudgetExecution.SummaryForm.SummaryTabPage_TabSelected.
MetroSetComboBox BudgetExecution.SummaryForm.DivisionFilter1
Referenced by BudgetExecution.SummaryForm.SummaryTabPage_TabSelected.
MetroSetComboBox BudgetExecution.SummaryForm.ObjectiveFilter1
Referenced by BudgetExecution.SummaryForm.SummaryTabPage_TabSelected.
MetroSetComboBox BudgetExecution.SummaryForm.GoalFilter1
Referenced by BudgetExecution.SummaryForm.SummaryTabPage_TabSelected.
MetroSetComboBox BudgetExecution.SummaryForm.FundFilter1
Referenced by BudgetExecution.SummaryForm.SummaryTabPage_TabSelected.
Label BudgetExecution.SummaryForm.label23
Label BudgetExecution.SummaryForm.label24
Label BudgetExecution.SummaryForm.label20
Label BudgetExecution.SummaryForm.label21
Label BudgetExecution.SummaryForm.label17
Label BudgetExecution.SummaryForm.label18
Label BudgetExecution.SummaryForm.label14
Label BudgetExecution.SummaryForm.label15
Label BudgetExecution.SummaryForm.label11
Label BudgetExecution.SummaryForm.label12
Label BudgetExecution.SummaryForm.label8
Label BudgetExecution.SummaryForm.label9
Label BudgetExecution.SummaryForm.label5
Label BudgetExecution.SummaryForm.label6
Label BudgetExecution.SummaryForm.label3
Label BudgetExecution.SummaryForm.label2
Label BudgetExecution.SummaryForm.label1
MetroSetComboBox BudgetExecution.SummaryForm.FundFilter3
Referenced by BudgetExecution.SummaryForm.SummaryTabPage_TabSelected.
MakarovDev.ExpandCollapsePanel.ExpandCollapsePanel BudgetExecution.SummaryForm.BocExpander2
Referenced by BudgetExecution.SummaryForm.Expander_Click, BudgetExecution.SummaryForm.SummaryTabPage_TabSelected.
MetroSetComboBox BudgetExecution.SummaryForm.BocFilter4
Referenced by BudgetExecution.SummaryForm.SummaryTabPage_TabSelected.
MetroSetComboBox BudgetExecution.SummaryForm.BocFilter3
Referenced by BudgetExecution.SummaryForm.SummaryTabPage_TabSelected.
MakarovDev.ExpandCollapsePanel.ExpandCollapsePanel BudgetExecution.SummaryForm.FundExpander2
Referenced by BudgetExecution.SummaryForm.Expander_Click, BudgetExecution.SummaryForm.SummaryTabPage_TabSelected.
Label BudgetExecution.SummaryForm.label25
MetroSetComboBox BudgetExecution.SummaryForm.FundFilter4
Referenced by BudgetExecution.SummaryForm.SummaryTabPage_TabSelected.
MakarovDev.ExpandCollapsePanel.ExpandCollapsePanel BudgetExecution.SummaryForm.ProjectExpander2
Referenced by BudgetExecution.SummaryForm.Expander_Click, BudgetExecution.SummaryForm.SummaryTabPage_TabSelected.
MetroSetComboBox BudgetExecution.SummaryForm.ProjectFilter4
Referenced by BudgetExecution.SummaryForm.SummaryTabPage_TabSelected.
MetroSetComboBox BudgetExecution.SummaryForm.ProjectFilter3
Referenced by BudgetExecution.SummaryForm.SummaryTabPage_TabSelected.
MakarovDev.ExpandCollapsePanel.ExpandCollapsePanel BudgetExecution.SummaryForm.AreaExpander2
Referenced by BudgetExecution.SummaryForm.Expander_Click, BudgetExecution.SummaryForm.SummaryTabPage_TabSelected.
MetroSetComboBox BudgetExecution.SummaryForm.AreaFilter4
Referenced by BudgetExecution.SummaryForm.SummaryTabPage_TabSelected.
MetroSetComboBox BudgetExecution.SummaryForm.AreaFilter3
Referenced by BudgetExecution.SummaryForm.SummaryTabPage_TabSelected.
MakarovDev.ExpandCollapsePanel.ExpandCollapsePanel BudgetExecution.SummaryForm.DivisionExpander2
Referenced by BudgetExecution.SummaryForm.SummaryTabPage_TabSelected.
MetroSetComboBox BudgetExecution.SummaryForm.DivisionFilter4
Referenced by BudgetExecution.SummaryForm.SummaryTabPage_TabSelected.
MetroSetComboBox BudgetExecution.SummaryForm.DivisionFilter3
Referenced by BudgetExecution.SummaryForm.SummaryTabPage_TabSelected.
MakarovDev.ExpandCollapsePanel.ExpandCollapsePanel BudgetExecution.SummaryForm.ObjectiveExpander2
Referenced by BudgetExecution.SummaryForm.Expander_Click, BudgetExecution.SummaryForm.SummaryTabPage_TabSelected.
MetroSetComboBox BudgetExecution.SummaryForm.ObjectiveFilter4
Referenced by BudgetExecution.SummaryForm.SummaryTabPage_TabSelected.
MetroSetComboBox BudgetExecution.SummaryForm.ObjectiveFilter3
Referenced by BudgetExecution.SummaryForm.SummaryTabPage_TabSelected.
MakarovDev.ExpandCollapsePanel.ExpandCollapsePanel BudgetExecution.SummaryForm.GoalExpander2
Referenced by BudgetExecution.SummaryForm.Expander_Click, BudgetExecution.SummaryForm.SummaryTabPage_TabSelected.
MetroSetComboBox BudgetExecution.SummaryForm.GoalFilter4
Referenced by BudgetExecution.SummaryForm.SummaryTabPage_TabSelected.
MetroSetComboBox BudgetExecution.SummaryForm.GoalFilter3
Referenced by BudgetExecution.SummaryForm.SummaryTabPage_TabSelected.
MakarovDev.ExpandCollapsePanel.ExpandCollapsePanel BudgetExecution.SummaryForm.NpmExpander2
Referenced by BudgetExecution.SummaryForm.Expander_Click, BudgetExecution.SummaryForm.SummaryTabPage_TabSelected.
Label BudgetExecution.SummaryForm.label7
Label BudgetExecution.SummaryForm.label27
MetroSetComboBox BudgetExecution.SummaryForm.NpmFilter4
Referenced by BudgetExecution.SummaryForm.SummaryTabPage_TabSelected.
MetroSetComboBox BudgetExecution.SummaryForm.NpmFilter3
Referenced by BudgetExecution.SummaryForm.SummaryTabPage_TabSelected.
Label BudgetExecution.SummaryForm.label22
Label BudgetExecution.SummaryForm.label30
Label BudgetExecution.SummaryForm.label19
Label BudgetExecution.SummaryForm.label29
Label BudgetExecution.SummaryForm.label16
Label BudgetExecution.SummaryForm.label28
Label BudgetExecution.SummaryForm.label13
Label BudgetExecution.SummaryForm.label26
Label BudgetExecution.SummaryForm.label4
Label BudgetExecution.SummaryForm.label10
Label BudgetExecution.SummaryForm.label35
Label BudgetExecution.SummaryForm.label36
BindingSource BudgetExecution.SummaryForm.BindingSource
Referenced by BudgetExecution.SummaryForm.CopyButton_OnClick, BudgetExecution.SummaryForm.Form_Load, BudgetExecution.SummaryForm.Grid_OnDoubleClick, BudgetExecution.SummaryForm.GridRefreshButton_OnClick, BudgetExecution.SummaryForm.InitializeComponent, BudgetExecution.SummaryForm.PopulateGridAccountFilterItems, BudgetExecution.SummaryForm.PopulateGridBocFilterItems, BudgetExecution.SummaryForm.SummaryTabPage_TabSelected, BudgetExecution.SummaryForm.UpdateAccountChart.
ChartControl BudgetExecution.SummaryForm.chartControl1
TabPageAdv BudgetExecution.SummaryForm.DatabaseTab
GroupBox BudgetExecution.SummaryForm.groupBox5
TabControlAdv BudgetExecution.SummaryForm.AccountTabControl
Referenced by BudgetExecution.SummaryForm.InitializeComponent.
TabPageAdv BudgetExecution.SummaryForm.UpdateTab
BindingNavigator BudgetExecution.SummaryForm.Navigator
Referenced by BudgetExecution.SummaryForm.InitializeComponent.
ToolStripLabel BudgetExecution.SummaryForm.toolStripLabel2
ToolStripSeparator BudgetExecution.SummaryForm.toolStripSeparator3
ToolStripButton BudgetExecution.SummaryForm.toolStripButton10
ToolStripSeparator BudgetExecution.SummaryForm.toolStripSeparator10
ToolStripTextBox BudgetExecution.SummaryForm.toolStripTextBox2
ToolStripSeparator BudgetExecution.SummaryForm.toolStripSeparator11
ToolStripButton BudgetExecution.SummaryForm.toolStripButton11
ToolStripSeparator BudgetExecution.SummaryForm.toolStripSeparator13
ToolStripButton BudgetExecution.SummaryForm.CopyButton
ToolStripSeparator BudgetExecution.SummaryForm.toolStripSeparator15
ToolStripButton BudgetExecution.SummaryForm.AddButton
ToolStripSeparator BudgetExecution.SummaryForm.toolStripSeparator18
ToolStripButton BudgetExecution.SummaryForm.ResetButton
ToolStripSeparator BudgetExecution.SummaryForm.toolStripSeparator16
MetroSetLabel BudgetExecution.SummaryForm.metroSetLabel20
MetroSetTextBox BudgetExecution.SummaryForm.BudgetLevel
MetroSetLabel BudgetExecution.SummaryForm.metroSetLabel19
MetroSetTextBox BudgetExecution.SummaryForm.ID
MetroSetLabel BudgetExecution.SummaryForm.metroSetLabel1
MetroSetLabel BudgetExecution.SummaryForm.metroSetLabel2
MetroSetTextBox BudgetExecution.SummaryForm.metroSetTextBox1
MetroSetTextBox BudgetExecution.SummaryForm.Amount
MetroSetTextBox BudgetExecution.SummaryForm.Code
MetroSetTextBox BudgetExecution.SummaryForm.BOC
MetroSetLabel BudgetExecution.SummaryForm.metroSetLabel12
MetroSetLabel BudgetExecution.SummaryForm.metroSetLabel13
MetroSetLabel BudgetExecution.SummaryForm.metroSetLabel14
MetroSetLabel BudgetExecution.SummaryForm.metroSetLabel16
MetroSetTextBox BudgetExecution.SummaryForm.RC
MetroSetTextBox BudgetExecution.SummaryForm.Fund
MetroSetLabel BudgetExecution.SummaryForm.metroSetLabel17
MetroSetLabel BudgetExecution.SummaryForm.metroSetLabel18
MetroSetTextBox BudgetExecution.SummaryForm.BFY
MetroSetTextBox BudgetExecution.SummaryForm.Org
TabPageAdv BudgetExecution.SummaryForm.tabPageAdv5
TabPageAdv BudgetExecution.SummaryForm.tabPageAdv6
GroupBox BudgetExecution.SummaryForm.groupBox1
MetroSetLabel BudgetExecution.SummaryForm.lblCount
DataGridView BudgetExecution.SummaryForm.Grid
Referenced by BudgetExecution.SummaryForm.ConfigureTextBoxBindings, BudgetExecution.SummaryForm.Form_Load, BudgetExecution.SummaryForm.InitializeComponent.
GroupBox BudgetExecution.SummaryForm.FilterGroupBox
Label BudgetExecution.SummaryForm.lblPrc
Label BudgetExecution.SummaryForm.lblBoc
Label BudgetExecution.SummaryForm.label33
MetroSetComboBox BudgetExecution.SummaryForm.GridAccountFilter
MetroSetComboBox BudgetExecution.SummaryForm.GridBocFilter
Referenced by BudgetExecution.SummaryForm.FilterDataGrid, BudgetExecution.SummaryForm.PopulateGridAccountFilterItems.
MetroSetComboBox BudgetExecution.SummaryForm.GridFundFilter
Referenced by BudgetExecution.SummaryForm.FilterDataGrid, BudgetExecution.SummaryForm.Form_Load, BudgetExecution.SummaryForm.GridFilterControl1_ItemSelected, BudgetExecution.SummaryForm.GridFilterControl2_ItemSelected, BudgetExecution.SummaryForm.GridFilterControl3_ItemSelected, BudgetExecution.SummaryForm.GridRefreshButton_OnClick, BudgetExecution.SummaryForm.PopulateGridAccountFilterItems, BudgetExecution.SummaryForm.PopulateGridBocFilterItems.
TableLayoutPanel BudgetExecution.SummaryForm.tableLayoutPanel1
Label BudgetExecution.SummaryForm.label31
Label BudgetExecution.SummaryForm.label32
Label BudgetExecution.SummaryForm.label34
Label BudgetExecution.SummaryForm.label37
Label BudgetExecution.SummaryForm.label40
Label BudgetExecution.SummaryForm.label41
Button BudgetExecution.SummaryForm.ExcelButton
Button BudgetExecution.SummaryForm.CalculatorButton
Button BudgetExecution.SummaryForm.CalendatButton
Button BudgetExecution.SummaryForm.button2
ToolStripSeparator BudgetExecution.SummaryForm.toolStripSeparator12
Button BudgetExecution.SummaryForm.button3
Button BudgetExecution.SummaryForm.button1
Button BudgetExecution.SummaryForm.button5
Button BudgetExecution.SummaryForm.button4
ToolStripButton BudgetExecution.SummaryForm.toolStripButton7
ToolStripSeparator BudgetExecution.SummaryForm.toolStripSeparator14
ToolStripButton BudgetExecution.SummaryForm.toolStripButton9
ToolStripSeparator BudgetExecution.SummaryForm.toolStripSeparator17
ToolStripButton BudgetExecution.SummaryForm.toolStripButton12
ToolStripButton BudgetExecution.SummaryForm.toolStripButton13
ToolStripSeparator BudgetExecution.SummaryForm.toolStripSeparator19
ToolStripSeparator BudgetExecution.SummaryForm.GridRefreshButton
ToolStripButton BudgetExecution.SummaryForm.toolStripButton14
ToolStripButton BudgetExecution.SummaryForm.toolStripButton15
ToolStripSeparator BudgetExecution.SummaryForm.toolStripSeparator20
ToolStripButton BudgetExecution.SummaryForm.toolStripButton16
ChartControl BudgetExecution.SummaryForm.ProjectChart
Referenced by BudgetExecution.SummaryForm.ChartFilterControl4_ItemSelected, BudgetExecution.SummaryForm.SummaryTabPage_TabSelected.
ChartControl BudgetExecution.SummaryForm.AreaChart
Referenced by BudgetExecution.SummaryForm.ChartFilterControl4_ItemSelected, BudgetExecution.SummaryForm.SummaryTabPage_TabSelected.
ChartControl BudgetExecution.SummaryForm.DivisionChart
Referenced by BudgetExecution.SummaryForm.ChartFilterControl4_ItemSelected, BudgetExecution.SummaryForm.SummaryTabPage_TabSelected.
ChartControl BudgetExecution.SummaryForm.ObjectiveChart
Referenced by BudgetExecution.SummaryForm.ChartFilterControl4_ItemSelected, BudgetExecution.SummaryForm.SummaryTabPage_TabSelected.
ChartControl BudgetExecution.SummaryForm.GoalChart
Referenced by BudgetExecution.SummaryForm.ChartFilterControl4_ItemSelected, BudgetExecution.SummaryForm.SummaryTabPage_TabSelected.
ChartControl BudgetExecution.SummaryForm.NpmChart
Referenced by BudgetExecution.SummaryForm.ChartFilterControl4_ItemSelected, BudgetExecution.SummaryForm.SummaryTabPage_TabSelected.
ChartControl BudgetExecution.SummaryForm.BocChart
Referenced by BudgetExecution.SummaryForm.ChartFilterControl4_ItemSelected, BudgetExecution.SummaryForm.SummaryTabPage_TabSelected.
ChartControl BudgetExecution.SummaryForm.FundChart
Referenced by BudgetExecution.SummaryForm.ChartFilterControl4_ItemSelected, BudgetExecution.SummaryForm.Form_Load, BudgetExecution.SummaryForm.SummaryTabPage_TabSelected.
ChartControl BudgetExecution.SummaryForm.AccountChart
Referenced by BudgetExecution.SummaryForm.SummaryTabPage_TabSelected.
BudgetExecution.SummaryForm.SummaryForm()
References BudgetExecution.SummaryForm.InitializeComponent.
BudgetExecution.SummaryForm.SummaryForm(string rc)
References BudgetExecution.SummaryForm.CurrentTabIndex, BudgetExecution.SummaryForm.DbData, BudgetExecution.SummaryForm.Division, BudgetExecution.SummaryForm.GetTabNames, BudgetExecution.SummaryForm.InitializeComponent, BudgetExecution.SummaryForm.Metric, BudgetExecution.SummaryForm.Parameter, BudgetExecution.SummaryForm.ProgramElements, BudgetExecution.SummaryForm.SummaryTabPage_TabSelected, BudgetExecution.SummaryForm.Table, BudgetExecution.SummaryForm.TabNames.
BudgetExecution.SummaryForm.SummaryForm(Source source)
References BudgetExecution.SummaryForm.CurrentTabIndex, BudgetExecution.SummaryForm.DbData, BudgetExecution.SummaryForm.GetTabNames, BudgetExecution.SummaryForm.InitializeComponent, BudgetExecution.SummaryForm.Metric, BudgetExecution.SummaryForm.ProgramElements, BudgetExecution.SummaryForm.SummaryTabPage_TabSelected, BudgetExecution.SummaryForm.Table, BudgetExecution.SummaryForm.TabNames.
void BudgetExecution.SummaryForm.Form_Load(object sender, EventArgs e)
References BudgetExecution.SummaryForm.BindingSource, BudgetExecution.SummaryForm.CalculatorButton_Click, BudgetExecution.SummaryForm.CalendatButton_Click, BudgetExecution.SummaryForm.ConfigureTextBoxBindings, BudgetExecution.SummaryForm.DbData, BudgetExecution.SummaryForm.DefineVisisbleDataColumns, BudgetExecution.SummaryForm.ExcelButton_Click, BudgetExecution.SummaryForm.FundChart, BudgetExecution.SummaryForm.Grid, BudgetExecution.SummaryForm.GridFilterControl1_ItemSelected, BudgetExecution.SummaryForm.GridFilterControl2_ItemSelected, BudgetExecution.SummaryForm.GridFundFilter, BudgetExecution.SummaryForm.GridRefreshButton_OnClick, BudgetExecution.SummaryForm.PopulateFilterBoxItems, BudgetExecution.DataBuilder.Source, BudgetExecution.SummaryForm.SummaryTabPage_TabSelected, BudgetExecution.SummaryForm.Table, BudgetExecution.SummaryForm.UpdateAccountChart.
void BudgetExecution.SummaryForm.GridFilterControl1_ItemSelected(object sender, EventArgs e)
References BudgetExecution.SummaryForm.CalculateAverage, BudgetExecution.SummaryForm.CalculateTotal, BudgetExecution.SummaryForm.GetCount, BudgetExecution.SummaryForm.GridFundFilter, BudgetExecution.SummaryForm.PopulateGridBocFilterItems.
Referenced by BudgetExecution.SummaryForm.Form_Load.
void BudgetExecution.SummaryForm.GridFilterControl2_ItemSelected(object sender, EventArgs e)
References BudgetExecution.SummaryForm.CalculateAverage, BudgetExecution.SummaryForm.CalculateTotal, BudgetExecution.SummaryForm.GetCount, BudgetExecution.SummaryForm.GridFilterControl3_ItemSelected, BudgetExecution.SummaryForm.GridFundFilter, BudgetExecution.SummaryForm.PopulateGridAccountFilterItems.
Referenced by BudgetExecution.SummaryForm.Form_Load.
void BudgetExecution.SummaryForm.GridFilterControl3_ItemSelected(object sender, EventArgs e)
References BudgetExecution.SummaryForm.CalculateTotal, BudgetExecution.SummaryForm.GetCount, BudgetExecution.SummaryForm.GridFundFilter.
Referenced by BudgetExecution.SummaryForm.GridFilterControl2_ItemSelected.
void BudgetExecution.SummaryForm.FilterDataGrid()
References BudgetExecution.SummaryForm.GridBocFilter, BudgetExecution.SummaryForm.GridFundFilter.
void BudgetExecution.SummaryForm.PopulateGridBocFilterItems()
References BudgetExecution.SummaryForm.BindingSource, BudgetExecution.SummaryForm.GridFundFilter.
Referenced by BudgetExecution.SummaryForm.GridFilterControl1_ItemSelected.
void BudgetExecution.SummaryForm.PopulateGridAccountFilterItems()
References BudgetExecution.SummaryForm.BindingSource, BudgetExecution.SummaryForm.GridBocFilter, BudgetExecution.SummaryForm.GridFundFilter.
Referenced by BudgetExecution.SummaryForm.GridFilterControl2_ItemSelected.
decimal BudgetExecution.SummaryForm.GetCount(string filter)
Referenced by BudgetExecution.SummaryForm.GridFilterControl1_ItemSelected, BudgetExecution.SummaryForm.GridFilterControl2_ItemSelected, BudgetExecution.SummaryForm.GridFilterControl3_ItemSelected.
decimal BudgetExecution.SummaryForm.GetCount(string filter1, string filter2)
References BudgetExecution.Count, BudgetExecution.Select.
void BudgetExecution.SummaryForm.PopulateFilterBoxItems(MetroSetComboBox cmbox, Field prcfilter)
Referenced by BudgetExecution.SummaryForm.Form_Load, BudgetExecution.SummaryForm.GridRefreshButton_OnClick, BudgetExecution.SummaryForm.SummaryTabPage_TabSelected.
void BudgetExecution.SummaryForm.PopulateFilterBoxItems(MetroSetComboBox cmbox, int i)
References BudgetExecution.SummaryForm.TabNames.
void BudgetExecution.SummaryForm.DefineVisisbleDataColumns(DataGridView dgv)
Referenced by BudgetExecution.SummaryForm.Form_Load.
void BudgetExecution.SummaryForm.ConfigureGridFilterButtons(FlowLayoutPanel panel, string[] list)
void BudgetExecution.SummaryForm.ConfigureTextBoxBindings()
References BudgetExecution.SummaryForm.Grid.
Referenced by BudgetExecution.SummaryForm.Form_Load.
decimal BudgetExecution.SummaryForm.CalculateAverage(string filter)
Referenced by BudgetExecution.SummaryForm.GridFilterControl1_ItemSelected, BudgetExecution.SummaryForm.GridFilterControl2_ItemSelected.
decimal BudgetExecution.SummaryForm.CalculateAverage(string filter1, string filter2)
References BudgetExecution.Average, BudgetExecution.Select.
decimal BudgetExecution.SummaryForm.CalculateTotal(string filter)
Referenced by BudgetExecution.SummaryForm.GridFilterControl1_ItemSelected, BudgetExecution.SummaryForm.GridFilterControl2_ItemSelected, BudgetExecution.SummaryForm.GridFilterControl3_ItemSelected.
decimal BudgetExecution.SummaryForm.CalculateTotal(string filter1, string filter2)
References BudgetExecution.Select.
void BudgetExecution.SummaryForm.GridRefreshButton_OnClick(object sender, EventArgs e)
References BudgetExecution.SummaryForm.BindingSource, BudgetExecution.SummaryForm.DbData, BudgetExecution.SummaryForm.GridFundFilter, BudgetExecution.SummaryForm.PopulateFilterBoxItems.
Referenced by BudgetExecution.SummaryForm.Form_Load.
string [] BudgetExecution.SummaryForm.GetTabNames()
Referenced by BudgetExecution.SummaryForm.SummaryForm.
ChartSeriesType BudgetExecution.SummaryForm.GetChartType(MetroSetComboBox ctb)
void BudgetExecution.SummaryForm.ChartFilterControl1_ItemSelected(object sender, EventArgs e)
References BudgetExecution.SummaryForm.ChartFilterControl1, BudgetExecution.SummaryForm.ChartType, BudgetExecution.SummaryForm.Expander2.
Referenced by BudgetExecution.SummaryForm.AssignChartFIlterControls.
void BudgetExecution.SummaryForm.ChartFilterControl2_ItemSelected(object sender, EventArgs e)
References BudgetExecution.SummaryForm.ChartFilterControl2, BudgetExecution.SummaryForm.Expander2, BudgetExecution.SummaryForm.Measure.
Referenced by BudgetExecution.SummaryForm.AssignChartFIlterControls.
void BudgetExecution.SummaryForm.ChartFilterControl3_ItemSelected(object sender, EventArgs e)
References BudgetExecution.SummaryForm.ChartField, BudgetExecution.SummaryForm.ChartFilter, BudgetExecution.SummaryForm.ChartFilterControl3.
Referenced by BudgetExecution.SummaryForm.AssignChartFIlterControls.
void BudgetExecution.SummaryForm.ChartFilterControl4_ItemSelected(object sender, EventArgs e)
References BudgetExecution.SummaryForm.AreaChart, BudgetExecution.SummaryForm.BocChart, BudgetExecution.SummaryForm.ChartFilter, BudgetExecution.SummaryForm.ChartFilterControl4, BudgetExecution.SummaryForm.ChartGroup, BudgetExecution.SummaryForm.ChartMainTitle, BudgetExecution.SummaryForm.ChartType, BudgetExecution.SummaryForm.CurrentTabIndex, BudgetExecution.SummaryForm.DivisionChart, BudgetExecution.SummaryForm.FundChart, BudgetExecution.SummaryForm.GoalChart, BudgetExecution.SummaryForm.Measure, BudgetExecution.SummaryForm.NpmChart, BudgetExecution.SummaryForm.ObjectiveChart, BudgetExecution.SummaryForm.ProjectChart.
Referenced by BudgetExecution.SummaryForm.AssignChartFIlterControls.
void BudgetExecution.SummaryForm.AssignChartFIlterControls(MetroSetComboBox filter1, MetroSetComboBox filter2, MetroSetComboBox filter3, MetroSetComboBox filter4)
References BudgetExecution.SummaryForm.ChartFilterControl1, BudgetExecution.SummaryForm.ChartFilterControl1_ItemSelected, BudgetExecution.SummaryForm.ChartFilterControl2, BudgetExecution.SummaryForm.ChartFilterControl2_ItemSelected, BudgetExecution.SummaryForm.ChartFilterControl3, BudgetExecution.SummaryForm.ChartFilterControl3_ItemSelected, BudgetExecution.SummaryForm.ChartFilterControl4, BudgetExecution.SummaryForm.ChartFilterControl4_ItemSelected.
Referenced by BudgetExecution.SummaryForm.SummaryTabPage_TabSelected.
void BudgetExecution.SummaryForm.AssignChartExpanders(ExpandCollapsePanel panel1, ExpandCollapsePanel panel2)
References BudgetExecution.SummaryForm.Expander1, BudgetExecution.SummaryForm.Expander2.
Referenced by BudgetExecution.SummaryForm.SummaryTabPage_TabSelected.
void BudgetExecution.SummaryForm.Expander_Click(object sender, EventArgs e)
References BudgetExecution.SummaryForm.AreaExpander2, BudgetExecution.SummaryForm.BocExpander2, BudgetExecution.SummaryForm.CurrentTabIndex, BudgetExecution.SummaryForm.FundExpander2, BudgetExecution.SummaryForm.GoalExpander2, BudgetExecution.SummaryForm.NpmExpander2, BudgetExecution.SummaryForm.ObjectiveExpander2, BudgetExecution.SummaryForm.ProjectExpander2.
void BudgetExecution.SummaryForm.SummaryTabPage_TabSelected(object sender, EventArgs e)
References BudgetExecution.SummaryForm.AccountChart, BudgetExecution.SummaryForm.AreaChart, BudgetExecution.SummaryForm.AreaExpander1, BudgetExecution.SummaryForm.AreaExpander2, BudgetExecution.SummaryForm.AreaFilter1, BudgetExecution.SummaryForm.AreaFilter2, BudgetExecution.SummaryForm.AreaFilter3, BudgetExecution.SummaryForm.AreaFilter4, BudgetExecution.SummaryForm.AssignChartExpanders, BudgetExecution.SummaryForm.AssignChartFIlterControls, BudgetExecution.SummaryForm.BindingSource, BudgetExecution.SummaryForm.BocChart, BudgetExecution.SummaryForm.BocExpander1, BudgetExecution.SummaryForm.BocExpander2, BudgetExecution.SummaryForm.BocFilter1, BudgetExecution.SummaryForm.BocFilter2, BudgetExecution.SummaryForm.BocFilter3, BudgetExecution.SummaryForm.BocFilter4, BudgetExecution.SummaryForm.ChartFilterControl3, BudgetExecution.SummaryForm.ChartMainTitle, BudgetExecution.SummaryForm.CurrentTabIndex, BudgetExecution.SummaryForm.DbData, BudgetExecution.SummaryForm.DbRow, BudgetExecution.SummaryForm.DivisionChart, BudgetExecution.SummaryForm.DivisionExpander1, BudgetExecution.SummaryForm.DivisionExpander2, BudgetExecution.SummaryForm.DivisionFilter1, BudgetExecution.SummaryForm.DivisionFilter2, BudgetExecution.SummaryForm.DivisionFilter3, BudgetExecution.SummaryForm.DivisionFilter4, BudgetExecution.SummaryForm.FundChart, BudgetExecution.SummaryForm.FundExpander1, BudgetExecution.SummaryForm.FundExpander2, BudgetExecution.SummaryForm.FundFilter1, BudgetExecution.SummaryForm.FundFilter2, BudgetExecution.SummaryForm.FundFilter3, BudgetExecution.SummaryForm.FundFilter4, BudgetExecution.SummaryForm.GoalChart, BudgetExecution.SummaryForm.GoalExpander1, BudgetExecution.SummaryForm.GoalExpander2, BudgetExecution.SummaryForm.GoalFilter1, BudgetExecution.SummaryForm.GoalFilter2, BudgetExecution.SummaryForm.GoalFilter3, BudgetExecution.SummaryForm.GoalFilter4, BudgetExecution.SummaryForm.NpmChart, BudgetExecution.SummaryForm.NpmExpander1, BudgetExecution.SummaryForm.NpmExpander2, BudgetExecution.SummaryForm.NpmFilter1, BudgetExecution.SummaryForm.NpmFilter2, BudgetExecution.SummaryForm.NpmFilter3, BudgetExecution.SummaryForm.NpmFilter4, BudgetExecution.SummaryForm.ObjectiveChart, BudgetExecution.SummaryForm.ObjectiveExpander1, BudgetExecution.SummaryForm.ObjectiveExpander2, BudgetExecution.SummaryForm.ObjectiveFilter1, BudgetExecution.SummaryForm.ObjectiveFilter2, BudgetExecution.SummaryForm.ObjectiveFilter3, BudgetExecution.SummaryForm.ObjectiveFilter4, BudgetExecution.SummaryForm.PopulateFilterBoxItems, BudgetExecution.ProgramProjectName, BudgetExecution.SummaryForm.ProjectChart, BudgetExecution.SummaryForm.ProjectExpander1, BudgetExecution.SummaryForm.ProjectExpander2, BudgetExecution.SummaryForm.ProjectFilter1, BudgetExecution.SummaryForm.ProjectFilter2, BudgetExecution.SummaryForm.ProjectFilter3, BudgetExecution.SummaryForm.ProjectFilter4, BudgetExecution.DataBuilder.Source, BudgetExecution.SummaryForm.SummaryTabControl, BudgetExecution.SummaryForm.Table, BudgetExecution.DataBuilder.Total.
Referenced by BudgetExecution.SummaryForm.Form_Load, BudgetExecution.SummaryForm.SummaryForm.
string [] BudgetExecution.SummaryForm.GetTitle(TabControlAdv tab, MetroSetComboBox filter)
References BudgetExecution.SummaryForm.CurrentTabIndex.
string [] BudgetExecution.SummaryForm.GetTitle(TabControlAdv tab, MetroSetComboBox filter1, MetroSetComboBox filter2, MetroSetComboBox filter3)
References BudgetExecution.SummaryForm.CurrentTabIndex.
Dictionary<string, object> BudgetExecution.SummaryForm.GetSelectedRowDictionary(DataGridView dgv)
void BudgetExecution.SummaryForm.TabPageAdv7_Click(object sender, EventArgs e)
void BudgetExecution.SummaryForm.CalendatButton_Click(object sender, EventArgs e)
Referenced by BudgetExecution.SummaryForm.Form_Load.
void BudgetExecution.SummaryForm.CalculatorButton_Click(object sender, EventArgs e)
Referenced by BudgetExecution.SummaryForm.Form_Load.
void BudgetExecution.SummaryForm.ExcelButton_Click(object sender, EventArgs e)
Referenced by BudgetExecution.SummaryForm.Form_Load.
void BudgetExecution.SummaryForm.ToolStripSeparator16_Click(object sender, EventArgs e)
void BudgetExecution.SummaryForm.MetroSetLabel9_Click(object sender, EventArgs e)
void BudgetExecution.SummaryForm.LblCount_Click(object sender, EventArgs e)
void BudgetExecution.SummaryForm.AddButton_OnClick(object sender, EventArgs e)
void BudgetExecution.SummaryForm.CopyButton_OnClick(object sender, EventArgs e)
References BudgetExecution.SummaryForm.BindingSource.
void BudgetExecution.SummaryForm.Grid_OnDoubleClick(object sender, EventArgs e)
References BudgetExecution.SummaryForm.BindingSource.
void BudgetExecution.SummaryForm.ReprogramButton_OnClick(object sender, EventArgs e)
void BudgetExecution.SummaryForm.UpdateAccountChart(object sender, EventArgs e)
References BudgetExecution.SummaryForm.BindingSource, BudgetExecution.SummaryForm.DbRow, BudgetExecution.SummaryForm.Table.
Referenced by BudgetExecution.SummaryForm.Form_Load.
void BudgetExecution.SummaryForm.AccountToolsButton_OnClick(object sender, EventArgs e)
void BudgetExecution.SummaryForm.AccountChart_Click(object sender, EventArgs e)
void BudgetExecution.SummaryForm.Button4_Click(object sender, EventArgs e)
void BudgetExecution.SummaryForm.button5_Click(object sender, EventArgs e)
void BudgetExecution.SummaryForm.InitializeComponent()
Required method for Designer support - do not modify the contents of this method with the code editor.
References BudgetExecution.SummaryForm.AccountTabControl, BudgetExecution.SummaryForm.BindingSource, BudgetExecution.D, BudgetExecution.F, BudgetExecution.SummaryForm.Grid, BudgetExecution.SummaryForm.MiniTabControl1, BudgetExecution.SummaryForm.Navigator, BudgetExecution.SummaryForm.SummaryTabControl.
Referenced by BudgetExecution.SummaryForm.SummaryForm.
override void BudgetExecution.SummaryForm.Dispose(bool disposing)
Clean up any resources being used.
disposing true if managed resources should be disposed; otherwise, false.
References BudgetExecution.SummaryForm.components.