BudgetExecution::DivisionAuthority
string BudgetExecution.DivisionAuthority.FiscalYear
Referenced by BudgetExecution.DocInfo.GetDocmumentInfo.
RC BudgetExecution.DivisionAuthority.RC
Referenced by BudgetExecution.DivisionAuthority.DivisionAuthority.
Org BudgetExecution.DivisionAuthority.Org
Referenced by BudgetExecution.DivisionAuthority.DivisionAuthority.
DataRow [] BudgetExecution.DivisionAuthority.DataRecords
Referenced by BudgetExecution.DivisionAuthority.DivisionAuthority.
PRC [] BudgetExecution.DivisionAuthority.PrcAllocation
Referenced by BudgetExecution.DivisionAuthority.DivisionAuthority.
DataBuilder BudgetExecution.DivisionAuthority.DbData
Referenced by BudgetExecution.DivisionAuthority.DivisionAuthority.
PrcMetric BudgetExecution.DivisionAuthority.Metric
Referenced by BudgetExecution.DivisionAuthority.DivisionAuthority.
DataTable BudgetExecution.DivisionAuthority.DbTable
Referenced by BudgetExecution.DivisionAuthority.DivisionAuthority.
Dictionary<string, string[]> BudgetExecution.DivisionAuthority.ProgramElements
Referenced by BudgetExecution.DivisionAuthority.DivisionAuthority.
decimal BudgetExecution.DivisionAuthority.Amount
decimal BudgetExecution.DivisionAuthority.Total
Referenced by BudgetExecution.DivisionAuthority.DivisionAuthority.
int BudgetExecution.DivisionAuthority.Count
Referenced by BudgetExecution.DivisionAuthority.DivisionAuthority.
decimal BudgetExecution.DivisionAuthority.Average
Referenced by BudgetExecution.DivisionAuthority.DivisionAuthority.
DataFilter BudgetExecution.DivisionAuthority.TableFilter
Referenced by BudgetExecution.DivisionAuthority.DivisionAuthority.
Dictionary<string, decimal> BudgetExecution.DivisionAuthority.ProgramData
FTE [] BudgetExecution.DivisionAuthority.FTE
Dictionary<string, decimal> BudgetExecution.DivisionAuthority.BocData
Referenced by BudgetExecution.DivisionAuthority.DivisionAuthority.
Dictionary<string, decimal> BudgetExecution.DivisionAuthority.FundData
Referenced by BudgetExecution.DivisionAuthority.DivisionAuthority.
Dictionary<string, decimal> BudgetExecution.DivisionAuthority.GoalData
Referenced by BudgetExecution.DivisionAuthority.DivisionAuthority.
Dictionary<string, decimal> BudgetExecution.DivisionAuthority.NpmData
Referenced by BudgetExecution.DivisionAuthority.DivisionAuthority.
Dictionary<string, decimal> BudgetExecution.DivisionAuthority.ProgramAreaData
Referenced by BudgetExecution.DivisionAuthority.DivisionAuthority.
Dictionary<string, decimal> BudgetExecution.DivisionAuthority.ProjectData
Referenced by BudgetExecution.DivisionAuthority.DivisionAuthority.
BudgetExecution.DivisionAuthority.DivisionAuthority()
References BudgetExecution.DivisionAuthority.Average, BudgetExecution.DivisionAuthority.BocData, BudgetExecution.DivisionAuthority.Count, BudgetExecution.DataFilter, BudgetExecution.DivisionAuthority.DataRecords, BudgetExecution.DivisionAuthority.DbData, BudgetExecution.DivisionAuthority.DbTable, BudgetExecution.DataBuilder.DbTable, BudgetExecution.DataBuilder.FilterTable, BudgetExecution.DivisionAuthority.FundData, BudgetExecution.DivisionAuthority.GetFTE, BudgetExecution.DivisionAuthority.GetPrcArray, BudgetExecution.DivisionAuthority.GetProgramElements, BudgetExecution.DivisionAuthority.GoalData, BudgetExecution.DivisionAuthority.Metric, BudgetExecution.DivisionAuthority.NpmData, BudgetExecution.DivisionAuthority.PrcAllocation, BudgetExecution.DivisionAuthority.ProgramAreaData, BudgetExecution.DivisionAuthority.ProgramElements, BudgetExecution.DivisionAuthority.ProjectData, BudgetExecution.DivisionAuthority.TableFilter, BudgetExecution.DivisionAuthority.Total.
BudgetExecution.DivisionAuthority.DivisionAuthority(string rc)
References BudgetExecution.RC.Code, BudgetExecution.DivisionAuthority.DbData, BudgetExecution.DivisionAuthority.Org, BudgetExecution.DivisionAuthority.RC.
decimal BudgetExecution.DivisionAuthority.GetAverage(DataTable table)
References BudgetExecution.Average, BudgetExecution.M, BudgetExecution.Select.
string [] BudgetExecution.DivisionAuthority.GetCodes(DataTable table, string column)
References BudgetExecution.Select.
int BudgetExecution.DivisionAuthority.GetCount(DataTable table)
References BudgetExecution.Select.
Tuple<DataTable, PRC[], decimal, int> BudgetExecution.DivisionAuthority.GetDataValues(DataTable table, string column, string filter)
decimal [] BudgetExecution.DivisionAuthority.GetMetrics(DataTable table)
PRC [] BudgetExecution.DivisionAuthority.GetPrcArray(DataTable table)
References BudgetExecution.PRC, BudgetExecution.Select.
Referenced by BudgetExecution.DivisionAuthority.DivisionAuthority.
Dictionary<string, string[]> BudgetExecution.DivisionAuthority.GetProgramElements(DataTable table)
Referenced by BudgetExecution.DivisionAuthority.DivisionAuthority.
decimal BudgetExecution.DivisionAuthority.GetTotal(DataTable table)
References BudgetExecution.M.
FTE [] BudgetExecution.DivisionAuthority.GetFTE(DataTable table)
References BudgetExecution.FTE.
Referenced by BudgetExecution.DivisionAuthority.DivisionAuthority.