BudgetExecution
FileExt
FundCode
Function
Goal
HQ
Net
Objective
Numeric
Command
Field
Provider
Source
Stat
TransferType
typedef Syncfusion Windows Forms MetroForm BudgetExecution::MetroForm
typedef Microsoft Office Interop Excel BudgetExecution::Excel
using BudgetExecution.Workbook = typedef Microsoft.Office.Interop.Excel.Workbook
using BudgetExecution.Worksheet = typedef Microsoft.Office.Interop.Excel.Worksheet
delegate double [] BudgetExecution.Calculator(DataTable table)
delegate DataTable BudgetExecution.DataFilter(DataTable table, Field prcfilter, string filter)
Referenced by BudgetExecution.DivisionAuthority.DivisionAuthority, BudgetExecution.SQLiteData.SQLiteData.
delegate string [] BudgetExecution.ColumnFilter(DataTable table, string filter)
Referenced by BudgetExecution.SQLiteData.SQLiteData.
delegate ChartControl BudgetExecution.GetChart(ChartControl chart, string title, Dictionary< string, double > data)
Referenced by BudgetExecution.MainForm.MainForm.