CREATE TABLE IF NOT EXISTS `P8` (
	`ID`	INTEGER NOT NULL UNIQUE,
	`BudgetLevel`	TEXT,
	`RPIO`	TEXT,
	`BFY`	TEXT,
	`Fund`	TEXT,
	`FundName`	TEXT,
	`BOC`	TEXT,
	`BocName`	TEXT,
	`Org`	TEXT,
	`RC`	TEXT,
	`DivisionName`	TEXT,
	`Code`	TEXT,
	`Amount`	NUMERIC,
	`SubProject`	TEXT,
	`NPM`	TEXT,
	`NpmCode`	TEXT,
	`ProgramProjectCode`	TEXT,
	`ProgramProjectName`	TEXT,
	`ProgramArea`	TEXT,
	`ProgramAreaName`	TEXT,
	`Goal`	TEXT,
	`GoalName`	TEXT,
	`Objective`	TEXT,
	`ObjectiveName`	TEXT,
	PRIMARY KEY(`ID`),
	FOREIGN KEY(`ID`) REFERENCES `P6`,
	FOREIGN KEY(`BFY`) REFERENCES `P7`,
	FOREIGN KEY(`Fund`) REFERENCES `P7`,
	FOREIGN KEY(`BOC`) REFERENCES `P7`,
	FOREIGN KEY(`Org`) REFERENCES `P7`,
	FOREIGN KEY(`Code`) REFERENCES `P7`
);