//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ninja
{
    using System;
    using System.Collections.Generic;
    
    public partial class A6
    {
        public long Id { get; set; }
        public string BFY { get; set; }
        public string RPIO { get; set; }
        public string Fund { get; set; }
        public string FundName { get; set; }
        public string NPM { get; set; }
        public string NpmName { get; set; }
        public string AH { get; set; }
        public string AhName { get; set; }
        public string AHRC { get; set; }
        public string AhrcName { get; set; }
        public string Org { get; set; }
        public string OrgName { get; set; }
        public string PrcOrgCode { get; set; }
        public string PrcOrgName { get; set; }
        public string Code { get; set; }
        public string PrgramProjectCode { get; set; }
        public string ProgramProjectName { get; set; }
        public string RpioActivityCode { get; set; }
        public string ProgramArea { get; set; }
        public string ProgramAreaName { get; set; }
        public string BOC { get; set; }
        public string BocName { get; set; }
        public string FOC { get; set; }
        public string FocName { get; set; }
    }
}
