//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ninja
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class R6Entities1 : DbContext
    {
        public R6Entities1()
            : base("name=R6Entities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<A6> A6 { get; set; }
        public virtual DbSet<B6> B6 { get; set; }
        public virtual DbSet<F6> F6 { get; set; }
        public virtual DbSet<P6> P6 { get; set; }
        public virtual DbSet<P7> P7 { get; set; }
        public virtual DbSet<P8> P8 { get; set; }
    }
}
