CREATE TABLE "Obligations" ( 
    "ID" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE, 
    "BFY" TEXT, 
    "RPIO" TEXT DEFAULT 06, 
    "Fund" TEXT, 
    "FundName" TEXT, 
    "AH" TEXT DEFAULT 06, 
    "Org" TEXT, 
    "OrgName" TEXT, 
    "RC" TEXT, 
    "DivisionName" TEXT, 
    "Code" TEXT, 
    "ProgramProjectCode" TEXT, 
    "ProgramProjectName" TEXT, 
    "SubProject" TEXT, 
    "ProgramArea" TEXT, 
    "ProgramAreaName" TEXT, 
    "DCN" TEXT, 
    "BOC" TEXT, 
    "BocName" TEXT, 
    "FOC" TEXT, 
    "FocName" TEXT, 
    "System" TEXT, 
    "PurchaseRequest" TEXT, 
    "SiteProjectCode" TEXT, 
    "SiteProjectName" TEXT, 
    "CommitmentDate" NUMERIC DEFAULT 0, 
    "Obligations" NUMERIC DEFAULT 0 );