USE [C:\USERS\TERRY\DOCUMENTS\VISUAL STUDIO 2017\PROJECTS\BUDGETEXECUTION\NINJA\SQLSERVER\R6.MDF]
GO

/****** Object:  Table [dbo].[D6]    Script Date: 4/17/2018 10:24:15 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[D6](
	[Id] [text] NULL,
	[RC] [text] NULL,
	[Name] [text] NULL,
	[Org] [text] NULL,
	[Code] [text] NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

