CREATE TABLE "Obligations" (
	"ID"	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	"Fund"	TEXT,
	"FundName"	TEXT,
	"NPM"	TEXT,
	"NpmName"	TEXT,
	"BFY"	TEXT,
	"System"	TEXT,
	"RC"	TEXT,
	"Division"	TEXT,
	"Division"	TEXT,
	"Code"	TEXT,
	"ProgramArea"	TEXT,
	"ProgramAreaName"	TEXT,
	"RpioActivityCode"	TEXT,
	"ProgramProjectName"	TEXT,
	"ProgramProjectCode"	TEXT,
	"BOC"	TEXT,
	"BocName"	TEXT,
	"FOC"	TEXT,
	"FocName"	TEXT,
	"PurchaseRequest"	TEXT,
	"Column23"	TEXT,
	"DocType"	TEXT,
	"DCN"	TEXT,
	"TransactionNumber"	TEXT,
	"SiteProjectName"	TEXT,
	"SiteName"	TEXT,
	"CommitmentDate"	TEXT,
	"RecordDate"	TEXT,
	"Commitments"	NUMERIC,
	"Obligations"	NUMERIC
);