CREATE TABLE "PRC" (
	"ID" INTEGER NOT NULL UNIQUE PRIMARY KEY AUTOINCREMENT,
	"BudgetLevel"	TEXT,
	"RPIO"	TEXT DEFAULT 06,
	"BFY"	TEXT,
	"Fund"	TEXT,
	"FundName"	TEXT,
	"BOC"	TEXT,
	"BocName"	TEXT,
	"Org"	TEXT,
	"RC"	TEXT,
	"DivisionName"	TEXT,
	"Code"	TEXT,
	"Amount"	NUMERIC,
	"SubProject"	TEXT,
	"NPM"	TEXT,
	"NpmCode"	TEXT,
	"ProgramProjectCode"	TEXT,
	"ProgramProjectName"	TEXT,
	"ProgramArea"	TEXT,
	"ProgramAreaName"	TEXT,
	"Goal"	TEXT,
	"GoalName"	TEXT,
	"Objective"	TEXT,
	"ObjectiveName"	TEXT
);