CREATE TABLE `R6` (
	`ID`	INTEGER NOT NULL UNIQUE,
	`BudgetLevel`	TEXT,
	`RPIO`	TEXT,
	`BFY`	TEXT,
	`Fund`	TEXT,
	`FundName`	TEXT,
	`BOC`	TEXT,
	`BocName`	TEXT,
	`Org`	TEXT,
	`RC`	TEXT,
	`DivisionName`	TEXT,
	`Code`	TEXT,
	`Amount`	NUMERIC,
	`SubProject`	TEXT,
	`NPM`	TEXT,
	`NpmCode`	TEXT,
	`ProgramProjectCode`	TEXT,
	`ProgramProjectName`	TEXT,
	`ProgramArea`	TEXT,
	`ProgramAreaName`	TEXT,
	`Goal`	TEXT,
	`GoalName`	TEXT,
	`Objective`	TEXT,
	`ObjectiveName`	TEXT,
	FOREIGN KEY(`ID`) REFERENCES `PRC`(`ID`),
	PRIMARY KEY(`ID`)
);