
CREATE TABLE "EJ" ( "ID" INTEGER NOT NULL UNIQUE, "BudgetLevel" TEXT DEFAULT 8, "RPIO" TEXT DEFAULT 06, "BFY" TEXT, "Fund" TEXT, "FundName" TEXT, "BOC" TEXT, "BocName" TEXT, "Org" TEXT DEFAULT 06, "RC" TEXT DEFAULT '06F', "DivisionName" TEXT, "Code" TEXT, "Amount" NUMERIC, "SubProject" TEXT, "NPM" TEXT, "NpmCode" TEXT, "ProgramProjectCode" TEXT, "ProgramProjectName" TEXT, "ProgramArea" TEXT, "ProgramAreaName" TEXT, "Goal" TEXT, "GoalName" TEXT, "Objective" TEXT, "ObjectiveName" TEXT, PRIMARY KEY("ID"), FOREIGN KEY("ID") REFERENCES "PRC"("ID") );
CREATE TABLE "EN" ( "ID" INTEGER NOT NULL UNIQUE, "BudgetLevel" TEXT DEFAULT 8, "RPIO" TEXT DEFAULT 06, "BFY" TEXT, "Fund" TEXT, "FundName" TEXT, "BOC" TEXT, "BocName" TEXT, "Org" TEXT DEFAULT 06, "RC" TEXT DEFAULT '06M', "DivisionName" TEXT, "Code" TEXT, "Amount" NUMERIC, "SubProject" TEXT, "NPM" TEXT, "NpmCode" TEXT, "ProgramProjectCode" TEXT, "ProgramProjectName" TEXT, "ProgramArea" TEXT, "ProgramAreaName" TEXT, "Goal" TEXT, "GoalName" TEXT, "Objective" TEXT, "ObjectiveName" TEXT, PRIMARY KEY("ID"), FOREIGN KEY("ID") REFERENCES "PRC"("ID") );
CREATE TABLE "MD" ( "ID" INTEGER NOT NULL UNIQUE, "BudgetLevel" TEXT DEFAULT 8, "RPIO" TEXT DEFAULT 06, "BFY" TEXT, "Fund" TEXT, "FundName" TEXT, "BOC" TEXT, "BocName" TEXT, "Org" TEXT, "RC" TEXT DEFAULT '06C', "DivisionName" TEXT, "Code" TEXT, "Amount" NUMERIC, "SubProject" TEXT, "NPM" TEXT, "NpmCode" TEXT, "ProgramProjectCode" TEXT, "ProgramProjectName" TEXT, "ProgramArea" TEXT, "ProgramAreaName" TEXT, "Goal" TEXT, "GoalName" TEXT, "Objective" TEXT, "ObjectiveName" TEXT, FOREIGN KEY("ID") REFERENCES "PRC"("ID"), PRIMARY KEY("ID") );
CREATE TABLE "MDR" ( "ID" INTEGER NOT NULL UNIQUE, "BudgetLevel" TEXT DEFAULT 8, "RPIO" TEXT DEFAULT 06, "BFY" TEXT, "Fund" TEXT, "FundName" TEXT, "BOC" TEXT, "BocName" TEXT, "Org" TEXT, "RC" TEXT DEFAULT '0R', "DivisionName" TEXT, "Code" TEXT, "Amount" NUMERIC, "SubProject" TEXT, "NPM" TEXT, "NpmCode" TEXT, "ProgramProjectCode" TEXT, "ProgramProjectName" TEXT, "ProgramArea" TEXT, "ProgramAreaName" TEXT, "Goal" TEXT, "GoalName" TEXT, "Objective" TEXT, "ObjectiveName" TEXT, FOREIGN KEY("ID") REFERENCES "PRC"("ID"), PRIMARY KEY("ID") );
CREATE TABLE "MM" ( "ID" INTEGER NOT NULL UNIQUE, "BudgetLevel" TEXT DEFAULT 8, "RPIO" TEXT DEFAULT 06, "BFY" TEXT, "Fund" TEXT, "FundName" TEXT, "BOC" TEXT, "BocName" TEXT, "Org" TEXT, "RC" TEXT DEFAULT '06J', "DivisionName" TEXT, "Code" TEXT, "Amount" NUMERIC, "SubProject" TEXT, "NPM" TEXT, "NpmCode" TEXT, "ProgramProjectCode" TEXT, "ProgramProjectName" TEXT, "ProgramArea" TEXT, "ProgramAreaName" TEXT, "Goal" TEXT, "GoalName" TEXT, "Objective" TEXT, "ObjectiveName" TEXT, FOREIGN KEY("ID") REFERENCES "PRC"("ID"), PRIMARY KEY("ID") );
CREATE TABLE "RA" ( "ID" INTEGER NOT NULL UNIQUE, "BudgetLevel" TEXT DEFAULT 8, "RPIO" TEXT DEFAULT 06, "BFY" TEXT, "Fund" TEXT, "FundName" TEXT, "BOC" TEXT, "BocName" TEXT, "Org" TEXT DEFAULT 06, "RC" TEXT DEFAULT '06A', "DivisionName" TEXT, "Code" TEXT, "Amount" NUMERIC, "SubProject" TEXT, "NPM" TEXT, "NpmCode" TEXT, "ProgramProjectCode" TEXT, "ProgramProjectName" TEXT, "ProgramArea" TEXT, "ProgramAreaName" TEXT, "Goal" TEXT, "GoalName" TEXT, "Objective" TEXT, "ObjectiveName" TEXT, FOREIGN KEY("ID") REFERENCES "PRC"("ID"), PRIMARY KEY("ID") )
CREATE TABLE "SF" ( "ID" INTEGER NOT NULL UNIQUE, "BudgetLevel" TEXT DEFAULT 8, "RPIO" TEXT DEFAULT 06, "BFY" TEXT, "Fund" TEXT, "FundName" TEXT, "BOC" TEXT, "BocName" TEXT, "Org" TEXT, "RC" TEXT DEFAULT '06L', "DivisionName" TEXT, "Code" TEXT, "Amount" NUMERIC, "SubProject" TEXT, "NPM" TEXT, "NpmCode" TEXT, "ProgramProjectCode" TEXT, "ProgramProjectName" TEXT, "ProgramArea" TEXT, "ProgramAreaName" TEXT, "Goal" TEXT, "GoalName" TEXT, "Objective" TEXT, "ObjectiveName" TEXT, FOREIGN KEY("ID") REFERENCES "PRC"("ID"), PRIMARY KEY("ID") );
CREATE TABLE "WCF" ( "ID" INTEGER NOT NULL UNIQUE, "BudgetLevel" TEXT DEFAULT 8, "RPIO" TEXT DEFAULT 06, "BFY" TEXT, "Fund" TEXT, "FundName" TEXT, "BOC" TEXT, "BocName" TEXT, "Org" TEXT, "RC" TEXT DEFAULT '06G', "DivisionName" TEXT, "Code" TEXT, "Amount" NUMERIC, "SubProject" TEXT, "NPM" TEXT, "NpmCode" TEXT, "ProgramProjectCode" TEXT, "ProgramProjectName" TEXT, "ProgramArea" TEXT, "ProgramAreaName" TEXT, "Goal" TEXT, "GoalName" TEXT, "Objective" TEXT, "ObjectiveName" TEXT, FOREIGN KEY("ID") REFERENCES "PRC"("ID"), PRIMARY KEY("ID") );
CREATE TABLE "WQ" ( "ID" INTEGER NOT NULL UNIQUE, "BudgetLevel" TEXT DEFAULT 8, "RPIO" TEXT DEFAULT 06, "BFY" TEXT, "Fund" TEXT, "FundName" TEXT, "BOC" TEXT, "BocName" TEXT, "Org" TEXT, "RC" TEXT DEFAULT '06K', "DivisionName" TEXT, "Code" TEXT, "Amount" NUMERIC, "SubProject" TEXT, "NPM" TEXT, "NpmCode" TEXT, "ProgramProjectCode" TEXT, "ProgramProjectName" TEXT, "ProgramArea" TEXT, "ProgramAreaName" TEXT, "Goal" TEXT, "GoalName" TEXT, "Objective" TEXT, "ObjectiveName" TEXT, FOREIGN KEY("ID") REFERENCES "PRC"("ID"), PRIMARY KEY("ID") );
CREATE TABLE "WSA" ( "ID" INTEGER NOT NULL UNIQUE, "BudgetLevel" TEXT DEFAULT 8, "RPIO" TEXT DEFAULT 06, "BFY" TEXT, "Fund" TEXT, "FundName" TEXT, "BOC" TEXT, "BocName" TEXT, "Org" TEXT, "RC" TEXT DEFAULT '06N', "DivisionName" TEXT, "Code" TEXT, "Amount" NUMERIC, "SubProject" TEXT, "NPM" TEXT, "NpmCode" TEXT, "ProgramProjectCode" TEXT, "ProgramProjectName" TEXT, "ProgramArea" TEXT, "ProgramAreaName" TEXT, "Goal" TEXT, "GoalName" TEXT, "Objective" TEXT, "ObjectiveName" TEXT, FOREIGN KEY("ID") REFERENCES "PRC"("ID"), PRIMARY KEY("ID") );
CREATE TABLE "XA" ( "ID" INTEGER NOT NULL UNIQUE, "BudgetLevel" TEXT DEFAULT 8, "RPIO" TEXT DEFAULT 06, "BFY" TEXT, "Fund" TEXT, "FundName" TEXT, "BOC" TEXT, "BocName" TEXT, "Org" TEXT, "RC" TEXT DEFAULT '06X', "DivisionName" TEXT, "Code" TEXT, "Amount" TEXT, "SubProject" TEXT, "NPM" TEXT, "NpmCode" TEXT, "ProgramProjectCode" TEXT, "ProgramProjectName" TEXT, "ProgramArea" TEXT, "ProgramAreaName" TEXT, "Goal" TEXT, "GoalName" TEXT, "Objective" TEXT, "ObjectiveName" TEXT, FOREIGN KEY("ID") REFERENCES "PRC"("ID"), PRIMARY KEY("ID") );
