USE [C:\USERS\TERRY\DOCUMENTS\VISUAL STUDIO 2017\PROJECTS\BUDGETEXECUTION\NINJA\DATABASE\SQLSERVER\R6.MDF]
GO

/****** Object: View [dbo].[CONTRACTS] Script Date: 10/6/2018 1:52:09 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE VIEW "CONTRACTS" 
AS SELECT * 
FROM PRC 
WHERE BOC = '37';
