//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BudgetExecution.resources
{
    /// <summary>
    /// A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ControlImages
    {
        /// <summary>
        /// Defines the resourceMan
        /// </summary>
        private static global::System.Resources.ResourceManager resourceMan;

        /// <summary>
        /// Defines the resourceCulture
        /// </summary>
        private static global::System.Globalization.CultureInfo resourceCulture;

        /// <summary>
        /// Initializes a new instance of the <see cref="ControlImages"/> class.
        /// </summary>
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ControlImages()
        {
        }

        /// <summary>
        /// Gets the ResourceManager
        /// Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if(object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BudgetExecution.resources.ControlImages", typeof(ControlImages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        /// Gets or sets the Culture
        /// Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        /// <summary>
        /// Gets the _123
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _123
        {
            get
            {
                object obj = ResourceManager.GetObject("_123", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        /// Gets the _2000px_Applications_database_svg
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _2000px_Applications_database_svg
        {
            get
            {
                object obj = ResourceManager.GetObject("_2000px_Applications_database_svg", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        /// Gets the Access_New_Wf
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Access_New_Wf
        {
            get
            {
                object obj = ResourceManager.GetObject("Access_New_Wf", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        /// Gets the Addition
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Addition
        {
            get
            {
                object obj = ResourceManager.GetObject("Addition", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        /// Gets the Aim1_WF
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Aim1_WF
        {
            get
            {
                object obj = ResourceManager.GetObject("Aim1_WF", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        /// Gets the Arrow_Left___03
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Arrow_Left___03
        {
            get
            {
                object obj = ResourceManager.GetObject("Arrow_Left___03", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        /// Gets the Arrow_right
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Arrow_right
        {
            get
            {
                object obj = ResourceManager.GetObject("Arrow_right", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        /// Gets the Command_Undo_WF_1_
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Command_Undo_WF_1_
        {
            get
            {
                object obj = ResourceManager.GetObject("Command_Undo_WF_1_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        /// Gets the Data_Export
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Data_Export
        {
            get
            {
                object obj = ResourceManager.GetObject("Data_Export", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        /// Gets the database__8_
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap database__8_
        {
            get
            {
                object obj = ResourceManager.GetObject("database__8_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        /// Gets the Database_WF_1_
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Database_WF_1_
        {
            get
            {
                object obj = ResourceManager.GetObject("Database_WF_1_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        /// Gets the database02
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap database02
        {
            get
            {
                object obj = ResourceManager.GetObject("database02", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        /// Gets the Diagram
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Diagram
        {
            get
            {
                object obj = ResourceManager.GetObject("Diagram", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        /// Gets the epadarklogoicon
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap epadarklogoicon
        {
            get
            {
                object obj = ResourceManager.GetObject("epadarklogoicon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        /// Gets the Excel_Export_1_
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Excel_Export_1_
        {
            get
            {
                object obj = ResourceManager.GetObject("Excel_Export_1_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        /// Gets the Excel_Import_and_Export_1_
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Excel_Import_and_Export_1_
        {
            get
            {
                object obj = ResourceManager.GetObject("Excel_Import_and_Export_1_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        /// Gets the Excel_Online
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Excel_Online
        {
            get
            {
                object obj = ResourceManager.GetObject("Excel_Online", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        /// Gets the Exchange___02_1_
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Exchange___02_1_
        {
            get
            {
                object obj = ResourceManager.GetObject("Exchange___02_1_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        /// Gets the Formula_Support_1_
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Formula_Support_1_
        {
            get
            {
                object obj = ResourceManager.GetObject("Formula_Support_1_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        /// Gets the Library_Books
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Library_Books
        {
            get
            {
                object obj = ResourceManager.GetObject("Library_Books", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        /// Gets the Money_Transfer
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Money_Transfer
        {
            get
            {
                object obj = ResourceManager.GetObject("Money_Transfer", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        /// Gets the Organization_WF
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Organization_WF
        {
            get
            {
                object obj = ResourceManager.GetObject("Organization_WF", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        /// Gets the Overview_810x301
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Overview_810x301
        {
            get
            {
                object obj = ResourceManager.GetObject("Overview_810x301", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        /// Gets the Project_Plan_01_WF
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Project_Plan_01_WF
        {
            get
            {
                object obj = ResourceManager.GetObject("Project_Plan_01_WF", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        /// Gets the qm_icon
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap qm_icon
        {
            get
            {
                object obj = ResourceManager.GetObject("qm_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        /// Gets the Statistical_Analysis
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Statistical_Analysis
        {
            get
            {
                object obj = ResourceManager.GetObject("Statistical_Analysis", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        /// Gets the Stock_Exchange_01
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Stock_Exchange_01
        {
            get
            {
                object obj = ResourceManager.GetObject("Stock_Exchange_01", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        /// Gets the Text_Edit
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Text_Edit
        {
            get
            {
                object obj = ResourceManager.GetObject("Text_Edit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        /// Gets the Text_Edit_1_
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Text_Edit_1_
        {
            get
            {
                object obj = ResourceManager.GetObject("Text_Edit_1_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        /// Gets the Text_Edit_2_
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Text_Edit_2_
        {
            get
            {
                object obj = ResourceManager.GetObject("Text_Edit_2_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        /// Gets the Text_Edit_3_
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Text_Edit_3_
        {
            get
            {
                object obj = ResourceManager.GetObject("Text_Edit_3_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        /// Gets the Text_Edit_4_
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Text_Edit_4_
        {
            get
            {
                object obj = ResourceManager.GetObject("Text_Edit_4_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        /// Gets the Tools_02
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Tools_02
        {
            get
            {
                object obj = ResourceManager.GetObject("Tools_02", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        /// Gets the Transaction_Fee_WF
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Transaction_Fee_WF
        {
            get
            {
                object obj = ResourceManager.GetObject("Transaction_Fee_WF", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        /// Gets the Transfer_Arrows
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Transfer_Arrows
        {
            get
            {
                object obj = ResourceManager.GetObject("Transfer_Arrows", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        /// Gets the unnamed
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap unnamed
        {
            get
            {
                object obj = ResourceManager.GetObject("unnamed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        /// Gets the Upload
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Upload
        {
            get
            {
                object obj = ResourceManager.GetObject("Upload", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        /// Gets the Wallet_WF
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Wallet_WF
        {
            get
            {
                object obj = ResourceManager.GetObject("Wallet_WF", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
