//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BudgetExecution.resources
{
    /// <summary>
    /// A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class FormImages
    {
        /// <summary>
        /// Defines the resourceMan
        /// </summary>
        private static global::System.Resources.ResourceManager resourceMan;

        /// <summary>
        /// Defines the resourceCulture
        /// </summary>
        private static global::System.Globalization.CultureInfo resourceCulture;

        /// <summary>
        /// Initializes a new instance of the <see cref="FormImages"/> class.
        /// </summary>
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FormImages()
        {
        }

        /// <summary>
        /// Gets the ResourceManager
        /// Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if(object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BudgetExecution.resources.FormImages", typeof(FormImages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        /// Gets or sets the Culture
        /// Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        /// <summary>
        /// Gets the _123
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _123
        {
            get
            {
                object obj = ResourceManager.GetObject("_123", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        /// Gets the _171016
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _171016
        {
            get
            {
                object obj = ResourceManager.GetObject("_171016", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        /// Gets the _218325_1_m
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _218325_1_m
        {
            get
            {
                object obj = ResourceManager.GetObject("_218325_1_m", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        /// Gets the _699434_icon_70_document_file_pdf_128
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _699434_icon_70_document_file_pdf_128
        {
            get
            {
                object obj = ResourceManager.GetObject("_699434_icon_70_document_file_pdf_128", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        /// Gets the AboutUs_Icons_Frame5a_Cirlces
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap AboutUs_Icons_Frame5a_Cirlces
        {
            get
            {
                object obj = ResourceManager.GetObject("AboutUs_Icons_Frame5a_Cirlces", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        /// Gets the Actions_view_calendar_icon_budget
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Actions_view_calendar_icon_budget
        {
            get
            {
                object obj = ResourceManager.GetObject("Actions_view_calendar_icon_budget", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        /// Gets the api
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap api
        {
            get
            {
                object obj = ResourceManager.GetObject("api", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        /// Gets the blockchain
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap blockchain
        {
            get
            {
                object obj = ResourceManager.GetObject("blockchain", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        /// Gets the bo_icon
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap bo_icon
        {
            get
            {
                object obj = ResourceManager.GetObject("bo_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        /// Gets the budget
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap budget
        {
            get
            {
                object obj = ResourceManager.GetObject("budget", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        /// Gets the charts_512
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap charts_512
        {
            get
            {
                object obj = ResourceManager.GetObject("charts_512", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        /// Gets the Data_Analysis
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Data_Analysis
        {
            get
            {
                object obj = ResourceManager.GetObject("Data_Analysis", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        /// Gets the document__1_
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap document__1_
        {
            get
            {
                object obj = ResourceManager.GetObject("document__1_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        /// Gets the Dollar_Money_Time_Payment_Savings_Earnings_Salary_512
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Dollar_Money_Time_Payment_Savings_Earnings_Salary_512
        {
            get
            {
                object obj = ResourceManager.GetObject("Dollar_Money_Time_Payment_Savings_Earnings_Salary_512", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        /// Gets the download
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap download
        {
            get
            {
                object obj = ResourceManager.GetObject("download", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        /// Gets the download__1_
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap download__1_
        {
            get
            {
                object obj = ResourceManager.GetObject("download__1_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        /// Gets the entity_relationship_model_icon
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap entity_relationship_model_icon
        {
            get
            {
                object obj = ResourceManager.GetObject("entity_relationship_model_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        /// Gets the epadarklogoicon
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap epadarklogoicon
        {
            get
            {
                object obj = ResourceManager.GetObject("epadarklogoicon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        /// Gets the EXPLAIN_FORMATJSON
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap EXPLAIN_FORMATJSON
        {
            get
            {
                object obj = ResourceManager.GetObject("EXPLAIN_FORMATJSON", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        /// Gets the ezlizbpckwswoqjbfjaa
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ezlizbpckwswoqjbfjaa
        {
            get
            {
                object obj = ResourceManager.GetObject("ezlizbpckwswoqjbfjaa", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        /// Gets the federalbudget_icon
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap federalbudget_icon
        {
            get
            {
                object obj = ResourceManager.GetObject("federalbudget_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        /// Gets the Financial_Report_512
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Financial_Report_512
        {
            get
            {
                object obj = ResourceManager.GetObject("Financial_Report_512", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        /// Gets the financial_report_business_chart_finance_372ebde1c24ba979_512x512
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap financial_report_business_chart_finance_372ebde1c24ba979_512x512
        {
            get
            {
                object obj = ResourceManager.GetObject("financial_report_business_chart_finance_372ebde1c24ba979_512x512", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        /// Gets the Financial_Report_slider2
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Financial_Report_slider2
        {
            get
            {
                object obj = ResourceManager.GetObject("Financial_Report_slider2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        /// Gets the financial_reports_icon
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap financial_reports_icon
        {
            get
            {
                object obj = ResourceManager.GetObject("financial_reports_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        /// Gets the Financial_Transactions_256
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Financial_Transactions_256
        {
            get
            {
                object obj = ResourceManager.GetObject("Financial_Transactions_256", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        /// Gets the financialreports
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap financialreports
        {
            get
            {
                object obj = ResourceManager.GetObject("financialreports", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        /// Gets the fiscal_year_2015_budget
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap fiscal_year_2015_budget
        {
            get
            {
                object obj = ResourceManager.GetObject("fiscal_year_2015_budget", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        /// Gets the govreporting
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap govreporting
        {
            get
            {
                object obj = ResourceManager.GetObject("govreporting", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        /// Gets the icon_analysis500x500
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icon_analysis500x500
        {
            get
            {
                object obj = ResourceManager.GetObject("icon_analysis500x500", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        /// Gets the icon_budget
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icon_budget
        {
            get
            {
                object obj = ResourceManager.GetObject("icon_budget", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        /// Gets the icon_innovation__1_
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icon_innovation__1_
        {
            get
            {
                object obj = ResourceManager.GetObject("icon_innovation__1_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        /// Gets the images__1_
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap images__1_
        {
            get
            {
                object obj = ResourceManager.GetObject("images__1_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        /// Gets the images__11_
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap images__11_
        {
            get
            {
                object obj = ResourceManager.GetObject("images__11_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        /// Gets the images__12_
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap images__12_
        {
            get
            {
                object obj = ResourceManager.GetObject("images__12_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        /// Gets the images__14_
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap images__14_
        {
            get
            {
                object obj = ResourceManager.GetObject("images__14_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        /// Gets the images__7_
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap images__7_
        {
            get
            {
                object obj = ResourceManager.GetObject("images__7_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        /// Gets the iStock_000006161493Medium_puzzle
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap iStock_000006161493Medium_puzzle
        {
            get
            {
                object obj = ResourceManager.GetObject("iStock_000006161493Medium_puzzle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        /// Gets the Jigsaw
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Jigsaw
        {
            get
            {
                object obj = ResourceManager.GetObject("Jigsaw", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        /// Gets the jigsaw_puzzle_and_three_lessons_learned
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap jigsaw_puzzle_and_three_lessons_learned
        {
            get
            {
                object obj = ResourceManager.GetObject("jigsaw_puzzle_and_three_lessons_learned", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        /// Gets the kn1100207198
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap kn1100207198
        {
            get
            {
                object obj = ResourceManager.GetObject("kn1100207198", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        /// Gets the mmbanner
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap mmbanner
        {
            get
            {
                object obj = ResourceManager.GetObject("mmbanner", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        /// Gets the money_deadline_clock_coin_time_timer_budget_planning_3558282585efb7d3_512x512
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap money_deadline_clock_coin_time_timer_budget_planning_3558282585efb7d3_512x512
        {
            get
            {
                object obj = ResourceManager.GetObject("money_deadline_clock_coin_time_timer_budget_planning_3558282585efb7d3_512x512", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        /// Gets the montr_400x284_jpg_pagespeed_ce_kbr0KFiWwq
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap montr_400x284_jpg_pagespeed_ce_kbr0KFiWwq
        {
            get
            {
                object obj = ResourceManager.GetObject("montr_400x284_jpg_pagespeed_ce_kbr0KFiWwq", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        /// Gets the Planning_and_Budget_Header
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Planning_and_Budget_Header
        {
            get
            {
                object obj = ResourceManager.GetObject("Planning_and_Budget_Header", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        /// Gets the planning_graphic
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap planning_graphic
        {
            get
            {
                object obj = ResourceManager.GetObject("planning_graphic", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        /// Gets the Predictive_modeling
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Predictive_modeling
        {
            get
            {
                object obj = ResourceManager.GetObject("Predictive_modeling", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        /// Gets the reporting_and_data_visualization_500x500
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap reporting_and_data_visualization_500x500
        {
            get
            {
                object obj = ResourceManager.GetObject("reporting_and_data_visualization_500x500", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        /// Gets the reporting_icon
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap reporting_icon
        {
            get
            {
                object obj = ResourceManager.GetObject("reporting_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        /// Gets the resource_builder_01_1_e1503604315834
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap resource_builder_01_1_e1503604315834
        {
            get
            {
                object obj = ResourceManager.GetObject("resource_builder_01_1_e1503604315834", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        /// Gets the RTR4NYEF_1024x683
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap RTR4NYEF_1024x683
        {
            get
            {
                object obj = ResourceManager.GetObject("RTR4NYEF_1024x683", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        /// Gets the rzbwrruiezaxgfxmanva
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rzbwrruiezaxgfxmanva
        {
            get
            {
                object obj = ResourceManager.GetObject("rzbwrruiezaxgfxmanva", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        /// Gets the Screen_Shot_2012_04_18_at_2_43_23_PM_366x327
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Screen_Shot_2012_04_18_at_2_43_23_PM_366x327
        {
            get
            {
                object obj = ResourceManager.GetObject("Screen_Shot_2012_04_18_at_2_43_23_PM_366x327", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        /// Gets the SEO_icon
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap SEO_icon
        {
            get
            {
                object obj = ResourceManager.GetObject("SEO_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        /// Gets the sql_595x335_0
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap sql_595x335_0
        {
            get
            {
                object obj = ResourceManager.GetObject("sql_595x335_0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        /// Gets the stakeholder_analysis_project_success
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap stakeholder_analysis_project_success
        {
            get
            {
                object obj = ResourceManager.GetObject("stakeholder_analysis_project_success", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        /// Gets the stock_photo__d_budget_federal_text_crossword_on_white_background_96102830
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap stock_photo__d_budget_federal_text_crossword_on_white_background_96102830
        {
            get
            {
                object obj = ResourceManager.GetObject("stock_photo__d_budget_federal_text_crossword_on_white_background_96102830", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        /// Gets the stock_photo_budgeting_concept_metallic_keyboard_with_budgeting_selected_focus_on_blue_enter_button_d_render_475163416
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap stock_photo_budgeting_concept_metallic_keyboard_with_budgeting_selected_focus_on_blue_enter_button_d_render_475163416
        {
            get
            {
                object obj = ResourceManager.GetObject("stock_photo_budgeting_concept_metallic_keyboard_with_budgeting_selected_focus_on_" +
                        "blue_enter_button_d_render_475163416", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        /// Gets the stock_vector_general_expenses_budget_planning_business_icon_flat_vector_illustration_494432347
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap stock_vector_general_expenses_budget_planning_business_icon_flat_vector_illustration_494432347
        {
            get
            {
                object obj = ResourceManager.GetObject("stock_vector_general_expenses_budget_planning_business_icon_flat_vector_illustrat" +
                        "ion_494432347", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        /// Gets the stock_vector_info_graphic_reporting_and_searching_template_eps_file_1877133681
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap stock_vector_info_graphic_reporting_and_searching_template_eps_file_1877133681
        {
            get
            {
                object obj = ResourceManager.GetObject("stock_vector_info_graphic_reporting_and_searching_template_eps_file_1877133681", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        /// Gets the summary
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap summary
        {
            get
            {
                object obj = ResourceManager.GetObject("summary", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        /// Gets the Talend_Data_Model_Best_Practices_Part_2_1_250x250
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Talend_Data_Model_Best_Practices_Part_2_1_250x250
        {
            get
            {
                object obj = ResourceManager.GetObject("Talend_Data_Model_Best_Practices_Part_2_1_250x250", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        /// Gets the tile_template_appropriations
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap tile_template_appropriations
        {
            get
            {
                object obj = ResourceManager.GetObject("tile_template_appropriations", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        /// Gets the tile_template_boc
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap tile_template_boc
        {
            get
            {
                object obj = ResourceManager.GetObject("tile_template_boc", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        /// Gets the tile_template_budget_activity
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap tile_template_budget_activity
        {
            get
            {
                object obj = ResourceManager.GetObject("tile_template_budget_activity", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        /// Gets the tile_template_division
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap tile_template_division
        {
            get
            {
                object obj = ResourceManager.GetObject("tile_template_division", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        /// Gets the tile_template_obligations
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap tile_template_obligations
        {
            get
            {
                object obj = ResourceManager.GetObject("tile_template_obligations", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        /// Gets the tile_template_StatusOfFunds
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap tile_template_StatusOfFunds
        {
            get
            {
                object obj = ResourceManager.GetObject("tile_template_StatusOfFunds", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        /// Gets the Trading
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Trading
        {
            get
            {
                object obj = ResourceManager.GetObject("Trading", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        /// Gets the Transfer_Arrows
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Transfer_Arrows
        {
            get
            {
                object obj = ResourceManager.GetObject("Transfer_Arrows", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        /// Gets the TripBossEBI_webicon
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TripBossEBI_webicon
        {
            get
            {
                object obj = ResourceManager.GetObject("TripBossEBI_webicon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        /// Gets the x_46_512
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap x_46_512
        {
            get
            {
                object obj = ResourceManager.GetObject("x_46_512", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        /// Gets the xls
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap xls
        {
            get
            {
                object obj = ResourceManager.GetObject("xls", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
