//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BudgetExecution.resources
{
    /// <summary>
    /// A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class NinjaIcons
    {
        /// <summary>
        /// Defines the resourceMan
        /// </summary>
        private static global::System.Resources.ResourceManager resourceMan;

        /// <summary>
        /// Defines the resourceCulture
        /// </summary>
        private static global::System.Globalization.CultureInfo resourceCulture;

        /// <summary>
        /// Initializes a new instance of the <see cref="NinjaIcons"/> class.
        /// </summary>
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal NinjaIcons()
        {
        }

        /// <summary>
        /// Gets the ResourceManager
        /// Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if(object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BudgetExecution.resources.NinjaIcons", typeof(NinjaIcons).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        /// Gets or sets the Culture
        /// Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        /// <summary>
        /// Gets the appropriation_icon1
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap appropriation_icon1
        {
            get
            {
                object obj = ResourceManager.GetObject("appropriation_icon1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        /// Gets the appropriation_icon2
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap appropriation_icon2
        {
            get
            {
                object obj = ResourceManager.GetObject("appropriation_icon2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        /// Gets the bluedatabase
        /// Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon bluedatabase
        {
            get
            {
                object obj = ResourceManager.GetObject("bluedatabase", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }

        /// <summary>
        /// Gets the BudgetNinja
        /// Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon BudgetNinja
        {
            get
            {
                object obj = ResourceManager.GetObject("BudgetNinja", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }

        /// <summary>
        /// Gets the epa_seal_medium1
        /// Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon epa_seal_medium1
        {
            get
            {
                object obj = ResourceManager.GetObject("epa_seal_medium1", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }

        /// <summary>
        /// Gets the if_6_1376009
        /// Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon if_6_1376009
        {
            get
            {
                object obj = ResourceManager.GetObject("if_6_1376009", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }

        /// <summary>
        /// Gets the if_bar_chart_87411
        /// Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon if_bar_chart_87411
        {
            get
            {
                object obj = ResourceManager.GetObject("if_bar-chart_87411", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }

        /// <summary>
        /// Gets the if_pie_chart_87451
        /// Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon if_pie_chart_87451
        {
            get
            {
                object obj = ResourceManager.GetObject("if_pie-chart_87451", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }

        /// <summary>
        /// Gets the if_processing_2799201__1_
        /// Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon if_processing_2799201__1_
        {
            get
            {
                object obj = ResourceManager.GetObject("if_processing_2799201 (1)", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }

        /// <summary>
        /// Gets the if_transfer_87476
        /// Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon if_transfer_87476
        {
            get
            {
                object obj = ResourceManager.GetObject("if_transfer_87476", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }

        /// <summary>
        /// Gets the pie_chart
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pie_chart
        {
            get
            {
                object obj = ResourceManager.GetObject("pie_chart", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        /// Gets the RA
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap RA
        {
            get
            {
                object obj = ResourceManager.GetObject("RA", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        /// Gets the report_icon
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap report_icon
        {
            get
            {
                object obj = ResourceManager.GetObject("report_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        /// Gets the sf_site_icon
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap sf_site_icon
        {
            get
            {
                object obj = ResourceManager.GetObject("sf_site_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        /// Gets the sql_icon
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap sql_icon
        {
            get
            {
                object obj = ResourceManager.GetObject("sql_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        /// Gets the summation_3d_blue_oma_icon
        /// Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon summation_3d_blue_oma_icon
        {
            get
            {
                object obj = ResourceManager.GetObject("summation_3d_blue_oma_icon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }

        /// <summary>
        /// Gets the transfer_icon
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap transfer_icon
        {
            get
            {
                object obj = ResourceManager.GetObject("transfer_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
