//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BudgetExecution.resources
{
    /// <summary>
    /// A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SlideImages
    {
        /// <summary>
        /// Defines the resourceMan
        /// </summary>
        private static global::System.Resources.ResourceManager resourceMan;

        /// <summary>
        /// Defines the resourceCulture
        /// </summary>
        private static global::System.Globalization.CultureInfo resourceCulture;

        /// <summary>
        /// Initializes a new instance of the <see cref="SlideImages"/> class.
        /// </summary>
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SlideImages()
        {
        }

        /// <summary>
        /// Gets the ResourceManager
        /// Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if(object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BudgetExecution.resources.SlideImages", typeof(SlideImages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        /// Gets or sets the Culture
        /// Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        /// <summary>
        /// Gets the AppropriationImages
        /// Looks up a localized string similar to C:\Users\terry\Documents\Visual Studio 2017\Projects\BudgetExecution\Ninja\Resources\AppropriationImages.
        /// </summary>
        internal static string AppropriationImages
        {
            get
            {
                return ResourceManager.GetString("AppropriationImages", resourceCulture);
            }
        }

        /// <summary>
        /// Gets the DatabaseImages
        /// Looks up a localized string similar to C:\Users\terry\Documents\Visual Studio 2017\Projects\BudgetExecution\Ninja\Resources\DatabaseImages.
        /// </summary>
        internal static string DatabaseImages
        {
            get
            {
                return ResourceManager.GetString("DatabaseImages", resourceCulture);
            }
        }

        /// <summary>
        /// Gets the DivisionImages
        /// Looks up a localized string similar to C:\Users\terry\Documents\Visual Studio 2017\Projects\BudgetExecution\Ninja\Resources\DivisionImages.
        /// </summary>
        internal static string DivisionImages
        {
            get
            {
                return ResourceManager.GetString("DivisionImages", resourceCulture);
            }
        }

        /// <summary>
        /// Gets the Enter
        /// Looks up a localized string similar to C:\Users\terry\Documents\Visual Studio 2017\Projects\BudgetExecution\Ninja\Resources\enter.
        /// </summary>
        internal static string Enter
        {
            get
            {
                return ResourceManager.GetString("Enter", resourceCulture);
            }
        }

        /// <summary>
        /// Gets the FunctionImages
        /// Looks up a localized string similar to C:\Users\terry\Documents\Visual Studio 2017\Projects\BudgetExecution\Ninja\Resources\FunctionImages.
        /// </summary>
        internal static string FunctionImages
        {
            get
            {
                return ResourceManager.GetString("FunctionImages", resourceCulture);
            }
        }

        /// <summary>
        /// Gets the SummaryImages
        /// Looks up a localized string similar to C:\Users\terry\Documents\Visual Studio 2017\Projects\BudgetExecution\Ninja\Resources\SummaryImages.
        /// </summary>
        internal static string SummaryImages
        {
            get
            {
                return ResourceManager.GetString("SummaryImages", resourceCulture);
            }
        }
    }
}
